### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ajs031985** [elasticsearch-dump/elasticsearch-dump#1000]
- ElasticDump version - 6.82.3
- Elasticsearch version - 7.17.8 (Elastic cloud)
- Node.js version *(note that nodejs v10+ is required for this tool)* - 17.9.0

**Describe the bug**
We have build a java framework around the elasticdump utility to transfer records based on some search queries on timestamps. The java process runs every 15 mins and transfers the delta data to the backup cluster. We are using the java process builder to run the elasticdump commands with a search body to selectively transfer the data. After java process is created it waits for the elasticdump response. This is working as expected, but from time to time we find the java process to await indefinitely waiting on the elasticdump command to complete.

To rule out any issues with the java process we did try manually running the same elasticdump commands several time and we have seen from the outputs generated by elasticdump that process just stops without doing any more data transfer.

Below is the logs of one such instance where we can see the data transfer has stopped without completing or erroring out.
![image](https://github.com/elasticsearch-dump/elasticsearch-dump/assets/108987075/549f2c42-f5b6-4d66-ab47-c1476cd1ef16)

no logs after this...

Is there something that can be done to figure out the problem? 

Below is the command we are using to transfer the data for one of the indices

elasticdump --input=${SEC_PROTOCOL}://${SEC_USERNAME}:${SEC_PASSWORD}@${SEC_HOST}:${SEC_PORT}/segment-20231008 --output=${PRI_PROTOCOL}://${PRI_USERNAME}:${PRI_PASSWORD}@${PRI_HOST}:${PRI_PORT} --type=data --limit=1000 --searchBody="{\"query\":{\"bool\":{\"must\":[{\"query_string\":{\"default_field\":\"<fieldname>\",\"query\":\"<field_value>\"}}]}}}"

**Comment by ferronrsmith** [comment]
The issue could be the size of the file. When you're dumping large amount of data it might cause issues for some system since you're writing a buffer to a very large file, i.e. the OS might not be able to keep up.

I would recommend trying to use `--fileSize` just to see if this helps your situation.

**Comment by ferronrsmith** [comment]
Try using the `--debug` and see if that helps. Also take a look at `--retryAttempts`., this is 0 by default, can be used in combination with `--retryDelay` (default: 5000 milliseconds). 

Sometimes elasticsearch or the network may drop connection. Retrying just to see if it helps

**Comment by ajs031985** [comment]
with --debug enabled we didn't get much insight.. it was additionally logging the scroll id but at the end it just stopped like earlier.

with retryAttempts flag set it will only retry on failures, right?

Because the problem here is it doesn't fails gracefully to get a handle. It just stops the data transfer. Ideally the process should exit with or without failures.  

On the node side, can we add some properties to log more info like uncaught exceptions, etc?

**Comment by ferronrsmith** [comment]
I'll add a flag to check for uncaught exceptions.

**Comment by ferronrsmith** [comment]
https://github.com/elasticsearch-dump/elasticsearch-dump/blob/master/bin/elasticdump#L151-L160

@L151 you can add the following to your installation and test

```javascript
process
  .on('unhandledRejection', (reason, p) => {
    console.error(reason, 'Unhandled Rejection at Promise', p);
  })
  .on('uncaughtException', err => {
    console.error(err, 'Uncaught Exception thrown');
    process.exit(1);
  });
```

**Comment by ajs031985** [comment]
since we are creating a image with the java framework, we just install the elasticdump package.. so changing the executable is not feasible for us.

Will it be possible to create a build with the changes.. Thanks

**Comment by ferronrsmith** [comment]
Yea sure.

**Comment by ferronrsmith** [comment]
added to https://github.com/elasticsearch-dump/elasticsearch-dump/releases/tag/v6.104.2
