### ISSUE TITLE
[BUG] Fields that only exist in some documents were not exported to CSV

### ISSUE THREAD

**Issue by lenovore** [elasticsearch-dump/elasticsearch-dump#1001]
- ElasticDump version 6.104.1
- Elasticsearch version 7.10.2

**Describe the bug**
Use -- searchBody and specify _source, assuming the value of _source is [a, b, c], where field b only exists in some documents. If the first document record does not include field b during export, the final exported CSV only contains fields a, c.

**Expected behavior**
Regardless of whether the fields exist in the document, all fields in the source should be exported to CSV. If they do not exist, empty values can be used to replace them

**Screenshots**
The first row of exported document data has corresponding fields
![image](https://github.com/elasticsearch-dump/elasticsearch-dump/assets/29646774/4585186c-e7ad-41ed-a60a-b6c1f4d31487)
The first row of exported document data does not have a corresponding field
![image](https://github.com/elasticsearch-dump/elasticsearch-dump/assets/29646774/d32c0832-92b2-4ee2-880e-c416a6221609)

**Comment by ferronrsmith** [comment]
That's a consequence of the underlying library. You can use the `--csvRenameHeaders --csvCustomHeaders=<comma seperated list of headers>` flag to specify all headers
