### ISSUE TITLE
[FEATURE] Match on datastream name

### ISSUE THREAD

**Issue by vfronterotta** [elasticsearch-dump/elasticsearch-dump#1003]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump 6.104.2
- Elasticsearch 8.10
- Node.js version v21.1.0
- Full command you are having issue with:

```bash
AWS_PROFILE="myprofile" multielasticdump \
    --noRefresh \
    --awsChain \
    --headers='{"Authorization": "Basic '${elasticsearch_token}'"}' \
    --direction="dump" \
    --includeType="data" \
    --size="$size" \
    --match=".*traces.*" \
    --input="https://my.es.com" \
    --output="s3://${bucket}/${project}/${env}/${current_date}"
```

**Describe the bug**
I have everything working as expected for regular indices and I get the expected output in my s3 bucket. My issue is that for datastreams it seems like we need to add aliases to every datastream for this to work. Is there any way to match on datastream names instead of on aliases?

Here is what my example working template looks like:
```json
{
  "template": {
    "settings": {
      "index": {
        "lifecycle": {
          "name": "logs-policy",
          "rollover_alias": "my-traces-logs"
        },
        "routing": {
          "allocation": {
            "include": {
              "_tier_preference": "data_hot"
            }
          }
        },
        "mapping": {
          "total_fields": {
            "limit": "1500"
          }
        }
      }
    },
    "aliases": {
      "my-traces-alias": {}
    },
    "mappings": {}
  }
}
```

Our datastream index templates do not normally have this aliases section and ideally I would like to enable matching on the datastream name instead of this alias

**Comment by ferronrsmith** [comment]
By default we do lookup on alias endpoint for indices. This isn't a bug, you're requesting doing lookup on datastreams, which currently isn't supported, hence the need to alias

**Comment by vfronterotta** [comment]
Ok, thanks for the response! I wasn't sure if this was supposed to work or not so I flagged it as a bug but yes if we could treat it as a feature request then that would be great. 

Maybe having something like `matchType` param that defaults to "alias", so it doesn't break anything, with similar syntax as ignoreType and includeType?
e.g:  
- `alias` (GET /_alias)
- `datastream` (GET /_data_stream)
- `alias,datastream` (GET /_alias and GET /_data_stream)

Another potential option later on that could be explored would be index_template but I don't know if there is any need for it.

Let me know if this makes sense and if you need anything from my side

**Comment by ferronrsmith** [comment]
What are you matching on ? The index the datastream is attached or datastream itself ?

```json
{
  "data_streams": [
    {
      "name": "my-data-stream",
      "timestamp_field": {
        "name": "@timestamp"
      },
      "indices": [
        {
          "index_name": ".ds-my-data-stream-2099.03.07-000001",
          "index_uuid": "xCEhwsp8Tey0-FLNFYVwSg",
          "prefer_ilm": true,
          "ilm_policy": "my-lifecycle-policy",
          "managed_by": "Index Lifecycle Management"
        },
        {
          "index_name": ".ds-my-data-stream-2099.03.08-000002",
          "index_uuid": "PA_JquKGSiKcAKBA8DJ5gw",
          "prefer_ilm": true,
          "ilm_policy": "my-lifecycle-policy",
          "managed_by": "Index Lifecycle Management"
        }
      ],
      "generation": 2,
      "_meta": {
        "my-meta-field": "foo"
      },
      "status": "GREEN",
      "next_generation_managed_by": "Index Lifecycle Management",
      "prefer_ilm": true,
      "template": "my-index-template",
      "ilm_policy": "my-lifecycle-policy",
      "hidden": false,
      "system": false,
      "allow_custom_routing": false,
      "replicated": false
    },
    {
      "name": "my-data-stream-two",
      "timestamp_field": {
        "name": "@timestamp"
      },
      "indices": [
        {
          "index_name": ".ds-my-data-stream-two-2099.03.08-000001",
          "index_uuid": "3liBu2SYS5axasRt6fUIpA",
          "prefer_ilm": true,
          "ilm_policy": "my-lifecycle-policy",
          "managed_by": "Index Lifecycle Management"
        }
      ],
      "generation": 1,
      "_meta": {
        "my-meta-field": "foo"
      },
      "status": "YELLOW",
      "next_generation_managed_by": "Index Lifecycle Management",
      "prefer_ilm": true,
      "template": "my-index-template",
      "ilm_policy": "my-lifecycle-policy",
      "hidden": false,
      "system": false,
      "allow_custom_routing": false,
      "replicated": false
    }
  ]
}
```

**Comment by vfronterotta** [comment]
I am matching on the datastream itself

**Comment by ferronrsmith** [comment]
I am more inclined to expose the matching function to allow developer to use their own matching function.

--match=`@/match.js` <-- must return a list
--match=`function(){return list_of_indices }`


I'll push a first draft out soon, so you can test.

**Comment by ferronrsmith** [comment]
Here is a PR - https://github.com/elasticsearch-dump/elasticsearch-dump/pull/1004.

Test and let me know if this works for you.

**Comment by vfronterotta** [comment]
I just tested and it is calling /_data_stream correctly now but the mapping doesn't seem to be working as it isn't finding anything. 

```
Thu, 09 Nov 2023 00:34:13 GMT [debug] | GET /_data_stream
(node:66077) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
Thu, 09 Nov 2023 00:34:13 GMT [debug] | GET /_data_stream -> 200 OK
Thu, 09 Nov 2023 00:34:13 GMT |  dumping all done
Thu, 09 Nov 2023 00:34:13 GMT |  bye
Finished dump from staging for .*traces.* pattern
```

**Comment by vfronterotta** [comment]
I don't write JS usually but do we need the map? The following seems to work:

`matchedIndexes = response.data_streams.filter(stream => matchRegExp.test(stream.name))`

```
Filtered Streams: [
  'diameter-cca-data-rg-traces',
  'diameter-cca-data-traces',
  'diameter-cca-events-traces',
  'diameter-cca-voice-traces',
  'diameter-gx-traces',
  'diameter-traces',
  'map-traces',
  'sctp-traces',
  'traces-apm-default',
  'traces-apm.rum-default',
  'traces-telecom-diameter-cx',
  'traces-telecom-diameter-gx',
  'traces-telecom-diameter-gy',
  'traces-telecom-diameter-ro-voice',
  'traces-telecom-diameter-s6a',
  'traces-telecom-diameter-sh',
  'traces-telecom-map',
  'traces-telecom-sctp'
]
```

**Comment by vfronterotta** [comment]
Deleted last comment, was running previous code for that to work. I just changed 

`matchedIndexes = response.data_streams.filter(stream => matchRegExp.test(stream)).map(stream => stream.name)`
to
`matchedIndexes = response.data_streams.filter(stream => matchRegExp.test(stream.name)).map(stream => stream.name)`

**Comment by ferronrsmith** [comment]
did you pass in the `--matchType=datastream` ?

**Comment by ferronrsmith** [comment]
ok everything should be squared away with this. Test and let me know, and I'll merge this in the AM.

Thanks for testing

**Comment by vfronterotta** [comment]
Awesome, thanks for the quick work.

Everything works with the latest changes for me on the following test cases:
- `--matchType="alias"`
- `--matchType="datastream"`
- `--matchType="alias,datastream"`
- No matchType

Added a small comment on the PR for the README but everything looks good otherwise

**Comment by ferronrsmith** [comment]
ok updated readme. I'll release this in the AM.  Thanks for testing.

**Comment by ferronrsmith** [comment]
changes released in https://github.com/elasticsearch-dump/elasticsearch-dump/releases/tag/v6.106.0
