### ISSUE TITLE
[FEATURE] Importing data with index name with special chars creates a new index with encoded special chars

### ISSUE THREAD

**Issue by Trekky12** [elasticsearch-dump/elasticsearch-dump#1005]
**Context**
I have a index with special characters in the index-name (it is a ";"). I exported the index with multielasticdump.
Afterwards I tried an import in an empty elasticsearch instance.

- ElasticDump version 6.104.2
- Elasticsearch version 7.8.1
- Node.js version *(note that nodejs v10+ is required for this tool)* v20.9.0
- Full command you are having issue with (with inputs and outputs): `>multielasticdump --direction=load --input=testdata --output=http://<ip>:9200 --includeType=settings,data`
- A data-set you can share publicly which reproduces the problem:

test-data;info;version=1.settings.json
```
"{\"test-data;info;version=1\":{\"settings\":{}},\"test-data%3binfo%3bversion%3d1\":{}}"
```
test-data;info;version=1.json:
```
{"_index":"test-data;info;version=1","_type":"_doc","_id":"1234","_score":1,"_source":{},"fields":{}}
```

**Describe the bug**
When importing the index is created with the settings file and correctly named `test-data;info;version=1`. 
When the data file is imported elasticdump can't find the index and creates a new index with the encoded special characters (`test-data%3binfo%3bversion%3d1`) instead of using the already existing index with the decoded component (test-data;info;version=1).

**Expected behavior**
When the index exists elasticdump should use the existing index. Otherwise a index with the decoded special characters should be created.

**Additional context**
Apparently when using the `_bulk` import the index name is retrieved from the encoded uri of the index. It would be better to either decode the uri or prefer the (correct) value of the key "_index" in the data file.

The solution can be here:
https://github.com/elasticsearch-dump/elasticsearch-dump/blob/7c4fb60941eae1baa2b42e8fa5e46366f3e595de/lib/transports/__es__/_data.js#L127

Suggestion 1:
```
 actionMeta[bulkAction]._index = decodeURIComponent(this.base.index) || elem._index
```
Suggestion 2:
```
 actionMeta[bulkAction]._index = elem._index || this.base.index
```

**Comment by ferronrsmith** [comment]
This isn't a bug. This is a feature request

**Comment by Trekky12** [comment]
Okay, but in my specific case this is an breaking error, because the exported files are not able to be imported. 
Should I make a PR for a change? What suggestion do you prefer?

**Comment by ferronrsmith** [comment]
Here is a PR https://github.com/elasticsearch-dump/elasticsearch-dump/pull/1006. Test and let me know if this works for you.

**Comment by ferronrsmith** [comment]
changes are in https://github.com/elasticsearch-dump/elasticsearch-dump/releases/tag/v6.105.0
