### ISSUE TITLE
[BUG] Mappings with the key "properties" are not able to be parsed

### ISSUE THREAD

**Issue by Trekky12** [elasticsearch-dump/elasticsearch-dump#1007]
**Context**
I have a index with a mapping key "properties". The index was exported with multielasticdump.
Afterwards I tried an import in an empty elasticsearch instance.

- ElasticDump version 6.104.2
- Elasticsearch version 7.8.1
- Node.js version *(note that nodejs v10+ is required for this tool)* v20.9.0
- Full command you are having issue with (with inputs and outputs): `>multielasticdump --direction=load --input=testdata --output=http://<ip>:9200 --includeType=mapping`
- A data-set you can share publicly which reproduces the problem:

test-data;info;version=1.mapping.json
```
{
    "test-data;info;version=1": {
        "mappings": {
            "properties": {
                "properties": {
                    "type": "keyword"
                }
            }
        }
    }
}
```

**Describe the bug**
After the settings file is imported and the index is created I tried to set the mappings.
Unfortunately this is not working with the error:
```
Error Emitted => {"root_cause":[{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}],"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}
```

Apparently the keys are not merged as expected because the generated json payload is:
```
{
  url: 'http://<ip>:9200/test-data%3binfo%3bversion%3d1/_mapping',
  method: 'PUT',
  body: '{"properties":{"type":"keyword"}}'
}
```

When the key is renamed to e.g. properties1 everything is working as expected and the following (correct) payload is generated:
```
{
  url: 'http://<ip>:9200/test-data%3binfo%3bversion%3d1/_mapping',
  method: 'PUT',
  body: '{"properties":{"properties1":{"type":"keyword"}}}'
}
```

**Additional context**

Apparently the payload generation on line 86 is not used because the key "properties" already exists:

https://github.com/elasticsearch-dump/elasticsearch-dump/blob/72424aede9cc63fca55277ba8f39e94a3ac2417f/lib/transports/__es__/_mapping.js#L79-L87

If an else clause with 
```
set.data = { properties: set.data }
```
would be applied it works, but this probably breaks other cases.

**Comment by ferronrsmith** [comment]
This is a corner case. Test and let me know. Since this affects a few backward compat, i'll do some more testing before this is merged.

**Comment by Trekky12** [comment]
Thank you very much @ferronrsmith! It is working as expected 👍

**Comment by ferronrsmith** [comment]
included in https://github.com/elasticsearch-dump/elasticsearch-dump/releases/tag/v6.107.0
