### ISSUE TITLE
Dependency Update - AWS SDK V3

### ISSUE THREAD

**Issue by adam-kramer** [elasticsearch-dump/elasticsearch-dump#1009]
**Is your feature request related to a problem? Please describe.**
Requesting `aws-sdk` dependency references updated to v3. `@aws-sdk/client-{service}`

**Describe the solution you'd like**
Current implementation requires `aws-sdk@v2.x`. Should update to v3 as v2 is at end of maintenance lifecycle.

**Describe alternatives you've considered**
I could fork the repo. I think most developers would appreciate the update to stay aligned with `@aws-sdk/*` support updates and runtime dependency requirements.

**Comment by ferronrsmith** [comment]
feel free to submit a PR or fork the repository as suggested. This isn't on my roadmap until next year.
