### ISSUE TITLE
[BUG] index is 'undefined' when not setting an output index on input from file

### ISSUE THREAD

**Issue by generalus89** [elasticsearch-dump/elasticsearch-dump#1014]
**Context**
I have exported multiple indexes from an ES instance using a wildcard selector to a JSON file and want to import the exported entries into another ES instance.

- ElasticDump version _6.109.0_
- Elasticsearch version _irrelavent_ 
- Node.js version _irrelavent_
- Full command you are having issue with (with inputs and outputs) 
`elasticdump --input=http://elk1instance:9200/index* --output=index_backup.json`
`elasticdump --input=index_backup.json --output=http://elk2instance:9200`

- A data-set you can share publicly which reproduces the problem
`{
    "_index": "index-2023.07.07",
    "_id": "64a89d95fb8b88d6750e8b94835a9db32cbad685",
    "_score": 1,
    "_ignored": [
        "event.original.keyword"
    ],
    "_source": {}
}`

**Describe the bug**
When trying to reimport the entries from the JSON-file, the entries get imported with the index 'undefined' instead of - what I would expect - the given index in the source JSON-file.

**To Reproduce**
1. Export to a file from an ES instance using a wildcard index (e. g. '/index*'). 
2. Import to an ES instance from the file without giving a specific index.

**Current behavior**
Entries are getting created with the index 'undefined' when importing without given a target index in the command.

**Expected behavior**
Entries are getting created with the index of the source entry in the JSON file when importing without given a target index in the command.

**Comment by ferronrsmith** [comment]
Fix released in https://github.com/elasticsearch-dump/elasticsearch-dump/releases/tag/v6.109.1
