### ISSUE TITLE
elasticdump backup performance

### ISSUE THREAD

**Issue by multikoop** [elasticsearch-dump/elasticsearch-dump#1017]
**Describe the solution you'd like**
Need to backup multiple indices with a total amount of more than 200.000.000 docs. (some indices with 200GB s each. total amount of data: 1 TB)  After trying out with small dataset it looks like the backup would take very long.

Is elasticdump right tool for backup of such amount of data?  What would be the right settings / config parameters for backup with elasticdump to S3 ?

Thanks for any advice.

**Comment by ferronrsmith** [comment]
Only you can determine if it's the right tool.

Some jobs require a hammer, some require a power tool. I can't make that decision for you. You might be better off using the [elasticsearch snapshots](https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshot-restore.html)
