### ISSUE TITLE
[BUG] punycode module is deprecated

### ISSUE THREAD

**Issue by gw-bcharboneau** [elasticsearch-dump/elasticsearch-dump#1020]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 6.110.0
- Elasticsearch version: Multiple
- Node.js version *(note that nodejs v10+ is required for this tool)*: 21.6.1
- Full command you are having issue with (with inputs and outputs)
;elasticdump --input=https://{my-elasticsearchcluster} --output=https://{my-opensearchcluster} --type=data --limit=500
- A data-set you can share publicly which reproduces the problem
Not data related problem

**Describe the bug**

Warning displayed when running elasticdump
Wed, 31 Jan 2024 15:53:34 GMT | starting dump
(node:2260) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Wed, 31 Jan 2024 15:53:35 GMT | got 100 objects from source elasticsearch (offset: 0)

**To Reproduce**
1. run elasticdump to dump index data from one cluster to another

**Current behavior**
Describe what's happening now.
Warning about deprecated module and then process continues

**Expected behavior**
No Warning as modules would be using maintained versions

**Screenshots**

**Additional context**
Running on Windows 11 via Powershell 7.3.3 terminal
Copying Data from ES 1.5 to OS 2.11

**Comment by ferronrsmith** [comment]
This isn't something that's used by elasticsearch-dump directly. It's an upstream dependency. I will continue to monitor it and update as soon as version updates are available for the affected dependencies
