### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PrathamSoni** [elasticsearch-dump/elasticsearch-dump#1027]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump latest
- Elasticsearch 8.10.4
- Node.js v18.18.2
```elasticdump --input=https://***.us-central1.gcp.cloud.es.io:443 --s3AccessKeyId=**** --s3SecretAccessKey=*** --output=s3://****/dump1.json --awsRegion=us-east-1 --type=data --headers='{"Authorization": "ApiKey ***=="}' --maxSockets 32 --fileSize 100mb  --noRefresh --offset 3292100```

**Describe the bug**
Offst giving error 
Wed, 20 Mar 2024 22:05:58 GMT | Error Emitted => {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: using [from] is not allowed in a scroll context;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: using [from] is not allowed in a scroll context;"},"status":400}

**To Reproduce**
timed out dump tried to restart with same settings with above command

**Current behavior**
error message above 

**Expected behavior**
job restarts with offset

**Comment by ferronrsmith** [comment]
Error is clear. `--offset 3292100` isn't supported in scroll.

**Comment by PrathamSoni** [comment]
how do i skip rows then

**Comment by PrathamSoni** [comment]
```dump ended with error (get phase) => NOT_FOUND: {"error":{"root_cause":[{"type":"search_context_missing_exception","reason":"No search context found for id [6128015]"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":-1,"index":null,"reason":{"type":"search_context_missing_exception","reason":"No search context found for id [6128015]"}}],"caused_by":{"type":"search_context_missing_exception","reason":"No search context found for id [6128015]"}},"status":404}``` got this as well if you have any insights

**Comment by ferronrsmith** [comment]
Server timed out while processing. this is a really an elasticsearch issue. Try increasing the scrollTime to acomodate your processing time.
