### ISSUE TITLE
[BUG]  reference #1302

### ISSUE THREAD

**Issue by sdetweil** [elasticsearch-dump/elasticsearch-dump#1033]
i have set number of replicas to 0, and system is green, all indexes green.
```text
green open .internal.alerts-transform.health.alerts-default-000001            4pn5Hl7RTw2XjY6XTMitTg 1 0    0 0    249b    249b    249b
green open .internal.alerts-observability.logs.alerts-default-000001          51RrPAazTDyKrHFzgNLmRg 1 0    0 0    249b    249b    249b
green open .internal.alerts-observability.uptime.alerts-default-000001        b8gQVtsaQia-iJTyzCjFFw 1 0    0 0    249b    249b    249b
green open .ds-logs-generic-default-2023.08.13-000003                         k2xuuxchRlm9Y1YJbb5_6w 1 0 2227 0   2.7mb   2.7mb   2.7mb
green open .internal.alerts-ml.anomaly-detection.alerts-default-000001        Hrfhs-zOTAmxBYgawV_eGw 1 0    0 0    249b    249b    249b
green open .ds-logs-generic-default-2023.10.12-000005                         lc0qHE0kRF2KHKeXCmgsJg 1 0   82 0 204.3kb 204.3kb 204.3kb
green open .internal.alerts-observability.slo.alerts-default-000001           Zxgzua58RveGSk5sshC1ZQ 1 0    0 0    249b    249b    249b
green open .internal.alerts-default.alerts-default-000001                     UstpyAU2SVSa2ioJKD66og 1 0    0 0    249b    249b    249b
green open .internal.alerts-observability.apm.alerts-default-000001           m0T25e0OQ_ij3iWjxhfQBg 1 0    0 0    249b    249b    249b
green open .ds-logs-generic-default-2023.09.12-000004                         Nb8SMbq1QlqMwaO2ubLagA 1 0 1201 0   1.5mb   1.5mb   1.5mb
green open .internal.alerts-observability.metrics.alerts-default-000001       YIFiI3jDQLuzDF-4BuZBAA 1 0    0 0    249b    249b    249b
green open .kibana-observability-ai-assistant-conversations-000001            L07ihP92S5SmAA9VWs_J6Q 1 0    0 0    249b    249b    249b
green open .internal.alerts-ml.anomaly-detection-health.alerts-default-000001 Zf8TDGGPR4yjHytXW2NbDA 1 0    0 0    249b    249b    249b
green open .internal.alerts-observability.threshold.alerts-default-000001     WxRy8xIGTAud7ctx79s_AA 1 0    0 0    249b    249b    249b
green open .ds-logs-generic-default-2024.02.02-000008                         BSKPNM7aSueWyG1Ollf-Tw 1 0   15 0  57.8kb  57.8kb  57.8kb
green open .ds-logs-generic-default-2023.07.14-000002                         HF-cHvjvR7mD48_PkmxB8A 1 0 1030 0   1.2mb   1.2mb   1.2mb
green open .ds-logs-generic-default-2023.11.26-000006                         qCacTx5IQsamA4n38isf-A 1 0   21 0 102.6kb 102.6kb 102.6kb
green open .kibana-observability-ai-assistant-kb-000001                       INk5UBC4T5Gp0q0VTB-d0Q 1 0    0 0    249b    249b    249b
green open .internal.alerts-security.alerts-default-000001                    yGYMwJdzSI2Gt-cl8wzwyg 1 0    0 0    249b    249b    249b
green open .ds-logs-generic-default-2023.06.14-000001                         vRdMOCBPRSO1PPgJosUMtA 1 0 1480 0     1mb     1mb     1mb
green open .ds-logs-generic-default-2023.12.26-000007                         vQbBXf4tSHKqWihRwmLSWw 1 0   85 0 181.8kb 181.8kb 181.8kb
green open .internal.alerts-stack.alerts-default-000001                       bDFTw5zFR5S1sKeXOdWHVQ 1 0    0 0    249b    249b    249b
```
data sizes look right..

but I can't find these in discover. logs-* is the default view , nothing.. trying to create a view with ds-*, .ds-*. all turn up nothing..

i started over, deleted the implementation and set number of replicas to 0. same results..

I am NOT an es expert by any means.. the tools docs says 'easy'.. but I am lost.. nothing matches up.. correct number of records written..  they look present.. just don't know where they are..

**Comment by sdetweil** [comment]
I have a test script in javascript that searches the index ' index: 'logs-generic-default' 

and it correctly gets the data, but I cannot access that in kibana

**Comment by ferronrsmith** [comment]
Are you sure the data is in the dump file ? the only problem I can see is a restriction on elasticsearch for creating certain prefixed indices

**Comment by ferronrsmith** [comment]
Have you tried * wildcard, to see if everything shows up ?

**Comment by sdetweil** [comment]
I tried *, and .* neither worked..

in the Kibana search, indices I see 

![Screenshot at 2024-04-10 20-33-48](https://github.com/elasticsearch-dump/elasticsearch-dump/assets/1498142/1585c9ea-de18-418e-a0cc-9e365518d4a3)

looking thru the data its what was dumped on the source side. 

a second worry is that my apps injecting data thru logstash and direct post will not end up in these same indices.. so later search later will not include them in results..

**Comment by sdetweil** [comment]
and drilling in to one of those indices it says

![Screenshot at 2024-04-10 21-32-26](https://github.com/elasticsearch-dump/elasticsearch-dump/assets/1498142/c727bdcd-3cb5-4e06-9787-a1d38567aad9)

**Comment by sdetweil** [comment]
does externally managed mean something

**Comment by ferronrsmith** [comment]
But you can query the index, the only issue seems to be that the index isn't being displayed in kibana

**Comment by sdetweil** [comment]
>Can you show the index settings/mapping for both a managed/unmanaged index.

I don't know what that means.. I am running as installed.

**Comment by ferronrsmith** [comment]
curl http://host/index_name/_settings
curl http://host/index_name/_mappings

**Comment by sdetweil** [comment]
no, this is local on one machine under docker. 

response to the two quesries on one index

[s.txt](https://github.com/elasticsearch-dump/elasticsearch-dump/files/14946629/s.txt)
[m.txt](https://github.com/elasticsearch-dump/elasticsearch-dump/files/14946630/m.txt)

**Comment by sdetweil** [comment]
by editing my input and setting a specific index name, creating it before I can get to my data.

so my assumption is this is because I was using the default indexes..  I am updating my apps to use the new index

**Comment by sdetweil** [comment]
hm.. now I get unmapped fields.. for all the data..

**Comment by sdetweil** [comment]
the search view on kibana shows my index (created before the import), and shows the field mappings..

which look good.. but discover doesn't see the mappings..

**Comment by sdetweil** [comment]
my data coming in thru logstash is going to the correct index, and the fields are mapped..  how do I fix the old data coming in thru elasticsearch-dump?

**Comment by sdetweil** [comment]
well , I am at a loss.. 
I restarted, sent in some data from my apps, (commandline curl post, and Apple app, http POST.. both come in thru logstash and are parsed and presented cpoorrectly. 
I created an alias over the logs-general-default  and my search functions work using the alias..

now to restore my old data, exported via elasticsearch_dump.
i don't want all the data in that record, so I wrote a short JS app to read the file in, line by line get the json, remove the kes added by the original elasticsearch ingest. 
and then http post it to the logstash entrypoint, like the others do.. and it comes in, BUT my content is NOT parsed, just added as the original_event data.  i dont understand what is wrong here. 

in our design ALL data IN comes thru logstash. only direct attachment to elasticsearch is search in two areas, based on the logtype of the existing records 

logstash cannot output to the alias.

**Comment by sdetweil** [comment]
my logstash pipeline is pretty simple
```text
input {
        beats {
                port => 5044
        }

        tcp {
                port => 50000
        }
        http {
            host => "0.0.0.0"
            port => "3000"
          }
}

## Add your filters / logstash plugins configuration here

filter {
        if [http][method] != "POST" {
                 drop {}
         }
}

output {
        elasticsearch {
                hosts => "elasticsearch:9200"
                user => "logstash_internal"
                password => "${LOGSTASH_INTERNAL_PASSWORD}"
#               index => "cndata"
        }
}
```
