### ISSUE TITLE
Dump new documents of an index partially dumped to other elastic cluster

### ISSUE THREAD

**Issue by ayeshasiddiqs** [elasticsearch-dump/elasticsearch-dump#1041]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version 6.8
- Elasticsearch version 6.8
- Node.js version *(note that nodejs v10+ is required for this tool)* 18.20.2
- Full command you are having issue with (with inputs and outputs) ["elasticdump", es_input_url, es_output_url, access_key, secret_key, "--retryAttempts=3", "--retryDelay=3", "--limit=5000", "--scrollTime=10m", "--type=data"]
- A data-set you can share publicly which reproduces the problem NA or any small document count

**Describe the bug**
Dumping from one elastic cluster to another for 3 documents is successfully done, now after 5mins or so, I get new documents in source elastic cluster, I want to dump only the remaining documents newly added in source. How can I do it?

**To Reproduce**
I tried scrollId, where I'm passing the scrollId in next run to dump remaining docs, I don't get the newly added docs with this scrollId. Probably because in that scroll time ES didnt get the new docs.

**Current behavior**
Unable to correctly dump **ONLY** remaining docs

**Expected behavior**
I want to dump remaining docs, and not start all over again.

**Comment by ferronrsmith** [comment]
You can use the "searchBody" to filter out the remaining document. It's accepts an elastic search query/filter

**Comment by ayeshasiddiqs** [comment]
Ok, how can I pass the "from" attribute in this? for example: 
```
{"from":2,"size":100,"query":{"match_all":{}}}
```

**Comment by ferronrsmith** [comment]
```bash

elasticdump \
  --input= es_input_url \
  --output= es_output_url \
  --searchBody="{\"from\":2,\"size\":100,\"query\":{\"match_all\":{}}}"

```
