### ISSUE TITLE
[BUG] Empty alias export breaks import

### ISSUE THREAD

**Issue by gquintana** [elasticsearch-dump/elasticsearch-dump#1042]
**Context**

- ElasticDump 6.111
- Elasticsearch 7.13 / Opensearch 1.3
- Node.js version 20.14 from Docker image

**Describe the bug**
When exporting aliases on an index having no aliases, the resulting file can not be imported.
The file content `"{}"` is not valid.

**To Reproduce**
1. Export aliases from Elasticsearch to file 
2. The alias file contains `"{}"` because there is no alias on this particular index
3. Import the alias file to another Elasticsearch fails with error:
```
Mon, 29 Jul 2024 19:04:56 GMT | Error Emitted => 
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "No action specified"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "No action specified"
    },
    "status": 400
}
```

**Current behavior**
See above error

**Expected behavior**

* Either the exported file is empty
* Or, the content `"{}"` is considered as empty
In both case, the file is considered as legal, doesn't raise any error, doesn't create any alias.

**Comment by ferronrsmith** [comment]
Can you provide a sample exported file ? thanks

**Comment by ferronrsmith** [comment]
Technically it's not incorrect. No aliases were found so no actions can be created. Ideally this can be handled with a `'no aliases detected'` error message, but it's still the same thing.

**Comment by gquintana** [comment]
Too bad the behaviour is not align with datatype data: When there is no data, file is empty and it doesn't break reimport.
