### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by sameeroak1110** [elasticsearch-dump/elasticsearch-dump#1043]
Add exaxmples related to scrollId and scrollTime in README:
I've a use case where I've to slice the source elastic data in batches of 1000 documents each batch.
Say for instance, I've 100,000 documents in an index. I'll need to created 100 json files.
With the latest ElasticSearch and elasticdump tool, offset is gone.
--from option of elasticdump is of no use as it silently ignores that option.
scrollId and scrollTime are at help. We can use scrollTime.
However, there's no clue how to use scrollId when we need to take a dump in terms of batches.
I've been searching for how to use these 2 options. No success so far.
Can you please provide a few good appropriate examples on these 2 options?

**Comment by ferronrsmith** [comment]
technically you can run in serverless mode. `--openSearchServerless`, this shoudl revert back to using the `--from`
