### ISSUE TITLE
elasticdump error

### ISSUE THREAD

**Issue by fuming898** [elasticsearch-dump/elasticsearch-dump#1044]
when i dump es data, an error has occurred, 
my command:
elasticdump --input http://open-sh.jdcloud.com:9200/distribution_2311_v1 --output distribution_2311_v1-data.json --type=data --limit 10000

this is log:
Thu, 08 Aug 2024 13:29:44 GMT | got 10000 objects from source elasticsearch (offset: 338680000)
Thu, 08 Aug 2024 13:29:44 GMT | sent 10000 objects to destination file, wrote 10000
Thu, 08 Aug 2024 13:29:50 GMT | got 10000 objects from source elasticsearch (offset: 338690000)
Thu, 08 Aug 2024 13:29:50 GMT | sent 10000 objects to destination file, wrote 10000
Thu, 08 Aug 2024 13:29:50 GMT | got 10000 objects from source elasticsearch (offset: 338700000)
Thu, 08 Aug 2024 13:29:50 GMT | sent 10000 objects to destination file, wrote 10000
Thu, 08 Aug 2024 13:30:10 GMT | Error Emitted => {"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [3987665894/3.7gb], which is larger than the limit of [3978238361/3.7gb], real usage: [3987664048/3.7gb], new bytes reserved: [1846/1.8kb], usages [request=0/0b, fielddata=0/0b, in_flight_requests=1846/1.8kb, accounting=0/0b]","bytes_wanted":3987665894,"bytes_limit":3978238361,"durability":"TRANSIENT"}],"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [3987665894/3.7gb], which is larger than the limit of [3978238361/3.7gb], real usage: [3987664048/3.7gb], new bytes reserved: [1846/1.8kb], usages [request=0/0b, fielddata=0/0b, in_flight_requests=1846/1.8kb, accounting=0/0b]","bytes_wanted":3987665894,"bytes_limit":3978238361,"durability":"TRANSIENT"},"status":429}
Thu, 08 Aug 2024 13:30:10 GMT | Error Emitted => {"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [3987665894/3.7gb], which is larger than the limit of [3978238361/3.7gb], real usage: [3987664048/3.7gb], new bytes reserved: [1846/1.8kb], usages [request=0/0b, fielddata=0/0b, in_flight_requests=1846/1.8kb, accounting=0/0b]","bytes_wanted":3987665894,"bytes_limit":3978238361,"durability":"TRANSIENT"}],"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [3987665894/3.7gb], which is larger than the limit of [3978238361/3.7gb], real usage: [3987664048/3.7gb], new bytes reserved: [1846/1.8kb], usages [request=0/0b, fielddata=0/0b, in_flight_requests=1846/1.8kb, accounting=0/0b]","bytes_wanted":3987665894,"bytes_limit":3978238361,"durability":"TRANSIENT"},"status":429}
Thu, 08 Aug 2024 13:30:10 GMT | Total Writes: 0
Thu, 08 Aug 2024 13:30:10 GMT | dump ended with error (get phase) => TOO_MANY_REQUESTS: {"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [3987665894/3.7gb], which is larger than the limit of [3978238361/3.7gb], real usage: [3987664048/3.7gb], new bytes reserved: [1846/1.8kb], usages [request=0/0b, fielddata=0/0b, in_flight_requests=1846/1.8kb, accounting=0/0b]","bytes_wanted":3987665894,"bytes_limit":3978238361,"durability":"TRANSIENT"}],"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [3987665894/3.7gb], which is larger than the limit of [3978238361/3.7gb], real usage: [3987664048/3.7gb], new bytes reserved: [1846/1.8kb], usages [request=0/0b, fielddata=0/0b, in_flight_requests=1846/1.8kb, accounting=0/0b]","bytes_wanted":3987665894,"bytes_limit":3978238361,"durability":"TRANSIENT"},"status":429}

i dont know why,thanks

**Comment by ferronrsmith** [comment]
You don't have enough memory in elasticsearch to handle the volume of data and request. This is an elasticsearch error hand has nothing to do with elasticdump

**Comment by fuming898** [comment]
thank you
