### ISSUE TITLE
[FEATURE] Allow to specify same options multiple times with later overriding former

### ISSUE THREAD

**Issue by pallxk** [elasticsearch-dump/elasticsearch-dump#1055]
**Is your feature request related to a problem? Please describe.**
elasticdump comes with `100` as the default to the `--limit` option, and I'd like it to be `1000` by default for me, so I add an alias in bash:

```sh
alias elasticdump="elasticdump --limit=1000"
```

It works flawlessly when I don't specify `--limit` option again, otherwise, it exits with some weird errors:

```
Sun, 15 Sep 2024 00:10:55 GMT | starting dump
Sun, 15 Sep 2024 00:10:55 GMT | Error Emitted => {"error":{"root_cause":[{"type":"parsing_exception","reason":"Unknown key for a START_ARRAY in [size].","line":1,"col":71}],"type":"parsing_exception","reason":"Unknown key for a START_ARRAY in [size].","line":1,"col":71},"status":400}
Sun, 15 Sep 2024 00:10:55 GMT | Error Emitted => {"error":{"root_cause":[{"type":"parsing_exception","reason":"Unknown key for a START_ARRAY in [size].","line":1,"col":71}],"type":"parsing_exception","reason":"Unknown key for a START_ARRAY in [size].","line":1,"col":71},"status":400}
Sun, 15 Sep 2024 00:10:55 GMT | Total Writes: 0
Sun, 15 Sep 2024 00:10:55 GMT | dump ended with error (get phase) => BAD_REQUEST: {"error":{"root_cause":[{"type":"parsing_exception","reason":"Unknown key for a START_ARRAY in [size].","line":1,"col":71}],"type":"parsing_exception","reason":"Unknown key for a START_ARRAY in [size].","line":1,"col":71},"status":400}
```

**Describe the solution you'd like**
I'd like elasticdump to accept same options multiple times, with later ones overriding former ones. So that
* `elasticdump --limit 1000 --limit 100` is equivalent to `elasticdump --limit 100`
* similarly, `elasticdump --output=dump.json --output=http://es:9200/my_index` is equivalent to `elasticdump --output=http://es:9200/my_index`

**Describe alternatives you've considered**
For my particular issue and alias setup, I can achieve the same with:

```sh
alias elasticdump="elasticdump --limit=1000"

# Using alias
elasticdump ...

# Not using alias
\elasticdump ...
```

**Give some examples of implementations**
If this is what we want, we can do this in `parse()` in `argv.js`; alternatively, we may consider using another arg parser other than `minimist`.

**Comment by ferronrsmith** [comment]
Specify limit twice turns into an array, that's the default behavior for `minimist`, which we won't change
