### ISSUE TITLE
[BUG] --offset when --input is a large (gz) file takes a long time to seek

### ISSUE THREAD

**Issue by dhmw** [elasticsearch-dump/elasticsearch-dump#1060]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 6.113.0
- Elasticsearch version: N/A
- Node.js version: 20.15.0
- Full command you are having issue with (with inputs and outputs)

```
elasticdump
  --output=https://[REDACTED]/[REDACTED] 
  --input=./very_large_file.ndjson.gz 
  --type=data 
  --fsCompress=true
  --limit=100
  --offset=45600
  --awsChain
```

**Describe the bug**

I'm using the above command to bulk insert in to an AWS Opensearch instance. This requires the command to be run using temporary AWS assumed role credentials because of our Opensearch security setup.

The max session time for any assumed role on AWS is 1hr, so the bulk import fails after each hour of runtime.

```
Tue, 15 Oct 2024 14:22:26 GMT | sent 100 objects to destination elasticsearch, wrote 100
Tue, 15 Oct 2024 14:22:31 GMT | got 100 objects from source file (offset: 45700)
Tue, 15 Oct 2024 14:22:37 GMT | Error Emitted => {"message":"The security token included in the request is expired"}
Tue, 15 Oct 2024 14:22:37 GMT | Error Emitted => {"message":"The security token included in the request is expired"}
```

So, I have to resume using an offset. However, the offset itself takes ages to seek/scan through the file input, and for each iteration of actually running the bulk import, less and less time is actually used for sending data to Opensearch before the authenticated session times out.

My gz file is about 28GB, the data set contains about 100k very large documents.
Seeking to ~45k offset takes about 40 mins.

```
Tue, 15 Oct 2024 14:23:02 GMT | starting dump
Tue, 15 Oct 2024 14:23:02 GMT | Warning: offsetting 45600 rows.
Tue, 15 Oct 2024 14:23:02 GMT |   * Using an offset doesn't guarantee that the offset rows have already been written, please refer to the HELP text.
Tue, 15 Oct 2024 15:03:01 GMT | got 100 objects from source file (offset: 45600)
Tue, 15 Oct 2024 15:03:24 GMT | sent 100 objects to destination elasticsearch, wrote 100
Tue, 15 Oct 2024 15:03:30 GMT | got 100 objects from source file (offset: 45700)
...
```

**To Reproduce**

Try to import from a very large gz file source with an offset.

**Current behavior**

This will get to the point where the seek takes longer than the available session duration, and I won't be able to import the entire file without splitting it first. Splitting presents a challenge because of the limited storage capacity available on the machine where this runs.

**Expected behavior**

A quick seek through the input file and resuming bulk update operations.

**Comment by ferronrsmith** [comment]
Honestly there isn't anything I can do about this. This is purely a nodejs/stream problem.

**Comment by dhmw** [comment]
Thanks for the reply, I thought as much. In the end I did split the files.
