### ISSUE TITLE
[BUG] unexpected json returned when using opensearch serverless as output

### ISSUE THREAD

**Issue by majkiee** [elasticsearch-dump/elasticsearch-dump#1068]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version
6.114.0

- Elasticsearch version
Aws opensearch serverless
- Node.js version *(note that nodejs v10+ is required for this tool)*
v20.11.0

- Full command you are having issue with (with inputs and outputs)
```elasticdump --debug=true --input=./data/my_index_mapping.json --output=https://****.eu-west-1.aoss.amazonaws.com:443/dev-winback-offers --type=mapping --awsRegion=eu-west-1 --openSearchServerless --awsAccessKeyId=AK*** --awsSecretAccessKey=***```

- A data-set you can share publicly which reproduces the problem
Issue is related to elastic communication, not the input data. 

**Describe the bug**
Trying to use elasticdump to move data from a existing opensearch cluster into a opensearch serverless cluster but it seems like the response from the output server is not parsed correctly. I get the following:
```
Thu, 28 Nov 2024 11:14:22 GMT | starting dump
(node:22406) NOTE: The AWS SDK for JavaScript (v2) is in maintenance mode.
 SDK releases are limited to address critical bug fixes and security issues only.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the blog post at https://a.co/cUPnyil
(Use `node --trace-warnings ...` to show where the warning was created)
Thu, 28 Nov 2024 11:14:22 GMT | got 1 objects from source file (offset: 0)
Thu, 28 Nov 2024 11:14:22 GMT [debug] | opensearch serverless does not support version check, assuming major version: null
/Users/micke/.config/yarn/global/node_modules/elasticdump/lib/jsonparser.js:48
    throw new Error(`failed to parse json (message: "${e.message}") - source: ${JSON.stringify(str)}`)
          ^

Error: failed to parse json (message: "Unexpected end of JSON input") - source: ""
    at Object.parse (/Users/micke/.config/yarn/global/node_modules/elasticdump/lib/jsonparser.js:48:11)
    at Request.<anonymous> (/Users/micke/.config/yarn/global/node_modules/elasticdump/lib/transports/__es__/_mapping.js:108:50)
    at Request._callback (/Users/micke/.config/yarn/global/node_modules/lodash/lodash.js:10118:25)
    at Request.requestRetryReply [as reply] (/Users/micke/.config/yarn/global/node_modules/requestretry/index.js:151:19)
    at Request.<anonymous> (/Users/micke/.config/yarn/global/node_modules/requestretry/index.js:192:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

it seems like we get nothing back from the source and it's not showing any future details. It also fails to set the assumed major version.

**To Reproduce**
1. Upload any dumped mapping file to a opensearch serverless instance.
2. Error output above

**Current behavior**
See above

**Expected behavior**
I would think that the response is either not expected or some kind of error. Would be good to get some more details when running regarding status codes and other error responses since the only thing I can see is that the source input string is empty and it's expecting json.

**Additional context**
In this current version im using a key and secret but I initally tried to use my credentials file and ran into the same issue. 
I switched to a key just to verify that the profile loading / picking wasnt the issue.

**Comment by ferronrsmith** [comment]
seems the response body returned wasn't json, so there was a failure when parsing the error. without more information i can't do much.
