### ISSUE TITLE
[FEATURE] support a callback function in multielasticdump to determine if an index has to be backed up

### ISSUE THREAD

**Issue by jahlives** [elasticsearch-dump/elasticsearch-dump#1069]
**Is your feature request related to a problem? Please describe.**
if running `multielasticdump` it is currently impossible to tell the code that an index matching `match` pattern should **not** be backed up. We have dated indices per day (ex mylog-2024-12-03)  and I only want to backup ALL of `match` once. After that first run only indices younger than x days should be backed up again.

**Describe the solution you'd like**
it would be great if `multielasticdump` could callback a (shell)script per index matching `match` pattern and this code could return `1` for to be backed up and `0` for skip this particular index. It should pass the index name to the script. For dated indices that would be quite easy for the script as it could check if the dated index json already exists in backup destination (`--output`)

**Describe alternatives you've considered**
I do not see any alternative as `multielasticdump` seems not to support a `exclude` pattern

**Give some examples of implementations**
I would use a bash function like this
```bash
need_backup() {
 # pass index name as myindex-2024-12-03
  # backup if target file does not exists
  if [ ! -f /data/docker/backup/$1.json ] ; then 
    return 1
  else
    # do not backup if target file exists and index age is more than 5 days
    [ $(( $(date '+%s') - $(date '+%s' -d $(echo "$1" | awk -F'-' '{print $2"-"$3"-"$4}')) )) -gt $(( 5 * 86400 )) ] && return 0
    return 1
  fi
  return 1
}
```

Thanks a lot for considering this feature request.

Kind regards

tobi

**Comment by ferronrsmith** [comment]
made a pr for this. not exactly what you wanted, but this implementation gives more flexibility and is inline with the current methodology used in elasticdump. Test and let me know if this works for you. I converted your example above to js since calling bash from nodejs is a perform hit.

https://github.com/elasticsearch-dump/elasticsearch-dump/blob/feature/custom-matcher/customMatcher/backup.js
