### ISSUE TITLE
Question: How do I prevent extra double quoting of JSON string when writing to csv file?

### ISSUE THREAD

**Issue by eeijlar** [elasticsearch-dump/elasticsearch-dump#1071]
I am using a transform to extract fields from the elastic document, and write them all as a single JSON string into a csv file. `static_fields` is just a list of fields in the document that I want to do this operation on. It is populated from the contents of a file.

```
function createStaticFields(doc) {
    const extractedFields = {};
    static_fields.forEach(field => {
        if (doc._source[field]) {
            extractedFields[field] = doc._source[field];
            delete doc._source[field];
        }
    });

    doc._source.staticfields = JSON.stringify(extractedFields);
    doc.fields.staticfields = JSON.stringify(extractedFields);

return doc;
}
```

Which works just fine, if I print out the json fields with console.log, they look like this:
`
{"one":"0","two":"2400","three":"0","four":"0","five":"2400","six":"nrphone","seven":"12","eight":10,"nine":"2400","ten":"5196854","eleven":"35107200","twelve":"31410","thirteen":"0","fourteen":"101","fifteen":1,"sixteen":"U","seventeen":"SUCCESS","eighteen":"1","nineteen":"stuff","twenty":"3510715267218500","twentyone":"dfs"}
`

However, when the resulting string is written to csv, it looks like this:
`{""one":""0"",""two"":""2400"",""three"":""0"",""four"":""0"",""five"":""2400"",""six"":""nrphone"",""seven"":""12"",""eight"":""10"",""nine"":""2400"",""ten"":""5196854"",""eleven"":""35107200"",""twelve"":""31410"",""thirteen"":""0"",""fourteen"":""101"",""fifteen"":""1"",""sixteen"":""U"",""seventeen"":""SUCCESS"",""eighteen"":""1"",""nineteen"":""stuff"",""twenty"":""3510715267218500"",""twentyone"":""dfs""}`

It adds another set of double quotes around each field. I have tried many variations of `JSON.stringify` but it makes no difference, I think it's happening at the CSV writing stage. 

Is there any way around this?

**Comment by ferronrsmith** [comment]
> A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What was the url? What steps will reproduce the issue? What OS experience the problem? All these details will help to fix any potential bugs as soon as possible.

I still don't know what command you are running to aid you in this. can you share that information ? 

**Also stringifying the staticfields before passing it to the output will lead to double stringify**

**Comment by ferronrsmith** [comment]
you're looking at it as a stringified json. it's fine, the csv key/values are quoted. using csvQuoteChar https://c2fo.github.io/fast-csv/docs/parsing/options/#quote

**Comment by eeijlar** [comment]
> > A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What was the url? What steps will reproduce the issue? What OS experience the problem? All these details will help to fix any potential bugs as soon as possible.
> 
> I still don't know what command you are running to aid you in this. can you share that information ?
> 
> **Also stringifying the staticfields before passing it to the output will lead to double stringify**

I have updated the report to include more details. If I don't stringify it, it comes out as an object in the csv file.

**Comment by ferronrsmith** [comment]
Answered the question above. Essentially the behavior of the CSV library is to quote everything. This is due to things like

1. spaces in keys (might be interpreted incorrectly by csv editor ... excel)
2. spaces in values (same as above or might contain restricted characters etc.

There is nothing wrong with the outputted csv. should open in excel or your favorite csv editor.

**Comment by eeijlar** [comment]
> you're looking at it as a stringified json. it's fine, the csv key/values are quoted. using csvQuoteChar https://c2fo.github.io/fast-csv/docs/parsing/options/#quote

I have tried not quoting it:

```
function createStaticFields(doc) {
    const extractedFields = {};
    static_fields.forEach(field => {
        if (doc._source[field]) {
            extractedFields[field] = doc._source[field];
            delete doc._source[field];
        }
    });

    Object.defineProperty(extractedFields, 'toNonQuotedString', {
      value: function() {
        return `{ ${Object.entries(this)
          .map(([key, value]) => `${key}: ${value}`)
          .join(", ")} }`;
      },
      enumerable: false
    });


    doc._source.staticfields = extractedFields.toNonQuotedString();
    doc.fields.staticfields = extractedFields.toNonQuotedString();

return doc;
};
```

but then it comes out as unquoted json...

```
{one:0,two:2400,three:0,four:0,five:2400,six:nrphone,seven:12,eight:10,nine:2400,ten:5196854,eleven:35107200,twelve:31410,thirteen:0,fourteen:101,fifteen:1,sixteen:U,seventeen:SUCCESS,eighteen:1,nineteen:stuff,twenty:3510715267218500,twentyone:dfs}
```

**Comment by eeijlar** [comment]
> Answered the question above. Essentially the behavior of the CSV library is to quote everything. This is due to things like
> 
>     1. spaces in keys (might be interpreted incorrectly by csv editor ... excel)
> 
>     2. spaces in values (same as above or might contain restricted characters etc.
> 
> 
> There is nothing wrong with the outputted csv. should open in excel or your favorite csv editor.

Unfortunately, the output csv is being parsed by another tool to load it into another database (cassandra) and it expects valid json for that field.

**Comment by ferronrsmith** [comment]
Have you tried setting the `--csvQuoteChar=null` ?
