### ISSUE TITLE
Ordering types for parent child

### ISSUE THREAD

**Issue by AlexNodex** [elasticsearch-dump/elasticsearch-dump#410]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version - Latest (April 2018)
- Elasticsearch version - 1.7.6, 2.4.6, 5x, 6x
- Node.js version - latest stable (April 2018)

When dumping there needs to be an option for parent child routing so to be able to sort the documents dumped on some sort of order.

An example of this is where we have a parent child relationship which creates a routing context on the child document and thus the parent needs to be inserted first.

Without this and with parent/child documents inserts will fail when dumping

**Comment by ferronrsmith** [comment]
Can't you use the **searchBody** to filter outer parent from child then dump separately ?
