### ISSUE TITLE
Exporting an index then importing as a different index name

### ISSUE THREAD

**Issue by geekpete** [elasticsearch-dump/elasticsearch-dump#53]
I'm probably missing something here but I had to do a search/replace in my exported json file to adjust the index name to then import into a different index name.

Was there a parameter or method that would allow elasticdump to do this for me?

Cheers.

**Comment by jogaco** [comment]
I tried the same and it did not work until I did a full replace of the index name in the dumped json file.

**Comment by jchannon** [comment]
Bit late to the party here but I'd like to do the same. Is it possible now?
