### ISSUE TITLE
Import templates into ES isn't working

### ISSUE THREAD

**Issue by moriyahazan** [elasticsearch-dump/elasticsearch-dump#694]
- ElasticDump version : 6.28.0
- Elasticsearch version: 6.1.1
- Node.js version: 12.16.3

I backup template by following command: 
elasticdump --input=http://USER_NAME:PASS@HOST_NAME:9200/TEMPLATE_NAME --output=templates.json --type=template

The backup work properly and file templates.json was created with the TEMPLATE_NAME template, than I tried to import templates into ES (other server) by command:
elasticdump   --input=./templates.json  --output=http://USER_NAME:PASS@HOST_NAME:9200   --type=template

the import is not working and this is the log I got: 

Sun, 10 May 2020 12:34:20 GMT | starting dump
Sun, 10 May 2020 12:34:20 GMT | got 1 objects from source file (offset: 0)
Sun, 10 May 2020 12:34:20 GMT [debug] | discovered elasticsearch output major version: 6
Sun, 10 May 2020 12:34:21 GMT | sent 1 objects to destination elasticsearch, wrote 0
Sun, 10 May 2020 12:34:21 GMT | got 0 objects from source file (offset: 1)
Sun, 10 May 2020 12:34:21 GMT | Total Writes: 0
Sun, 10 May 2020 12:34:21 GMT | dump complet

Can you please help me? thanks

**Comment by ferronrsmith** [comment]
You can't import templates across major versions. Also this issue doesn't provide any information on replication or sample data.

**Comment by MilanDasek** [comment]
I have the same problem

I backed up template from AWS ES, but I cannot import into ES back - no change in the template.

**Comment by ferronrsmith** [comment]
If the versions of elasticsearch are different then it will fail. This is already stated in the docs

**Comment by ferronrsmith** [comment]
You can't import templates across major versions. Also this issue doesn't provide any information on replication or sample data.

You can’t import es2 templates into es6 or es7. This is due to the fact the ES introduced breaking changes across major versions (stayed in the docs)

**Comment by moriyahazan** [comment]
I tried in same ES version. from ES 6.1.1 to 6.1.1

**Comment by ferronrsmith** [comment]
Provide test data, and steps used import data

**Comment by moriyahazan** [comment]
You can run the 2 steps from the tutorial one after the other. it will not work.
thank for your help.

# Backup templates to a file
elasticdump \
  --input=http://es.com:9200/template-filter \
  --output=templates.json \
  --type=template

# Import templates into ES
elasticdump \
  --input=./templates.json \
  --output=http://es.com:9200 \
  --type=template

**Comment by ferronrsmith** [comment]
So I tested, even with your steps and it was successful. There are 2 problems here

1. The template endpoint doesn't return a count status (which can be added)
2. You didn't perform tests to verify that the template was written to ES

**Comment by moriyahazan** [comment]
you are right. the template was written. the log confused me see below - > **Total Writes: 0**
thank you again.

Wed, 13 May 2020 14:18:19 GMT | starting dump
Wed, 13 May 2020 14:18:19 GMT | got 1 objects from source file (offset: 0)
Wed, 13 May 2020 14:18:19 GMT | sent 1 objects to destination elasticsearch, wrote 0
Wed, 13 May 2020 14:18:19 GMT | got 0 objects from source file (offset: 1)
Wed, 13 May 2020 14:18:19 GMT | Total Writes: 0
Wed, 13 May 2020 14:18:19 GMT | dump complete

**Comment by ferronrsmith** [comment]
It'll be fixed in the next version, thanks for reporting
