### ISSUE TITLE
rror Emitted => {"error":"Content-Type header [] is not supported","status":406}

### ISSUE THREAD

**Issue by ghl1024** [elasticsearch-dump/elasticsearch-dump#697]
#### ES version：7.2.0
```
[root@aliyun ~]$ elasticdump --input=http://test:test@x.x.x.x:9200/some_index_01 --output=/root/query.json --headers='{"Content-Type": "application/json"}'
Tue, 19 May 2020 12:23:39 GMT | starting dump
Tue, 19 May 2020 12:23:39 GMT | Error Emitted => {"error":"Content-Type header [] is not supported","status":406}
Tue, 19 May 2020 12:23:39 GMT | Total Writes: 0
Tue, 19 May 2020 12:23:39 GMT | dump ended with error (get phase) => Error: {"error":"Content-Type header [] is not supported","status":406}
[root@aliyun ~]$ 
```

**Comment by ferronrsmith** [comment]
The header isn't properly escaped. 

```
--input=http://test:test@x.x.x.x:9200/some_index_01 --output=/root/query.json --headers="{\"Content-Type\":\"application/json\"}"
```

Also `Content-Type` is a default header, so passing it is redundant

**Comment by Dravening** [comment]
[root@local-retail-worker-1 data]# elasticdump --direction=dump --input=http://elasticsearch-app.uat.svc.retailcluster.local:9200 --output=es-app-dump --headers="{\"Content-Type\":\"application/json\"}"
Tue, 17 May 2022 06:49:34 GMT | starting dump
Tue, 17 May 2022 06:49:34 GMT | Error Emitted => {"error":"Content-Type header [] is not supported","status":406}
Tue, 17 May 2022 06:49:34 GMT | Total Writes: 0
Tue, 17 May 2022 06:49:34 GMT | dump ended with error (get phase) => Error: {"error":"Content-Type header [] is not supported","status":406}

...emmm
