### ISSUE TITLE
一个小小的问题

### ISSUE THREAD

**Issue by Gwenpi** [elasticsearch-dump/elasticsearch-dump#699]
elasticdump version: 6.23.0
elasticsearch version: 6.3.2
一下是我的一个备份过程：

```
[root@localhost ~]# curl http://192.168.5.250:9200/_cat/indices?v
health status index                         uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   security_changle_data_test    A3dFYvsdQdSwtj9za_tmQw   5   1     176056            0     13.4mb         13.4mb
yellow open   nettest_new                   iryXM2_nQlWVdoQaatGo6Q   5   1      84644            0     14.4mb         14.4mb
yellow open   security_changle_data         Qo1pYkbnTK-QpwjLas9Etw   5   1      47824            0      3.6mb          3.6mb
yellow open   collect_network_flow_data_new ktBtOyT0RESU7Ye9LFXgDA   5   1     428712            0    119.7mb        119.7mb

```

```bash
[root@localhost ~]# elasticdump --input=http://192.168.5.250:9200/security_changle_data --output=/home/workspace/shell/collect_10.json --searchBogy {"quefsadfry": {"ranfasdfge": {"timestamfdasfasdfp": {"gte": "2020-02-12 1fsdafdas2:46:01","lte": "2020-02-13fdsaf 12:46:01"}}}} --limit=10000
```

```
Thu, 21 May 2020 02:37:12 GMT | starting dump
Thu, 21 May 2020 02:37:13 GMT | got 10000 objects from source elasticsearch (offset: 0)
Thu, 21 May 2020 02:37:13 GMT | sent 10000 objects to destination file, wrote 10000
Thu, 21 May 2020 02:37:13 GMT | got 10000 objects from source elasticsearch (offset: 10000)
Thu, 21 May 2020 02:37:13 GMT | sent 10000 objects to destination file, wrote 10000
Thu, 21 May 2020 02:37:13 GMT | got 10000 objects from source elasticsearch (offset: 20000)
Thu, 21 May 2020 02:37:14 GMT | sent 10000 objects to destination file, wrote 10000
Thu, 21 May 2020 02:37:14 GMT | got 10000 objects from source elasticsearch (offset: 30000)
Thu, 21 May 2020 02:37:14 GMT | sent 10000 objects to destination file, wrote 10000
Thu, 21 May 2020 02:37:14 GMT | got 7824 objects from source elasticsearch (offset: 40000)
Thu, 21 May 2020 02:37:14 GMT | sent 7824 objects to destination file, wrote 7824
Thu, 21 May 2020 02:37:14 GMT | got 0 objects from source elasticsearch (offset: 47824)
Thu, 21 May 2020 02:37:14 GMT | Total Writes: 47824
Thu, 21 May 2020 02:37:14 GMT | dump complete
```

我的问题是：为什么”--searchBogy“的查询语句是错误的，elasticdump仍然完整的备份整个索引？
是我的elasticsearch设置的有问题吗？我对elasticsearch不是很懂...

**Comment by ferronrsmith** [comment]
should be `--searchBody`. If present unless the scope selected is the entire index, it should only dump a partial

**Comment by Gwenpi** [comment]
我现在要根据 数据收集的时间 备份索引，如果 “--searchBody” 查询语句错误的结果是备份完整的索引，这显然是不行的。如果是解析或者转义问题不应会报错吗？为什么会继续备份下去呢？比如：
[root@localhost ~]# elasticdump --input=http://192.168.5.250:9200/security_changle_data --output=/home/workspace/shell/collect_18.json --searchBogy {"fasdf":"dsaf"} --limit=10000
Thu, 21 May 2020 08:28:38 GMT | starting dump
Thu, 21 May 2020 08:28:38 GMT | got 10000 objects from source elasticsearch (offset: 0)
Thu, 21 May 2020 08:28:38 GMT | sent 10000 objects to destination file, wrote 10000
Thu, 21 May 2020 08:28:38 GMT | got 10000 objects from source elasticsearch (offset: 10000)
Thu, 21 May 2020 08:28:39 GMT | sent 10000 objects to destination file, wrote 10000
Thu, 21 May 2020 08:28:39 GMT | got 10000 objects from source elasticsearch (offset: 20000)
Thu, 21 May 2020 08:28:39 GMT | sent 10000 objects to destination file, wrote 10000
Thu, 21 May 2020 08:28:39 GMT | got 10000 objects from source elasticsearch (offset: 30000)
Thu, 21 May 2020 08:28:39 GMT | sent 10000 objects to destination file, wrote 10000
Thu, 21 May 2020 08:28:39 GMT | got 7824 objects from source elasticsearch (offset: 40000)
Thu, 21 May 2020 08:28:39 GMT | sent 7824 objects to destination file, wrote 7824
Thu, 21 May 2020 08:28:39 GMT | got 0 objects from source elasticsearch (offset: 47824)
Thu, 21 May 2020 08:28:39 GMT | Total Writes: 47824
Thu, 21 May 2020 08:28:39 GMT | dump complete

有人来帮帮我吗...

**Comment by ferronrsmith** [comment]
The command being passed is incorrect. At least what’s posted is incorrect

**Comment by Gwenpi** [comment]
> The command being passed is incorrect. At least what’s posted is incorrect.
> 
> Not sure if it’s a translation issue, but the command above is incorrect


![KY43_70UO628VO39UFFVH%9](https://user-images.githubusercontent.com/45505868/82578190-a3a7dc00-9bbe-11ea-8470-32334b3687ee.png)
I don't know if this is the way to upload pictures.
The fact is, when I wrote searchBody as searchBogy. The program continues to run without error.
What's the reason for that? I think if the searchBody parameter is wrong, elasticdump will stop instead of continuing to back up the full index.

**Comment by ferronrsmith** [comment]
Unknown flags/params are ignored.
