### ISSUE TITLE
wrong integer values when dumping int64 numbers

### ISSUE THREAD

**Issue by mohammadrezza** [elasticsearch-dump/elasticsearch-dump#701]
Hi,

**Comment by ferronrsmith** [comment]
This isn't really an issue, there is no replication steps or sample data.

**Comment by mohammadrezza** [comment]
> This isn't really an issue, there is no replication steps or sample data.
> 
> Also it helps to read the documentation. There is a `support-big-int` flag

oh, I didn't notice that. Thank you
