### ISSUE TITLE
Using elasticsearch-dump to migrate to ES Cloud. 

### ISSUE THREAD

**Issue by uzay** [elasticsearch-dump/elasticsearch-dump#702]
Reading articles like https://help.aiven.io/en/articles/3280782-moving-indexes-with-elasticsearch-dump-tool , seems like elasticsearch-dump is fully compatible with ES Cloud. Please verify and we'd love to contact individuals who have already used dump to migrate to ES Cloud.

**Comment by ferronrsmith** [comment]
Once the service is expose over http it will work with elasticsearch-dump. I’ve worked with clients who have used elastic cloud
