### ISSUE TITLE
The 413 status (Request Entity Too Large) returns no body; Need to more informed logging

### ISSUE THREAD

**Issue by aby0** [elasticsearch-dump/elasticsearch-dump#703]
**Context**

- ElasticDump version
6.0.0
- Elasticsearch version: 5.6.16
- Node.js version *(note that nodejs v8+ is required for this tool)*
v8.10.0
- Full command you are having issue with (with inputs and outputs)

`NODE_OPTIONS=--max_old_space_size=16384 elasticdump --input=document_content_index.json  --overwrite=true   --output=$ESURL/document_content_index   --type=data`

- A data-set you can share publicly which reproduces the problem

**Describe the bug**
While running this, the error that elasticdump gives is:
```Wed, 10 Jun 2020 23:44:33 GMT | Error Emitted => {}
Wed, 10 Jun 2020 23:44:33 GMT | Total Writes: 1115
Wed, 10 Jun 2020 23:44:33 GMT | dump ended with error (set phase)  => Error

This is happening because the error returned was empty.
```
    at Request.baseRequest (/usr/local/lib/node_modules/elasticdump/lib/transports/elasticsearch.js:671:15)

However, the status code and status message are as follows:
`413 Request Entity Too Large`

It would be great if we can provide better logging information in elastic dump. 

**Current behavior**
While running this, the error that elasticdump gives is:
```Wed, 10 Jun 2020 23:44:33 GMT | Error Emitted => {}
Wed, 10 Jun 2020 23:44:33 GMT | Total Writes: 1115
Wed, 10 Jun 2020 23:44:33 GMT | dump ended with error (set phase)  => Error

**Expected behavior**
A well-defined error message indicating the status message as well as the status code.

**Comment by aby0** [comment]
I can provide a small pull request for the same.

**Comment by ferronrsmith** [comment]
feel free to provide a PR. 

> NB: (Although I I'm not mistaking the body of a 413 is empty), so what's actually needed is a report of the status

**Comment by aby0** [comment]
@ferronrsmith Yeah! Since the body was empty, we can provide report status for better error messages. I will raise a PR soon. Thank you.

**Comment by ferronrsmith** [comment]
closed by https://github.com/elasticsearch-dump/elasticsearch-dump/commit/1654ca08612110dacf4c88fde8e870b12afcdff3
