### ISSUE TITLE
Export data and then Import the data in new ES Cluster changes the order  of _search query results

### ISSUE THREAD

**Issue by sangharshcs** [elasticsearch-dump/elasticsearch-dump#704]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version : Using latest docker image
- Elasticsearch version: 1.x/2.x
- Node.js version *(note that nodejs v8+ is required for this tool)*
- Full command you are having issue with (with inputs and outputs) 
- A data-set you can share publicly which reproduces the problem

**Describe the bug**

**To Reproduce**
1. Create Index, and create 200 documents with some random data.
2. do a search query /<index>/_search . Take a note of the id of the documents.
3. Dump --type=data
4.  Setup a new elastic search cluster and import the data dump into Step 3.
5. Order of result in response of query is different in step 2 & 5. 

**Current behavior**
Same as step in reproduce.

**Expected behavior**
I had an impression that order or results of search query should remain same.

**Comment by sangharshcs** [comment]
1. Setup Elastic Search on docker one node setup.

**Comment by ferronrsmith** [comment]
```
In Elasticsearch, the relevance score is represented by the floating-point number returned in the search results as the _score, so the default sort order is _score descending.
```

This isn't an issue with `elasticsearch-dump`, this has to do with how Elasticsearch (Lucene) changes sorting algorithm through versions.

**Comment by sangharshcs** [comment]
@ferronrsmith Thanks for the answer. I am following the steps:

1. Run Single node docker setup of ES 1
2. Create 100 documents with score=1
3. Export data using elasticdump.
4. Create **New** Single node docker setup of ES 1.

**Comment by ferronrsmith** [comment]
You’re assuming that the bulk endpoint inserts the document in the same way it was exported which is incorrect. It’s an asynchronous endpoint endpoint. This library doesn’t control order. You can try writing to ES directly to test your theory
