### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wym408** [elasticsearch-dump/elasticsearch-dump#705]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump 6.29.1
- Elasticsearch 6.8.2
- Node.js version *(note that nodejs v8+ is required for this tool)*
node -v   v12.18.0
npm -v  6.14.4 
- Full command you are having issue with (with inputs and outputs)
 /opt/node-v12.18.0-linux-x64/bin/elasticdump    --support-big-int=true    --input=https://IP:PORT/index_test_v1   --output=1.json   --searchBody '{"query": {"term": { "nickname": {"value": "01234567891011121314151617181920" }}}}' 

Sun, 14 Jun 2020 09:44:20 GMT | dump ended with error (get phase) => Error: Invalid number (value: "01234567891011121314151617181920")

--support-big-int=true    without this , it works fine ,but  I need this because other filed is  long type 

- A data-set you can share publicly which reproduces the problem
PUT index_test_v1
```json
{
  "mappings": {
    "type1": {
      "dynamic": "false",
      "_all": {
        "enabled": false
      },
      "properties": {
        "guid": {
          "type": "long"
        },
        "nickname": {
          "type": "keyword",
          "fields": {
            "nickname_fen": {
              "type": "text"
            }
          }
        }
      }
    }
  }
}
```

```
PUT index_test_v1/type1/647200872369
{
  "nickname": "01234567891011121314151617181920",
  "guid": 647200872369
} 
```

Thanks

**Comment by ferronrsmith** [comment]
I have added a new flag, that limits the fields that should be checked for `big-int-support`.

```bash
/opt/node-v12.18.0-linux-x64/bin/elasticdump --support-big-int=true --big-int-fields=guid --input=https://IP:PORT/index_test_v1 --output=1.json 
```
