### ISSUE TITLE
multielasticdump export data from cluster A to cluster B

### ISSUE THREAD

**Issue by kaushalshriyan** [elasticsearch-dump/elasticsearch-dump#710]
Hi,

I am currently running ES (version 7.5.1) three nodes in the cluster mode.

```
**Cluster A**
ES Node1:- 192.168.0.10
ES Node2 :- 192.168.0.11
ES Node3 :- 192.168.0.12
```

I want to migrate the data from the above running production cluster to new hardware in cluster mode whose IP details are as below.

```
**Cluster B**
ES Node1:- 172.16.1.10
ES Node2 :- 172.16.1.11
ES Node3:- 172.16.1.12
```

Is there an elegant and efficient way to copy the data from the current production ES Cluster ( 3 nodes) to the new hardware based ES Cluster ( 3 nodes). Any help will be highly appreciated and I look forward to hearing from you. Thanks in advance.

```
multielasticdump --direction=dump --match='^.*$' --input=http://192.168.0.10:9200 --output=/tmp/es_backupnode1
multielasticdump --direction=dump --match='^.*$' --input=http://192.168.0.11:9200 --output=/tmp/es_backupnode2
multielasticdump --direction=dump --match='^.*$' --input=http://192.168.0.12:9200 --output=/tmp/es_backupnode3 
```

I am referring to https://www.npmjs.com/package/elasticdump to run multielasticdump to restore it to the below nodes. I am not sure how do I import it the below mentioned nodes using second binary multielasticdump. 

```
**Cluster B**
ES Node1:- 172.16.1.10
ES Node2 :- 172.16.1.11
ES Node3:- 172.16.1.12
```
Please suggest and correct me if my approach is wrong. Thanks in Advance.

Best Regards,

Kaushal

**Comment by ferronrsmith** [comment]
You don't need to export all 3 nodes in a cluster, they all contain the same data.

```bash
multielasticdump --direction=dump --match='^.*$' --input=http://192.168.0.10:9200 --output=/tmp/es_backupnode --ignoreType=mapping,analyzer
```

to import =>

```bash
multielasticdump --direction=load --match='^.*$' --output=http://192.168.0.10:9200 --input=/tmp/es_backupnode --ignoreType=mapping,analyzer
```

Please spend some time and read the documentation.
