### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by niladriforu** [elasticsearch-dump/elasticsearch-dump#711]
**Is your feature request related to a problem? Please describe.**
We are using esdump  ( programming language : python ) inside a aws ecs task. While running, it is not able to assume the ecs task role . The ecs task role already has permissions to connect to our es service. ESdump does not have a option to pass an authentication , much like the way request module has . 

**Describe the solution you'd like**
Is there a way we can have this authentication passed?

**Describe alternatives you've considered**
No alternatives so far. Alternative would be going away from elasticdump.

**Give some examples of implementations**
NA
**Additional context**
NA

**Comment by ferronrsmith** [comment]
ESDump is a command line tool, beside the options that are available, there isn’t much else that can be done.

If you want to submit a PR that’s fine, but we already provided a rich feature-set for aws interaction

**Comment by jlloyd-widen** [comment]
In case anyone like me thought this was a dead end. I finally got this working in ECS after setting the environment variable `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` correctly.
