### ISSUE TITLE
[BUG] Error while parsing searchBody

### ISSUE THREAD

**Issue by Crazyht** [elasticsearch-dump/elasticsearch-dump#712]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version : 
     latest (try with npm and docker)
- Elasticsearch version : 
     6.8
- Node.js version *(note that nodejs v8+ is required for this tool)* : 
     12.16.1
- Full command you are having issue with (with inputs and outputs)
     elasticdump  --input=http://my_els_server:9200/organisations_9 --output=id_0_2.json --searchBody='{"query": {"match": {"revenueBracket.id": "CD28845B-0514-4010-862E-18C49B179171"}}}'

- A data-set you can share publicly which reproduces the problem

**Describe the bug**
I just try to add search body parameter when I export my data 

`undefined:1
{'query': {'match': {'revenueBracket.id': 'CD28845B-0514-4010-862E-18C49B179171'}}}
 ^

SyntaxError: Unexpected token ' in JSON at position 1
    at JSON.parse (<anonymous>)
    at argv.parse (C:\Users\.....\AppData\Roaming\npm\node_modules\←[4melasticdump←[24m\lib\argv.js:28:55)
    at Object.<anonymous> (C:\Users\.....\AppData\Roaming\npm\node_modules\←[4melasticdump←[24m\bin\elasticdump:98:6)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1158:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:1002:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:901:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)←[39m
←[90m    at internal/main/run_main_module.js:18:47←[39m`

I try same with docker version (to be sure is not my local environment have problem) with same error as result and also try to simply copy/paste your sample command and get same error.

**Comment by ferronrsmith** [comment]
The searchBody should be properly escaped 

```bash
--searchBody="{\"query\": {\"match\": {\"revenueBracket.id\": \"CD28845B-0514-4010-862E-18C49B179171\"}}}"
```
