### ISSUE TITLE
elasticdump import/export

### ISSUE THREAD

**Issue by superfenv** [elasticsearch-dump/elasticsearch-dump#716]
Elasticdump index exports data from the query condition and then imports another index, encountered a problem: '[location] is defined as an object in mapping [xxxx] but this name is already used for a field in other types'

es version: 5.5

step:
elasticdump --input=http://192.168.30.117:9200/xxxv2 --output=query.json --searchBody='{"query": {"match": {"source": "tuhu"}}}' 
elasticdump --input=query.json --output=http://192.168.30.115:9200/xxxv2  --type=data

**Comment by ferronrsmith** [comment]
That’s a mapping issue. You need to ensure both mappings are the same before you import data into the index

**Comment by ferronrsmith** [comment]
Export the mappings first, then import them into the index. Then import the data. A property can’t have multiple types
