### ISSUE TITLE
[BUG] Previously called "Request Entity Too Large"

### ISSUE THREAD

**Issue by admanheart** [elasticsearch-dump/elasticsearch-dump#717]
i use this dump app to rebuild index from es5 to es7 , i have a index with 270gb/per shard , total 20 shard.
when the script running for a while, the script quit with this error:
Error Emitted => The request is larger than the server is willing or able to process. Previously called "Request Entity Too Large".
so i try to output to local file,it's ok to run. 
is that a bug?

**Comment by ferronrsmith** [comment]
No, the server is telling you it can’t handle the amount of data being sent. Either increase the **http.max_content_length** or throttle down the amount of data being sent

**Comment by ferronrsmith** [comment]
Try to put as much information as possible into the issue last created. I don’t know the request you’re sending etc
