### ISSUE TITLE
Excuse me_ How does type synchronize

### ISSUE THREAD

**Issue by houziyu** [elasticsearch-dump/elasticsearch-dump#719]
My script
`
for i in {clx_order_info_index9,clx_order_child_index4,clx_order_contract_index1}
do
  echo '开始导入'+$i+'表类型为analyzer'
  elasticdump --input=http://***.***.233.23:9200/$i --output=http://***.***.233.24:9200/$i --type=analyzer
  sleep 3
  echo '开始导入'+$i+'表类型为mapping'
  elasticdump --input=http://***.***.233.23:9200/$i --output=http://***.***.233.24:9200/$i --type=mapping
  sleep 3
  echo '开始导入'+$i'+表类型为data'
  elasticdump --input=http://***.***.233.23:9200/$i --output=http://***.***.233.24:9200/$i --type=data
done`
It doesn't seem to be a problem after syncing. But mine_ Type is not synchronized. What am I supposed to do_ Type is in sync, thank you
<img width="970" alt="WX20200720-151943@2x" src="https://user-images.githubusercontent.com/17023204/87911095-a3806b80-ca9d-11ea-885e-1990dc1ca4c1.png">
<img width="850" alt="WX20200720-152018@2x" src="https://user-images.githubusercontent.com/17023204/87911107-a7ac8900-ca9d-11ea-8e26-2577c4ac4ce4.png">

**Comment by houziyu** [comment]
After synchronization_ Type from the order of the source data_ Contract3 becomes_ Doc

**Comment by ferronrsmith** [comment]
Type parameter was deprecated from Elastic 6.8 off by default in ES 7. You can specify a type param.

**Comment by ferronrsmith** [comment]
> In 6.8, the index creation, index template, and mapping APIs support a query string parameter (include_type_name) which indicates whether requests and responses should include a type name. It defaults to true, and should be set to an explicit value to prepare to upgrade to 7.0. Not setting include_type_name will result in a deprecation warning. Indices which don’t have an explicit type will use the dummy type name _doc.
https://www.elastic.co/guide/en/elasticsearch/reference/7.x/removal-of-types.html
