### ISSUE TITLE
[BUG/IMPROVEMENT] inputTransport and outputTransport not used?

### ISSUE THREAD

**Issue by somehowchris** [elasticsearch-dump/elasticsearch-dump#720]
**Context**
I'm currently learning rust and I thought it would be a good idea to learn a language with a real project. So I thought that I could make some kind of port of elasticdump to rust.

**Describe the bug**
As I dug through the code I found `inputTransport` and `outputTransport` in the README, help text and the defaults but no where in the code. There is also some test with a transport in a file but those use `--transport`

Am I not aware of some code or are those not used?

**Comment by ferronrsmith** [comment]
What you're looking for is the [ioHelper](https://github.com/elasticsearch-dump/elasticsearch-dump/blob/master/lib/ioHelper.js).
