### ISSUE TITLE
[BUG] generateFilePath problem

### ISSUE THREAD

**Issue by thxwelchs** [elasticsearch-dump/elasticsearch-dump#721]
- ElasticDump version: 6.30.0
- Elasticsearch version: 7.4
- Node.js version: 12.4

I have an index, and at the end of the name of this is YYYY.mm.dd format.

For example, this is'**index-2020.07.30**'

There is one problem, which causes the wrong file name to be generated according to the following update from 6.27.4.
[commit](https://github.com/elasticsearch-dump/elasticsearch-dump/commit/dbf6d1ffd1cbe71a2de1ef92c1ddfd01fb068880)
```javascript
static generateFilePath (rootFileName, numFiles, compress) {
    const ext = path.extname(rootFileName)
    const dir = path.dirname(rootFileName)
    const baseName = path.basename(rootFileName, ext)
    return path.join(dir, `${baseName}.split-${numFiles}${ext}${compress ? '.gz' : ''}`)
}
```
Then the file name was generated. It is'**index-2020.07-split.1.20**'.

I want to keep my index name. Can you solve this problem?

**Comment by ferronrsmith** [comment]
This isn't a bug. You included an output without an extension which is why you're having issues.

Simply use `index-2020.07.30.jsonl` instead of `index-2020.07.30`
