### ISSUE TITLE
Error Emitted => getaddrinfo ENOTFOUND kibana kibana:443

### ISSUE THREAD

**Issue by nikuljain** [elasticsearch-dump/elasticsearch-dump#723]
Thu, 13 Aug 2020 09:48:53 GMT | starting dump
Thu, 13 Aug 2020 09:49:13 GMT | Error Emitted => getaddrinfo ENOTFOUND kibana kibana:443
Thu, 13 Aug 2020 09:49:13 GMT | Error Emitted => getaddrinfo ENOTFOUND kibana kibana:443
Thu, 13 Aug 2020 09:49:13 GMT | Total Writes: 0
Thu, 13 Aug 2020 09:49:13 GMT | dump ended with error (get phase) => Error: getaddrinfo ENOTFOUND kibana kibana:443

elasticdump --debug --bulk=true --cert xxx --key xxx --ca xxx  --input=https://kibana:$PASSWORD@ESname/:9200index --output=/tmp/es_test-index_mapping.json --type=mapping

**Comment by ferronrsmith** [comment]
Look at the address and ensure it's correct

**Comment by liujiashun0520** [comment]
It occured to me too, and have no idea how to fix it.
