### ISSUE TITLE
[QUESTION] One elasticdump process per index

### ISSUE THREAD

**Issue by oswellchan** [elasticsearch-dump/elasticsearch-dump#727]
Instead of using `multielasticdump`, can I just run one `elasticdump` process per index? This is as `multielasticdump` is missing some features. Are there any dangers of doing so?

**Comment by ferronrsmith** [comment]
`elasticdump` is the superset and `multielasticdump` offers just a subset of the features offered by multielasticdump

**Comment by oswellchan** [comment]
Hi @ferronrsmith, just a clarification. Is it safe to run multiple `elasticdump` processes in parallel?

**Comment by ferronrsmith** [comment]
Yes it's safe to run multiple instances of elasticdump
