### ISSUE TITLE
[FEATURE] Bulk using size of request instead number of document

### ISSUE THREAD

**Issue by truongthanh96** [elasticsearch-dump/elasticsearch-dump#728]
**Is your feature request related to a problem? Please describe.**
As a user, sometime we have a lot of indices, some indices are small documents, while some are very large. With small indices we can use --limit=10000 but is not feasible for large document, we have to manually work out a smaller number (like 1000) otherwise elastic dump return with error.

**Describe the solution you'd like**
1. Like https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-docs-bulk-processor.html allow to limit by size of request, we can try that for elasticdump too.

**Describe alternatives you've considered**

**Give some examples of implementations**
```
npx elasticdump --bulkSize=10mb
```
**Additional context**

**Comment by ferronrsmith** [comment]
This might be useful for when documents are being imported from a file, but from ES to ES, S3 to ES this isn't really useful or straight-forward. The bulk-processor holds docs in memory then flushes when a particular threshold is reached.

From ES -> ES. I would u know how much document to pull?
