### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by heliusjing** [elasticsearch-dump/elasticsearch-dump#729]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version:latest
- Elasticsearch version:6.5.1
- Node.js version *(note that nodejs v10+ is required for this tool)*:latest from official
- Full command you are having issue with (with inputs and outputs)
`      elasticdump \
        --input=${es_url}/${index} \
        --output=${backup_dir}/${time}/${index}/${type}.json \
        --type=${type} \
        --limit=5000 \
        --concurrency=10 \
        --fsCompress \
        --fileSize=10kb \
        --overwrite=true >>${logfile}`

**Describe the bug**
I used --filesize,i don't know how to restore from the spilted files?
can i get any help from here ?

**Comment by ferronrsmith** [comment]
You can use multi-elasticdump to restore all files in a folder or simply restore 1 at a time

**Comment by heliusjing** [comment]
> You can use multi-elasticdump to restore all files in a folder or simply restore 1 at a time

thanks
