### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by heliusjing** [elasticsearch-dump/elasticsearch-dump#730]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version：latest
- Elasticsearch version:6.5
- Node.js version:lastest
- Full command you are having issue with (with inputs and outputs)
        elasticdump \
          --input=${file} \
          --output=${es_url}/${index} \
          --type=${type} \
          --fsCompress \
          --limit=1000

### Describe the bug
When restoring mapping, there is an error, but it seems that after importing, there is no bad effect

### Error
`Wed, 23 Sep 2020 13:11:56 GMT | Error Emitted => {"root_cause":[{"type":"remote_transport_exception","reason":"[master-02][192.168.201.21:9300][indices:admin/mapping/put]"}],"type":"illegal_argument_exception","reason":"Enabling [_all] is disabled in 6.0. As a replacement, you can use [copy_to] on mapping fields to create your own catch all field."}
Wed, 23 Sep 2020 13:11:56 GMT | Error Emitted => {"root_cause":[{"type":"remote_transport_exception","reason":"[master-02][192.168.201.21:9300][indices:admin/mapping/put]"}],"type":"illegal_argument_exception","reason":"Enabling [_all] is disabled in 6.0. As a replacement, you can use [copy_to] on mapping fields to create your own catch all field."}`

*Screenshots*
![image](https://user-images.githubusercontent.com/17847020/94018182-e1be4200-fde2-11ea-9473-7f6b6f9174ea.png)

**Comment by ferronrsmith** [comment]
Error is self explanatory. _all isn't available in Ed 6, which means you need to update the mapping before importing it into Ed 6
