### ISSUE TITLE
[BUG] Action/metadata line [1] contains an unknown parameter [timestamp]

### ISSUE THREAD

**Issue by Cactice** [elasticsearch-dump/elasticsearch-dump#731]
**Context**
- ElasticDump version: 6.33.4
- Elasticsearch version: 7.9.2
- Node.js version *(note that nodejs v10+ is required for this tool)* : v12.17.0
- Full command you are having issue with (with inputs and outputs)
```
➜  elasticsearch-reproducable-bug git:(main) yarn dump
yarn run v1.22.5
$ ./elasticsearch/load_wiki_dump.sh
Tue, 06 Oct 2020 12:38:14 GMT | starting dump
Tue, 06 Oct 2020 12:38:14 GMT | got 20 objects from source file (offset: 0)
Tue, 06 Oct 2020 12:38:14 GMT | Error Emitted => {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [timestamp]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [timestamp]"},"status":400}
Tue, 06 Oct 2020 12:38:14 GMT | Error Emitted => {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [timestamp]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [timestamp]"},"status":400}
Tue, 06 Oct 2020 12:38:14 GMT | Total Writes: 0
Tue, 06 Oct 2020 12:38:14 GMT | dump ended with error (get phase) => BAD_REQUEST: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [timestamp]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [timestamp]"},"status":400}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
- A data-set you can share publicly which reproduces the problem
I want to load [example.json](https://github.com/Cactice/elasticsearch-reproducable-bug/blob/main/elasticsearch/example.json) to my elasticsearch. (Data from wikimedia)
I use[ this command](https://github.com/Cactice/elasticsearch-reproducable-bug/blob/main/elasticsearch/load_wiki_dump.sh) to load.

**Describe the bug**

**To Reproduce**
1. Go to '[minimal repo](https://github.com/Cactice/elasticsearch-reproducable-bug)'
2. Clone and Follow README

**Current behavior**
I get status 400

**Expected behavior**
Get successful status like 200 or 201

Thanks.
Sorry if this is a basic mistake. I'm new to elasticsearch.

**Comment by ferronrsmith** [comment]
The data isn't in a format that can be processed by elasticdump

**Comment by ferronrsmith** [comment]
```jsonl
{"_index":"bigint_index","_type":"seeds","_id":"0","_score":1,"_source":{"key":1726275868403174266,"_uuid":"0"}}
{"_index":"bigint_index","_type":"seeds","_id":"1","_score":1,"_source":{"key":99926275868403174266,"_uuid":"1"}}
```

**Comment by mfelician** [comment]
Just want to add a comment that this issue happens when you migrate data from ES that is older than version 5 to something newer ES that deosn't support this field. https://www.elastic.co/guide/en/elasticsearch/reference/2.4/mapping-timestamp-field.html

A possible workaround is to use --transform feature to remove this field from the input.
