### ISSUE TITLE
UnhandledPromiseRejectionWarning npm package to ES running in docker

### ISSUE THREAD

**Issue by mayureshs** [elasticsearch-dump/elasticsearch-dump#737]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version : 6.39.0
- Elasticsearch version : 6.8.6
- Node.js version *(note that nodejs v10+ is required for this tool)*  : 14.5.0

- Full command you are having issue with (with inputs and outputs)
elasticdump --bulk=true --input="C:\Temp\product.json" --output=http://localhost:5601/test-index

- A data-set you can share publicly whic
[error.txt](https://github.com/elasticsearch-dump/elasticsearch-dump/files/5527178/error.txt)

h reproduces the problem
Sample data attached.

**Describe the bug**
Installed npm package for ElasticDump and then import data into Elastic that is running in docker container. Getting the error below. Also the file is attached.

UnhandledPromiseRejectionWarning: Error: failed to parse json (message: "Unexpected token < in JSON at position 0") - source: "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\"><meta name=\"viewport\" content=\"width=device-width\"><title>Kibana</title><style>@font-face {\n  font-family: 'Open Sans';\n  font-style: normal;\n  font-weight: 300;\n  src: local('Open Sans Light'), local('O

**Comment by ferronrsmith** [comment]
The app is called elasticdump, it doesn't work with kibana

**Comment by mayureshs** [comment]
My bad, did not have the correct port of 9200
