### ISSUE TITLE
[FEATURE] Import file compressed

### ISSUE THREAD

**Issue by mikycol** [elasticsearch-dump/elasticsearch-dump#739]
I need to re-import a dump split across multiple files and compressed. I can't find any option that accepts the compressed file directly as input. It would be useful to be able to run it with a single command and not have to do a procedure.

**Comment by ferronrsmith** [comment]
```
--fsCompress
                    gzip data before sending output to file.
                    On import the command is used to inflate a gzipped file
```

**Comment by brendandebeasi** [comment]
@ferronrsmith Is there a way to use this with files that have been split and gzipped in a previous export? For example, I am trying to import `domains.split-0.gz` ... `domains.split-17.gz`, but I cannot see a way to pass all the files via the input param.  It looks like wildcards are not supported.
