### ISSUE TITLE
An error occurred when importing a large number of records from a json file to es

### ISSUE THREAD

**Issue by luguifang** [elasticsearch-dump/elasticsearch-dump#740]
I have a json file of about 16GB, I plan to import it into es, an error occurred when elasticdump imported 4030000.
import command:
/usr/local/bin/elasticdump --output=http://localhost:9200/ --input=/home/pvc/Downloads/backup/omni-es.json --limit=10000

![image](https://user-images.githubusercontent.com/10445214/99208157-b4967a80-27fa-11eb-8a95-cf66d35e151e.png)

**Comment by luguifang** [comment]
elaticdump version is 6.16.2

**Comment by ferronrsmith** [comment]
That screenshot isn't very informative, recent version of 'elasticdump' fixed issues with error propagation. 

It could be anything. There is most like from ES which could be caused by the request being too large, http size too large. I really don't know. 

My advice is to upgrade to the latest version and try again.

**Comment by luguifang** [comment]
@ferronrsmith Thank you for your reply,I will try the the latest version

**Comment by luguifang** [comment]
@ferronrsmith 
the lasest version  occurred Error:
![image](https://user-images.githubusercontent.com/10445214/99341000-0b1bbb80-28c4-11eb-9478-a3caeb084140.png)
Is this a problem with es? es version is 6.2.3

**Comment by ferronrsmith** [comment]
Seems like a memory issue, try increasing `max_old_space_size`


```
NODE_OPTIONS=--max_old_space_size=4012 /usr/local/bin/elasticdump --output=http://localhost:9200 --input=/home/pvc/Downloads/backup/omni-es.json --limit=10000
```

**Comment by luguifang** [comment]
@ferronrsmith hi ferronrsmith
When I use the command you provided, the problem still exists.
Before I execute the command, the system memory is as follows:
![image](https://user-images.githubusercontent.com/10445214/99352561-cef55480-28dd-11eb-826c-5ae433d48a90.png)
When elasticdump imports 4030000 data, the system memory is as follows:
![image](https://user-images.githubusercontent.com/10445214/99352693-0f54d280-28de-11eb-9096-185b146d5511.png)
elasticdump print error is:
![image](https://user-images.githubusercontent.com/10445214/99352756-21367580-28de-11eb-8ef1-50782dbd2eb0.png)
something else i need do?

**Comment by ferronrsmith** [comment]
By default Elasticsearch only accepts 100mb chunks. You need to increase this, or reduce the amount of records sent.

```
 http.max_content_length
    (Static) Maximum length of an HTTP request body. Defaults to 100MB. 
```

**Comment by luguifang** [comment]
@ferronrsmith  thanks, When I change the value of max_content_length in elasticsearch.yml, the problem is solved.

**Comment by ferronrsmith** [comment]
:+1:
