### ISSUE TITLE
Issue while dumping template to file, Error: dump ended with error (get phase) => Error: {}

### ISSUE THREAD

**Issue by gs-catapult** [elasticsearch-dump/elasticsearch-dump#742]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version - **6.39.0**, installed with npm
- Elasticsearch version - **6.2.2**
- Node.js version *(note that nodejs v10+ is required for this tool)* - **v15.1.0**
- Full command you are having issue with (with inputs and outputs) - 

```
$ elasticdump \
   --input=https://elasticsearch:9200/units \
   --output=templates.json \
   --type=template \
   --debug=true
```

- A data-set you can share publicly which reproduces the problem - Not applicable

**Describe the bug**
Our daily process takes backup of following types 'settings analyzer mapping data alias template' for different indexes by using ElasticDump version 6.34.1. Till yesterday it was working fine. 
Today after upgrading to ElasticDump version - 6.39.0, backup job started failing with **error dump ended with error (get phase) => Error: {}**

**To Reproduce**
Steps to reproduce the behaviour:
Try to dump template to a file using the above command, it will fail with below errors. 

```
Tue, 17 Nov 2020 01:13:01 GMT | starting dump  
Tue, 17 Nov 2020 01:13:02 GMT [debug] | discovered elasticsearch input major version: 6  
Tue, 17 Nov 2020 01:13:02 GMT | Error Emitted => {}  
Tue, 17 Nov 2020 01:13:02 GMT | Error Emitted => {}  
Tue, 17 Nov 2020 01:13:02 GMT | Total Writes: 0  
Tue, 17 Nov 2020 01:13:02 GMT | dump ended with error (get phase) => Error: {}
```

**Current behavior**
Dump of index template is failing with blank error. It does not report what was the actual error.
```
Tue, 17 Nov 2020 01:13:02 GMT | dump ended with error (get phase) => Error: {}
```

**Expected behavior**
It should dump template data in json file (i.e data whatever is returned by elasticsearch, emtpy json or actual data).  This was working fine till ElasticDump version 6.34.1 

**Screenshots**
Not applicable

**Additional context**
Not applicable

**Comment by ferronrsmith** [comment]
That's because before it was failing silently. Now it actually throws an error

**Comment by gs-catapult** [comment]
Could you please reopen this and investigate bit more on this below points.
- If there are errors, why elasticsearch-dump report blank errors **'dump ended with error (get phase) => Error: {}'**
- elasticsearch-dump should report the actual error from elasticsearch, if any.
- Also It appears there were no errors raised by elasticsearch. When template is fetched with curl, it respond with empty json. 
This can be verified with below command in terminal,
```
$ curl -XGET 'https://elasticsearch:9200/_template/units?pretty'
{ }
```
- elasticsearch-dump is expected to return the result of elasticsearch query instead of raising a blank error.

**Comment by ferronrsmith** [comment]
- The error wasn't properly parsed, but it's a NOT_FOUND exception
- it does
- your curl command is an error. increase the verbosity


```
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1:9200...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9200 (#0)
> GET /_template/units?pretty HTTP/1.1
> Host: localhost:9200
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Warning: 299 Elasticsearch-6.7.0-8453f77 "[types removal] The parameter include_type_name should be explicitly specified in get template requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', which means responses will omit the type name in mapping definitions."
< content-type: application/json; charset=UTF-8
< content-length: 4
< 
{ }
* Connection #0 to host localhost left intact

```
