### ISSUE TITLE
[BUG] aws token expires when running a long dump

### ISSUE THREAD

**Issue by marcosfilho** [elasticsearch-dump/elasticsearch-dump#746]
not sure if this would be a bug or a feature request but here I go:

I'm currently running elasticdump to move data from ElasticSearch  V5.5 to another ElasticSearch version 7.8. both cluster are AWS managed Elastic Search. 

I moved a few small indices(smaller than 100GB) and it worked well. however, when I try to move large indices, larger than 100Gb, and the process takes more than 5 hours, I get the following error:

_Thu, 19 Nov 2020 12:18:16 GMT | dump ended with error (get phase) => Error: {"message":"The security token included in the request is expired"}_

elasticDump version: 6.34.1
- Elasticsearch version. input 5.5 output 7.8
- Node.js version : 14
- Full command you are having issue with (with inputs and outputs)

elasticdump --input=https://elastic-5/myindex  --output=https://elastic7/myindex --type=data --noRefresh --limit=2300 --awsChain=true   

I run elasticdump from a EC2(windows) and it has the IAM role that has rights to read and write from/to both clusters.

is there any way elasticdump can renew the token before it expires?
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Credentials.html

**Comment by ferronrsmith** [comment]
I see the issue, seems the credentials expired (default limit is 1hr). We didn't implement the refresh logic because no one ever asked for it. 

I can add it, but I have no means of testing this since I don't have AWS. Would you be able to test it ?

**Comment by marcosfilho** [comment]
it took around 5 hours for the token to expire. not sure if that's a configurable value(I'm using a company's aws account)

I can definitely test it.

**Comment by ferronrsmith** [comment]
elasticdump@6.49.0 contains token refresh logic

**Comment by marcosfilho** [comment]
alright thank you. I'm going to test now and will get back to you.
it should take a few hours

**Comment by marcosfilho** [comment]
getting this error now:

 **Cannot read property 'get' of undefined**

I need to move to a dev and fresh  environment to test it properly .. will  get back to you by tomorrow

**Comment by ferronrsmith** [comment]
are you sure you're using the latest? that issue was fixed.

**Comment by marcosfilho** [comment]
I just tried it in a fresh environment. installed node and elasticdump from scratch

got the same error:
**Fri, 20 Nov 2020 07:27:38 GMT | Error Emitted => Cannot read property 'get' of undefined**

I tried in version 6.49.1 and 6.50.0 and added the flag --awsRefresh( is this flag really needed? do we want ever let the token expire?)

let me know how I can help to troubleshoot this.

thanks a lot for helping

**Comment by ferronrsmith** [comment]
No worries I think I'll have to check the credentials object for the existence of the refresh property

**Comment by ferronrsmith** [comment]
pushed a new release. the credentials object should never be null, think i might have to re-implement using promises

**Comment by marcosfilho** [comment]
thank you.
just updated to 6.50.2 and now I get this error:

**Error Emitted => {"message":"The security token included in the request is invalid."}**

let me know if I can help ..

**Comment by ferronrsmith** [comment]
Is this with every request or after expiration?

**Comment by ferronrsmith** [comment]
It might be the aws docs, but the refresh mechanism doesn't seem to working in the last few implementations. I've changed the logic to clear the cached token. Let's see if this works.

**Comment by marcosfilho** [comment]
sorry I should have explained. 

in the last error I reported, it failed right away when I started elasticdump. Apparently it didn't get the token at that time.

I just updated to 6.50.3 and now it was able to get the token and the dump is running.
I'll wait it for a few hours to see if it will refresh the token.

Thanks again for helping with this.

I'll update you tomorrow.

**Comment by ferronrsmith** [comment]
Ensure you're using the `awsRefresh` flag. This removes the token from cache when each request is made.

**Comment by marcosfilho** [comment]
yeah I did enable the flag ..

_elasticdump --input="mycluster-at-aws/my_index" --output=/tmp/data.json --type=data --awsRefresh --overwrite_ 

_Fri, 20 Nov 2020 23:23:41 GMT | starting dump
Fri, 20 Nov 2020 23:23:42 GMT | got 100 objects from source elasticsearch (offset: 0)
Fri, 20 Nov 2020 23:23:42 GMT | sent 100 objects to destination file, wrote 100
Fri, 20 Nov 2020 23:23:42 GMT | got 100 objects from source elasticsearch (offset: 100)
Fri, 20 Nov 2020 23:23:42 GMT | sent 100 objects to destination file, wrote 100
Fri, 20 Nov 2020 23:23:42 GMT | got 100 objects from source elasticsearch (offset: 200)
Fri, 20 Nov 2020 23:23:42 GMT | sent 100 objects to destination file, wrote 100
Fri, 20 Nov 2020 23:23:42 GMT | got 100 objects from source elasticsearch (offset: 300)
Fri, 20 Nov 2020 23:23:42 GMT | sent 100 objects to destination file, wrote 100
Fri, 20 Nov 2020 23:23:42 GMT | got 100 objects from source elasticsearch (offset: 400)
Fri, 20 Nov 2020 23:23:42 GMT | sent 100 objects to destination file, wrote 100
Fri, 20 Nov 2020 23:23:42 GMT | got 100 objects from source elasticsearch (offset: 500)
Fri, 20 Nov 2020 23:23:42 GMT | sent 100 objects to destination file, wrote 100_
 
I think that flag should default to true and if the user wants, they can set it to false. but this is just my humble opinion

**Comment by marcosfilho** [comment]
apologies my bad. if I add --awsChain, it fails 

**Admin:~/environment $ elasticdump --input="https://mycluster-at-aws/xerobusiness_109-3" --output=/tmp/data.json --type=data --awsRefresh --overwrite --awsChain**

_Fri, 20 Nov 2020 23:28:27 GMT | starting dump
Fri, 20 Nov 2020 23:28:28 GMT | Error Emitted => {"message":"The security token included in the request is invalid"}
Fri, 20 Nov 2020 23:28:28 GMT | Error Emitted => {"message":"The security token included in the request is invalid"}
Fri, 20 Nov 2020 23:28:28 GMT | Total Writes: 0
Fri, 20 Nov 2020 23:28:28 GMT | **dump ended with error (get phase) => Error: {"message":"The security token included in the request is invalid"}**_

**Comment by marcosfilho** [comment]
apologies my bad. if I add --awsChain, it fails 

**Admin:~/environment $ elasticdump --input="https://mycluster-at-aws/my_index" --output=/tmp/data.json --type=data --awsRefresh --overwrite --awsChain**

_Fri, 20 Nov 2020 23:28:27 GMT | starting dump
Fri, 20 Nov 2020 23:28:28 GMT | Error Emitted => {"message":"The security token included in the request is invalid"}
Fri, 20 Nov 2020 23:28:28 GMT | Error Emitted => {"message":"The security token included in the request is invalid"}
Fri, 20 Nov 2020 23:28:28 GMT | Total Writes: 0
Fri, 20 Nov 2020 23:28:28 GMT | **dump ended with error (get phase) => Error: {"message":"The security token included in the request is invalid"}**_

**Comment by marcosfilho** [comment]
I need to jump into my other windows environment and do this test again. will update you tomorrow

**Comment by ferronrsmith** [comment]
> yeah I did enable the flag ..
> 
> 
> 
> _elasticdump --input="mycluster-at-aws/my_index" --output=/tmp/data.json --type=data --awsRefresh --overwrite_ 
> 
> 
> 
> _Fri, 20 Nov 2020 23:23:41 GMT | starting dump
> 
> Fri, 20 Nov 2020 23:23:42 GMT | got 100 objects from source elasticsearch (offset: 0)
> 
> Fri, 20 Nov 2020 23:23:42 GMT | sent 100 objects to destination file, wrote 100
> 
> Fri, 20 Nov 2020 23:23:42 GMT | got 100 objects from source elasticsearch (offset: 100)
> 
> Fri, 20 Nov 2020 23:23:42 GMT | sent 100 objects to destination file, wrote 100
> 
> Fri, 20 Nov 2020 23:23:42 GMT | got 100 objects from source elasticsearch (offset: 200)
> 
> Fri, 20 Nov 2020 23:23:42 GMT | sent 100 objects to destination file, wrote 100
> 
> Fri, 20 Nov 2020 23:23:42 GMT | got 100 objects from source elasticsearch (offset: 300)
> 
> Fri, 20 Nov 2020 23:23:42 GMT | sent 100 objects to destination file, wrote 100
> 
> Fri, 20 Nov 2020 23:23:42 GMT | got 100 objects from source elasticsearch (offset: 400)
> 
> Fri, 20 Nov 2020 23:23:42 GMT | sent 100 objects to destination file, wrote 100
> 
> Fri, 20 Nov 2020 23:23:42 GMT | got 100 objects from source elasticsearch (offset: 500)
> 
> Fri, 20 Nov 2020 23:23:42 GMT | sent 100 objects to destination file, wrote 100_
> 
>  
> 
> I think that flag should default to true and if the user wants, they can set it to false. but this is just my humble opinion

Yea you're right, I plan on doing this if it works

**Comment by ferronrsmith** [comment]
> apologies my bad. if I add --awsChain, it fails 
> 
> 
> 
> **Admin:~/environment $ elasticdump --input="https://mycluster-at-aws/my_index" --output=/tmp/data.json --type=data --awsRefresh --overwrite --awsChain**
> 
> 
> 
> _Fri, 20 Nov 2020 23:28:27 GMT | starting dump
> 
> Fri, 20 Nov 2020 23:28:28 GMT | Error Emitted => {"message":"The security token included in the request is invalid"}
> 
> Fri, 20 Nov 2020 23:28:28 GMT | Error Emitted => {"message":"The security token included in the request is invalid"}
> 
> Fri, 20 Nov 2020 23:28:28 GMT | Total Writes: 0
> 
> Fri, 20 Nov 2020 23:28:28 GMT | **dump ended with error (get phase) => Error: {"message":"The security token included in the request is invalid"}**_

This is strange because I basically reverted back to what it was before excluding caching

**Comment by ferronrsmith** [comment]
Are you sure the environment is set up properly for aws authentication. Seems strange it doesn't work anymore, when basically nothing changed

**Comment by marcosfilho** [comment]
Thanks for that.
I’ll retest everything later and will let you know.
We could do a little zoom session to troubleshoot if you’re keen

**Comment by ferronrsmith** [comment]
Sounds good, just let me know !

**Comment by marcosfilho** [comment]
i just tested the latest version and  I keep getting the same error as before.

If I revert elasticdump back to 6.34.1, it works fine.

maybe we could try to revert back the aws sdk version and test it?
https://github.com/elasticsearch-dump/elasticsearch-dump/commit/57b04307177e79d4dc39cca17ef0fcbf6e61c54b#

**Comment by ferronrsmith** [comment]
Latest version reverts back to the old way

https://github.com/elasticsearch-dump/elasticsearch-dump/commit/86edb520059a1aca983d1d75622462a3bb50a505

**Comment by ferronrsmith** [comment]
Here is a diff https://github.com/elasticsearch-dump/elasticsearch-dump/compare/v6.34.1...master

**Comment by marcosfilho** [comment]
What time zone are you in? 

It’s weird that it works on version 6.34.1

**Comment by ferronrsmith** [comment]
If it's working on 6.34.1 then it's an upstream package issue.

**Comment by ferronrsmith** [comment]
> What time zone are you in? 
> 
> It’s weird that it works on version 6.34.1
> 
> 
> > On 22/11/2020, at 10:49 AM, Ferron H <notifications@github.com> wrote:
> > 
> > ﻿
> > Here is a diff v6.34.1...master
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Atlantic Standard Time (GMT-4)

**Comment by ferronrsmith** [comment]
I'm going to revert back aws-sdk so your can test

**Comment by ferronrsmith** [comment]
Reverted back packages + signing back to v6.34.1
