### ISSUE TITLE
How to encode "@"

### ISSUE THREAD

**Issue by tcyufeng** [elasticsearch-dump/elasticsearch-dump#749]
Within the user and password field, any ":","@", or "/" must be encoded.

_Originally posted by @ferronrsmith in https://github.com/elasticsearch-dump/elasticsearch-dump/issues/700#issuecomment-632105276_

**Comment by tcyufeng** [comment]
![image](https://user-images.githubusercontent.com/28287106/100999743-11828680-3598-11eb-88ec-9327fd1366a5.png)

**Comment by tcyufeng** [comment]
![image](https://user-images.githubusercontent.com/28287106/101000295-a7b6ac80-3598-11eb-8a68-816e4455c77b.png)

**Comment by ferronrsmith** [comment]
% - is a zsh expansion character which must be escaped. Wrap the output in quotes.

`--output 'http://%ssas@localhost:9200/whatever'`

http://zsh.sourceforge.net/Doc/Release/Expansion.html#Word-Designators
