### ISSUE TITLE
[BUG] Hanging on same offset on AWS ECS

### ISSUE THREAD

**Issue by PSJMcNeill** [elasticsearch-dump/elasticsearch-dump#750]
**Context**
Running AWS managed Elasticsearch
- Running Elasticdump 6.57.0 via Docker 
- Docker image is running on ECS on AWS
Exporting Index to S3

**Describe the bug**
When exporting ES Dump will hang on the same offset everytime.

got 100 objects from source elasticsearch (offset: 13000)
 sent 100 objects to destination file, wrote 100

Above are the logs where it gets to everytime before hanging and never continuing.

**To Reproduce**
1. Running docker container on ECS via fargate 
2. Commands are --input, --output (output being a S3 bucket)

**Comment by ferronrsmith** [comment]
Sounds like a network error. There isn't enough information here to diagnose

**Comment by PSJMcNeill** [comment]
Issue was I had autoscaling rules on the ECS that were spinning up a second container and interrupting the first for some reason.

Removing autoscaling and to a one time run on Fargate solved it.
