### ISSUE TITLE
[BUG] not able to authorize with EC2MetadataCredentials 

### ISSUE THREAD

**Issue by brucke** [elasticsearch-dump/elasticsearch-dump#751]
Hi, 

i'm not sure if it is a bug or there is a problem on my side. But i hope you can help me to fix it. 

**Context**
- ElasticDump 6.57.0:
- Elasticsearch version: 7.4
- Node.js version: 12
- Full command you are having issue with (with inputs and outputs)

``` 
bin/elasticdump --debug=true \
--awsChain=true \
--fileSize=1gb \
--output=s3://XXXes-archive-XXXXX/my-index \
--input=https://myelastichsearch/my-index
```

**Describe the bug**

We want to use the elasticdump docker container within kubernetes cluster to run every day and dump our data to S3. 

Our security concept is based on kube2iam which attach policicies to Pods as EC2MetaInformations. 

I tried the library on my local machine with my AWS Credentials and everything looks fine but on my Kubernetes Cluster we are not able to get data from ElasticSerach. I guess there is a problem with the signing request. 

I added some logs to provide more information's about the internal behaviour of the library. 

```
// aws4signer.js
...

aws4.sign(esRequest, credentials)

console.log(esRequest.headers['host'])
console.log(esRequest.headers['Content-Type'])
console.log(esRequest.headers['Content-Length'])
console.log(esRequest.headers['X-Amz-Date'])
console.log(esRequest.headers['Authorization'])
console.log(esRequest.path)
console.log(esRequest.hostname)
```

It seems the EC2MetadataCredentials did not return the credentials before the sign request was called. 

```
myelastichsearch.com
application/json
undefined
20201210T140647Z
AWS4-HMAC-SHA256 Credential=undefined/20201210/eu-central-1/es/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=62dfb75bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
/?
myelastichsearch.com
Thu, 10 Dec 2020 14:06:47 GMT | Error Emitted => {"message":"The security token included in the request is invalid."}
Thu, 10 Dec 2020 14:06:47 GMT | Error Emitted => {"message":"The security token included in the request is invalid."}
``` 

After that i changed the implementation to

```
// aws4signer.js

AWS.CredentialProviderChain.defaultProviders = [
  function () { return new AWS.EnvironmentCredentials('AWS'); },
  function () { return new AWS.EnvironmentCredentials('AMAZON'); },
  function () { return new AWS.SharedIniFileCredentials(); },
  function () { return new AWS.ECSCredentials(); },
  function () { return new AWS.ProcessCredentials(); },
  function () { return new AWS.TokenFileWebIdentityCredentials(); },
  function () { return new AWS.EC2MetadataCredentials() }
]
console.log("providers: " + AWS.CredentialProviderChain.defaultProviders )
var promise = new AWS.CredentialProviderChain().resolvePromise();

...

promise.then((credentials) =>  {
  aws4.sign(esRequest, credentials)
  console.log(esRequest.headers['host'])
  console.log(esRequest.headers['Content-Type'])
  console.log(esRequest.headers['Content-Length'])
  console.log(esRequest.headers['X-Amz-Date'])
  console.log(esRequest.headers['Authorization'])
  console.log(esRequest.path)
  console.log(esRequest.hostname)      
    
}).catch((err) => {
  console.log("error: " + err )
})

```

With the following output. 

```
myelastichsearch.com
application/json
undefined
20201210T142650Z
AWS4-HMAC-SHA256 Credential=ASIxxxxxxxxxxxxxxxxxxxxxxxxxx/eu-central-1/es/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-security-token, Signature=cfa292f649033xxxxxxxxxxxxxxxxxxxxxxxxxxx
/?
myelastichsearch.com
Thu, 10 Dec 2020 14:26:50 GMT | Error Emitted => {"Message":"User: anonymous is not authorized to perform: es:ESHttpGet"}
Thu, 10 Dec 2020 14:26:50 GMT | Error Emitted => {"Message":"User: anonymous is not authorized to perform: es:ESHttpGet"}
```

The header fields used for the requests look better but i wont work and sys "User: anonymous i not authorized". This response look like a HTTP Request without `Authorization`, `X-Amz-Date` and `X-Amz-Security-Token` Header. 

At the moment i have no more ideas. 

If you need more information's let me know! 
Thanks for helping

Bernhard

**Comment by ferronrsmith** [comment]
I saw this issue too, but I didn't bother fixing it. Not that I don't want to, just that I can't. I don't use AWS or have access to an instance so that code is a gray area and is usually updated by contributions.

Essentially is a race condition. The header is signed before the `CredentialProviderChain` has returned. Adding an `await/async` logic will fix this issue, but I'm not willing to do this without proper testing in place

**Comment by ferronrsmith** [comment]
You can take a look at https://github.com/elasticsearch-dump/elasticsearch-dump/pull/752

**Comment by brucke** [comment]
hi, thanks again for your create job. 
We used the image to dump 70 GB of data and it works greate without outage
👍

**Comment by ferronrsmith** [comment]
Awesome 😎, thanks for using elasticdump
