### ISSUE TITLE
[BUG] Docker builds might be broken?

### ISSUE THREAD

**Issue by flyinprogrammer** [elasticsearch-dump/elasticsearch-dump#755]
**Context**

![elasticdump](https://user-images.githubusercontent.com/1844847/101924040-c834c700-3b95-11eb-9adf-21a2b77be501.png)

```bash
❯ docker inspect elasticdump/elasticsearch-dump:v6.58.0 | jq .[0].RepoDigests[0]
"elasticdump/elasticsearch-dump@sha256:82b05a2b93749b19d91f5dffd26f5d5124862e328c19643473c8b6e5c5fbe6cb"

❯ docker inspect elasticdump/elasticsearch-dump:latest | jq .[0].RepoDigests[0]
"elasticdump/elasticsearch-dump@sha256:aa9ddc3e40b839ed116e417f19970343c2af4fd1298e10902d96c73b2c5ca1de"

❯ docker run --rm -it elasticdump/elasticsearch-dump:v6.58.0 --version
6.54.0

❯ docker run --rm -it elasticdump/elasticsearch-dump:latest --version
6.47.0
```

**Describe the bug**

Docker builds seem to be packaging the wrong versions of elasticsearch-dump ?

**Current behavior**

I would have expected both images to have v6.58.0 in it, but both seems to contain older, and surprisingly different versions.
It seems to me like things started going sideways around the v6.48.0 release, as it points to the v6.49.0 release:

```bash
❯ docker run --rm -it elasticdump/elasticsearch-dump:v6.48.0 --version
Unable to find image 'elasticdump/elasticsearch-dump:v6.48.0' locally
v6.48.0: Pulling from elasticdump/elasticsearch-dump
Digest: sha256:67e21b8921288f95e3a7d15df63457cb8403a1d8976b79f7eaf4e4a993c485cb
Status: Downloaded newer image for elasticdump/elasticsearch-dump:v6.48.0
6.49.0
```

**Expected behavior**

Docker image version v6.58.0 contains elasticdump v6.58.0

**Comment by ferronrsmith** [comment]
Not exactly, you have to remember the push the app to npm before building the docker. Sometimes the package takes some time to be reflected in npm and the docker build is very fast. You can use the script with buildargs to build a docker image with a specific version if you like.

**Comment by ferronrsmith** [comment]
Nvm it was a invalid caching issue on DockerHub part. I'll rebuild those images manually and re-push thanks!

**Comment by ferronrsmith** [comment]
Rebuilt all the images.
