### ISSUE TITLE
searchBody  range was seperated

### ISSUE THREAD

**Issue by zhj12388** [elasticsearch-dump/elasticsearch-dump#761]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 6.62.1
- Elasticsearch version: 7.40.0
- Node.js version :v10.23.0
- Full command you are having issue with (with inputs and outputs)
python3 os.sys()执行下面命令
elasticdump --input=http://ip:port/index-2020-12-12 --output=./output/2020-12-12/index-2020-12-12_from03_to04_.json --fsCompress=gzip --fileSize=3gb --limit=300 --concurrency=1 --noRefresh  --searchBody{"query":{"range":{"@timestamp":{"from":"2020-12-12T03:00:00.000Z","to":"2020-12-12T04:00:00.000Z"}}},"stored_fields":["*"],"_source":true}

ps aux  看到如下结果
root     19954  4.8  0.3 814436 241636 ?       Sl   Dec15 137:28 node /opt/elk/elasticdump/node-v10.23.0-linux-x64/bin/elasticdump --input=http://ip:port/index-2020-12-12 --output=./index-2020-12-12_from3_to4_.json --fsCompress=gzip --fileSize=10gb --limit=300 --concurrency=1 --noRefresh --searchBodyquery:{range:{@timestamp:from:2020-12-12T03:00:00.000Z}} --searchBodyquery:{range:{@timestamp:to:2020-12-12T04:00:00.000Z}} --searchBodystored_fields:[*] --searchBody_source:true

 
--searchBody{"query":{"range":{"@timestamp":{"from":"2020-12-12T03:00:00.000Z","to":"2020-12-12T04:00:00.000Z"}}}
被拆分成
--searchBodyquery:{range:{@timestamp:from:2020-12-12T03:00:00.000Z}} --searchBodyquery:{range:{@timestamp:to:2020-12-12T04:00:00.000Z}}

从导出的结果看到有些数据不在"range":{"@timestamp":{"from":"2020-12-12T03:00:00.000Z","to":"2020-12-12T04:00:00.000Z"}}范围内

**Comment by ferronrsmith** [comment]
I'm not sure what the error or problem is. Issues without replication steps will be closed

**Comment by ferronrsmith** [comment]
What do you mean by seperated ?
