### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by nguyensiclc** [elasticsearch-dump/elasticsearch-dump#763]
I got issue when i try restore data  for ES. 
Verison 1: My index have 400 document. Then i dump data to a json file --> ver1.json
After that, i index 1 document then i have 401. I want use file ver1.json for back to version 1. I use command like: 
elasticdump --input=/home/nguyentd/Desktop/dumpdata.json --output=http://localhost:9200/  --delete=true
But still got 401 document. I dont want remove index because it make my ES loss mapping. Can i have any way to empty index before run that command. Sr my english so poor. Thank for help!

**Comment by ferronrsmith** [comment]
````
curl -XPOST 'localhost:9200/index/index_type/_delete_by_query?conflicts=proceed&pretty' -d'
{
    "query": {
        "match_all": {}
    }
}'
```
