### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Abhay22** [elasticsearch-dump/elasticsearch-dump#767]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Using elasticdump currently we are writing data to a csv file in flat json format.
I was thinking if we can leverage this  and also we can have an option to push data to kafka topics.

**Describe alternatives you've considered**
I had to write a separate application to read the csv file generated by graphdump and then push to kafka topic

**Comment by ferronrsmith** [comment]
Actually writing a separate application is unecessary. `elasticdump` supports passing in your own custom `inputTransport` & `outputTransport`.

The aim is to keep the core as lite as possible and well maintained. I'm not interested in adding additional custom transports at this time.

**Comment by Abhay22** [comment]
Hi Ferron,

Is it possible to provide some samples of a custom js file which I need to
pass?

Thanks,
Abhay

**Comment by ferronrsmith** [comment]
```javascript
class template {
  constructor (parent, options) {
    this.options = options
    this.parent = parent
  }

  // accept callback
  // return (error, arr) where arr is an array of objects
  get (limit, offset, callback) {
    const error = null
    const data = []

    callback(error, data)
  }

  // accept arr, callback where writes is a count of objects written
  // return (error, writes)
  set (data, limit, offset, callback) {
    const error = null
    const writes = 0

    callback(error, writes)
  }
}

module.exports = {
  template
}
```

This essentially a transport struct. The project itself is built on these principles so it's itself an example (sample code).

Here is a folder of the supported transports.

https://github.com/elasticsearch-dump/elasticsearch-dump/tree/master/lib/transports
