### ISSUE TITLE
[FEATURE] Nodejs Usage

### ISSUE THREAD

**Issue by kaykhancheckpoint** [elasticsearch-dump/elasticsearch-dump#769]
Does this library only work as cli tool or is it possible to create an implementation that can be run using nodejs

**dump.js**
```
const Elasticdump = require("elasticdump");

const input = "some_http_input";
const output = "some_file.json"
const options = {
    type: "mapping"
}

const elasticDump = new Elasticdump(input, output, options);
elasticDump.dump()

```

```
node dump.js
```

> events.js:306
>     throw err; // Unhandled 'error' event
>     ^
> 
> Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
>   errors: [ '`input` is a required input', '`output` is a required input' ]
> })
>     at ElasticDump.emit (events.js:304:17)
>     at ElasticDump.EventEmitter.emit (domain.js:483:12)
>     at ElasticDump.dump (/home/kay/checkpoint/service-search-sync/node_modules/elasticdump/elasticdump.js:53:12)
>     at Object.<anonymous> (/home/kay/checkpoint/service-search-sync/src/indexes/main.js:11:13)
>     at Module._compile (internal/modules/cjs/loader.js:1137:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
>     at Module.load (internal/modules/cjs/loader.js:985:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47 {
>   code: 'ERR_UNHANDLED_ERROR',
>   context: {
>     errors: [ '`input` is a required input', '`output` is a required input' ]
>   }
> }

**Comment by ferronrsmith** [comment]
That's already possible.

```javascript
const Elasticdump = require("elasticdump");

const options = {
    type: "mapping",
    input: "some_http_input",
    output: "some_file.json"
}

const elasticDump = new Elasticdump(options.input, options.output, options);
elasticDump.dump()
```

The validation is done using the options. I'll update in the next release, but for now this should be fine.
