### ISSUE TITLE
[FEATURE] Speed and Update

### ISSUE THREAD

**Issue by Mariano215** [elasticsearch-dump/elasticsearch-dump#770]
**Is your feature request related to a problem? Please describe.**
Transfer from one elastic search to another.

1. I have an index with 10,950,338 records.  Elasticdump works GREAT but takes days. Is there a way to speed this up?
2. Is there a way to run this where it only updates new or changed items from one elasticsearch to another?

**Describe the solution you'd like**
1. Speed improvements or method.
2. Only transfer updated or changed records.

**Describe alternatives you've considered**
Logstash but does not work nearly as well.

**Give some examples of implementations**
5.6 Elasticsearch pulls data from source - bound by v5.6.
I use elasticdump to transfer from v5.6 ES to v7.1 ES.

**Additional context**
Great utility!

**Comment by ferronrsmith** [comment]
That's hard to say, because I don't know the commands you're running. The performance elasticdump is directly related to the Elasticsearch. 

Just at first glance ...

1. You can increase the esdump'size'
1. Parallelise the dumping of records
