### ISSUE TITLE
[BUG] ElasticDump deleted data from the original (source) index

### ISSUE THREAD

**Issue by herangstl** [elasticsearch-dump/elasticsearch-dump#774]
**Context**

- ElasticDump version 6.66.1

- Elasticsearch version 6.8.11

- Node.js version v10.19.0

**Full command you are having issue with (with inputs and outputs)**

`elasticdump --input=http://10.206.248.211:9200/graylog_2361 --output=http://10.206.249.32:9200/graylog_2361 --limit=1000 --timeout=3600000 --ignore-errors --type=analyzer`

`elasticdump --input=http://10.206.248.211:9200/graylog_2361 --output=http://10.206.249.32:9200/graylog_2361 --limit=1000 --timeout=3600000 --ignore-errors --type=mapping`

`elasticdump --input=http://10.206.248.211:9200/graylog_2361 --output=http://10.206.249.32:9200/graylog_2361 --limit=1000 --timeout=3600000 --ignore-errors --type=data`

**Describe the bug**
After running this commands, data from my input index has been MOVED to the output index (it was deleted in the input index). After that the input index (and the whole cluster) turned red.

```
red    open   graylog_2361       m2i2w5XlTfOqFBA2SXCyHg   6   0   13343248            0      6.7gb          6.7gb
green  open   graylog_2362       n6PrHvnjQQyLMGQGAbn3KQ   6   0   20014106            0     10.6gb         10.6gb
green  open   graylog_2363       9BGzGbqqSjC9FUryzIT2Wg   6   0   20009457            0     10.5gb         10.5gb
green  open   graylog_2364       VQ53oVmkRVusVYhgqHDF9A   6   0   20011084            0     10.7gb         10.7gb
```

Each index holds around 20 million documents. After running elasticdump for some time index graylog_2361 is down to 13 million documents - and turned red.

**Expected behavior**
Data in the input index stays unchanged and is not deleted.

**Comment by ferronrsmith** [comment]
That sounds like a shard allocation/cluster issue. This doesn't really have anything to do with elasticdump 


```
green
All shards are assigned.
 yellow
All primary shards are assigned, but one or more replica shards are unassigned. If a node in the cluster fails, some data could be unavailable until that node is repaired.
 red
One or more primary shards are unassigned, so some data is unavailable. This can occur briefly during cluster startup as primary shards are assigned.
```

**Comment by ferronrsmith** [comment]
The app doesn't delete data unless a specific flag is passed.

**Comment by herangstl** [comment]
The behavior is reproducible:
1) The Index "health" is green, "docs.count" is around 20 million
2) I start elasticdump 
3) The Index "health" turns red, the "docs.count" value steadily decreases

**Comment by ferronrsmith** [comment]
That doesn't mean it's reproducible. Elasticdump cannot and will under any circumstances remove data from an index unless the `delete` flag is passed. There are tests for this case.

What it sounds like is your index is becoming unstable due to some other factors. I don't know because I don't have enough information to reproduce the case. 

On my end I created an index with 40M records, transferred it to another server without issue.
