### ISSUE TITLE
scroll_id issue

### ISSUE THREAD

**Issue by feiyi1019** [elasticsearch-dump/elasticsearch-dump#775]
Dear Sir,
I  see the scrollid option is supported.
--scrollId
                    The last scroll Id returned from elasticsearch. 
                    This will allow dumps to be resumed used the last scroll Id &
                    `scrollTime` has not expired.

problem is how to get the lastest scrollid by elasticsearch-dump and i tested with scrollid. 
It didn't resume but restart from the begining.

Looks for your earliest help. thank you!

**Comment by ferronrsmith** [comment]
`lastScrollId` is shown when the debug mode is on. Then you can resume. 

`and i tested with scrollid. It didn't resume but restart from the begining.`

Did the `scrollId` you used come from endpoint or es-dump ?

Can show the commands used etc ? Thanks.

**Comment by feiyi1019** [comment]
elasticdump --input=http://loalhost:9200/report/_doc --output=/data/v1.json --limit=500 --fileSize=10mb --type=data --scrolltime=10m --debug=true
elasticdump --input=http://loalhost:9200/report/_doc --output=/data/v2.json --limit=500 --fileSize=10mb --type=data --scrolltime=10m --debug=true --scrollid=DXF1ZXJ5QW5kRmV0Y2gBAAAAAAMRndQWWndSd3gzeDNTSm1LelJDclliODg0QQ==

i checked with scrollid come from es-dump. still not working.

**Comment by ferronrsmith** [comment]
Retested this and couldn't replicate the issue you're seeing. It works for me.

```
# rec 1
elasticdump --input=http://localhost:9200/icons~rec
--output=/s.json
--type=data

--input=http://localhost:9200/icons~rec
--output=/s1.json
--type=data
--scrollId=DnF1ZXJ5VGhlbkZldGNoAgAAAAAAAAADFm5XdHFsQ1BjUm5pMDJ6c19hUjFKMkEAAAAAAAAABBZuV3RxbENQY1JuaTAyenNfYVIxSjJB
```

**Comment by feiyi1019** [comment]
THANK YOU FOR THE QUICK REPLY
