### ISSUE TITLE
importing mappings is not creating the index

### ISSUE THREAD

**Issue by renegat59** [elasticsearch-dump/elasticsearch-dump#777]
I wonder if I do something wrong or there is some issue with the tool. I make dump like this:
```
elasticdump --input=./mapping.json --output=http://host.docker.internal:9200/ --type=mapping
```

The `mapping.json` contains all the mappings correctly. I drop all the indexes and run:

```
elasticdump --input=./mapping.json --output=http://host.docker.internal:9200 --type=mapping

Wed, 17 Mar 2021 16:59:23 GMT | starting dump
Wed, 17 Mar 2021 16:59:23 GMT | got 1 objects from source file (offset: 0)
Wed, 17 Mar 2021 16:59:23 GMT | sent 1 objects to destination elasticsearch, wrote 19
Wed, 17 Mar 2021 16:59:23 GMT | got 0 objects from source file (offset: 1)
Wed, 17 Mar 2021 16:59:23 GMT | Total Writes: 19
Wed, 17 Mar 2021 16:59:23 GMT | dump complete
```

Then I run `curl -XGET 'http://host.docker.internal:9200/_cat/indices' -H 'Content-Type: application/json'` and the output:

```
green open .kibana_1            wozAmAbATESCzq3mvuHRdg 1 0 2 0  7.6kb  7.6kb
green open .kibana_task_manager lvR83fbHT3muvt4vwSjzXQ 1 0 2 0 12.5kb 12.5kb
```

It's missing my indexes.

When I import data the indexes are being created but the mappings are incorrect (the default Elasticsearch mappings are created). When I import mappings after of course it doesn't work because mapping can't be changed without reindex.

Thank you for help in advance

**Comment by ferronrsmith** [comment]
Can you share the mapping data ?
