### ISSUE TITLE
[FEATURE] Specify a file in searchBody argument

### ISSUE THREAD

**Issue by michelcaradec** [elasticsearch-dump/elasticsearch-dump#780]
There can be some business cases where the search query (specified in the `--searchBody` argument) can be very long (hundreds of kilobytes).
In such situations, it is not possible to use it, as the command line is limited to a certain size (even using `xargs`).

It would be nice to be able to specify the search query by using a file reference (such as in cURL) in the following way: `--searchBody @filename.txt`.

This would allow to reduce the size of the command, and to facilitate the maintenance by storing the search query in a separate file.

Thank you for this nice tool.

**Comment by ferronrsmith** [comment]
Sounds like a good idea 👍🏾. I'll implement it
