### ISSUE TITLE
[BUG] Missing indexes on export

### ISSUE THREAD

**Issue by shawnz** [elasticsearch-dump/elasticsearch-dump#781]
**Context**

- ElasticDump version: 6.68.0
- Elasticsearch version: 7.7.0
- Node.js version *(note that nodejs v10+ is required for this tool)*: v14.16.0
- Full command you are having issue with (with inputs and outputs):

    `NODE_EXTRA_CA_CERTS=../prod-root-ca.pem ~/elasticsearch-dump/bin/multielasticdump --input="https://redacted" --output="." --match="^filebeat-.*" --parallel=12 --limit=10000 --fsCompress | tee multielasticdump.log`

- A data-set you can share publicly which reproduces the problem: Can't repro outside of existing installation

**Describe the bug**

When exporting, not all the indexes are exported. Multielasticdump does not print the final "dumping all complete" message. This problem has only started happening for me since the beginning of this year. My last backup taken in Nov 2020 doesn't have the issue present, but now all backups I take on either our prod or test environment are exhibiting the problem. I am not sure what changed in that time besides OS upgrades. Please note I am running in WSL1 on Windows 20H2 (previously WSL worked well for this).

Logs: [multielasticdump_clean.log](https://github.com/elasticsearch-dump/elasticsearch-dump/files/6278496/multielasticdump_clean.log) Note I added a print statement here to show all the indexes. Otherwise this is produced by unchanged 6.68.0 source code

**Comment by ferronrsmith** [comment]
I am not seeing anything in the logs provided to say what could be causing an issue. My suggestion is to add `ignoreChildError` and see what happens. Seems like your process prematurely ending without outputting anything.

**Comment by shawnz** [comment]
Thank you for the suggestions. I am trying it with "ignoreChildError" now. Unfortunately it takes several hours to run on this data set. Previously I was using an older version which was also exhibiting the issue, so I tried upgrading to 6.68.0, but unfortunately I lost track of what the previous version number was. I will try the version from before November once this is completed

**Comment by shawnz** [comment]
Thank you again. ignoreChildError did work to allow me to get all indexes by running it multiple times. I then used `zcat | wc -l` and compared with the document count to find incomplete files and redownloaded those. Everything completed successfully although there were some transient network issues. Perhaps that is what caused the initial problem.

In total the dump took around 50 hours so I am thinking that perhaps this amount of data has become too big to handle efficiently with elasticdump. I will investigate if elasticsearch snapshots are better for this use case.
