### ISSUE TITLE
[BUG] maaping Is created dynamically when --type=data

### ISSUE THREAD

**Issue by zhupengfeivip** [elasticsearch-dump/elasticsearch-dump#782]
**Context**

- ElasticDump version ：6.68.0
- Elasticsearch version：  5.6.4
- Node.js version： v12.16.1
- Full command you are having issue with (with inputs and outputs)
docker run --rm -it docker.io/taskrabbit/elasticsearch-dump --input=http://172.17.0.1:9200/object002 --output=http://172.17.0.1:9200/object003 --limit=100 --size=200 --type=data

**Describe the bug**
Maaping is automatically created when moving from one index to another. For the new index I have set the mapping to be manually created.

```bash
root@test:~# curl --request GET --url http://127.0.0.1:9200/object003/_mapping
{"object003":{"mappings":{"pretty":{"dynamic":"strict","properties":{"app":{"type":"keyword"},"itemId":{"type":"keyword"},"message":{"type":"text"}}}}}}
```

**To Reproduce**
1. create index

```bash
curl --request PUT --url http://127.0.0.1:9200/object003
```

2. set mapping
```bash
curl --request PUT --url http://127.0.0.1:9200/object003/_mapping/pretty --header 'content-type: application/json' --data '{"pretty": {"dynamic":      "strict","properties": {"itemId": {"type":  "keyword"},"message": {"type":  "text"},"app": {"type":  "keyword"}}}}'
```

3. move data
```bash
docker run --rm -it docker.io/taskrabbit/elasticsearch-dump --input=http://172.17.0.1:9200/object002 --output=http://172.17.0.1:9200/object003 --limit=100 --size=200 --type=data
```

**Current behavior**
Mapping is set automatically

**Expected behavior**
Mapping does not change. When Maping is inconsistent, only mapping in the new index will be imported, or an error will be reported.

**Screenshots**

**Additional context**

**Comment by ferronrsmith** [comment]
This isn't an esdump issue. This is an elasticsearch issue. You need to disable dynamic mapping


```json
{
	"object003": {
		"mappings": {
			"pretty": {
				"dynamic": "strict",
				"properties": {
					"app": {
						"type": "keyword"
					},
					"itemId": {
						"type": "keyword"
					},
					"message": {
						"type": "text"
					}
				}
			}
		}
	}
}
```

==> (Invalid mapping)

Should be

```json
{
	"object003": {
		"mappings": {
			"dynamic": "strict",
			"properties": {
				"app": {
					"type": "keyword"
				},
				"itemId": {
					"type": "keyword"
				},
				"message": {
					"type": "text"
				}
			}
		}

	}
}
```

**Comment by zhupengfeivip** [comment]
Thank you very much. That's true.

I just did it again and found the reason.

When I set mpping, I wrongly set the mapping for the pretty type due to a writing error.
When importing data, another type is imported, and the mapping for the other type is automatically created by default.
After correcting the writing error, everything was normal.
Thanks again!
