### ISSUE TITLE
[BUG] Documented way of dumping to another ES instance omits certain settings

### ISSUE THREAD

**Issue by thelink2012** [elasticsearch-dump/elasticsearch-dump#785]
**Context**

- ElasticDump version: 6.68.1
- Elasticsearch version: 7.9.0
- Node.js version: v14.16.1
- Full command you are having issue with (with inputs and outputs): See below
- A data-set you can share publicly which reproduces the problem: Not necessary

**Describe the bug**

Dumping a ES index from one cluster to a staging instance as specified in the documentation:

```
# Copy an index from production to staging with analyzer and mapping:
elasticdump \
  --input=http://production.es.com:9200/my_index \
  --output=http://staging.es.com:9200/my_index \
  --type=analyzer
elasticdump \
  --input=http://production.es.com:9200/my_index \
  --output=http://staging.es.com:9200/my_index \
  --type=mapping
elasticdump \
  --input=http://production.es.com:9200/my_index \
  --output=http://staging.es.com:9200/my_index \
  --type=data
  ```

Doesn't preserve some settings and mappings. In my particular case,  `index.store` and `index.sort` from `_settings` are missing as well as `mappings._source` from  `_mappings`.

**To Reproduce**

1. `PUT http://localhost:9200/elasticsearchdump-bug-report` the JSON \[1\].
2. Dump `analyzer` and `mapping` to another index as specified in the documentation i.e. \[2\]

**Current behavior**

 `GET http://localhost:9200/elasticsearchdump-bug-report-2` and notice its missing the `index.store`, `index.sort` and `mappings._source` from the original index \[1\].

**Expected behavior**

 `GET http://localhost:9200/elasticsearchdump-bug-report-2` contains all important attributes from the source such as `index.store`, `index.sort` and `mappings._source`.

**Additional context**

It seems like this is caused by passing `settings` data and `mapping` data in different passes. When I dump these two into a JSON, merge the JSON, and then `PUT` that on the destination, everything goes as expected.

Also, removing the `mappings.dynamic` line preserves `mappings._source` in the destination. 

\[1\]:

```
{
  "settings": {
    "index": {
      "store.type": "mmapfs",
      "sort.field": "date",
      "sort.order": "desc",
      "analysis": {
        "analyzer": {
          "default": {
            "filter": ["lowercase", "asciifolding"],
            "tokenizer": "standard"
          }
        }
      }
    }
  },
  "mappings": {
      "dynamic": "strict",
      "_source": {
            "excludes": [
                  "example1",
                  "example2"
            ]
    },
    "properties": {
      "all": {
        "type": "text",
        "analyzer": "default"
      },
      "date": {
            "type": "date"
      }
    }
  }
}
```

\[2\]:
```
elasticdump \
  --input=http://localhost:9200/elasticsearchdump-bug-report \
  --output=http://localhost:9200/elasticsearchdump-bug-report-2 \
  --type=analyzer
elasticdump \
  --input=http://localhost:9200/elasticsearchdump-bug-report \
  --output=http://localhost:9200/elasticsearchdump-bug-report-2 \
  --type=mapping
  ```

**Comment by ferronrsmith** [comment]
Dump the settings if you want everything

**Comment by ferronrsmith** [comment]
As I said in a previous issue. `type=analyzer` & `type=settings` both produce the same JSON output, where they differ is on import.
