### ISSUE TITLE
[FEATURE] Input and output headers

### ISSUE THREAD

**Issue by akovov** [elasticsearch-dump/elasticsearch-dump#787]
When using elasticsearch-dump when both input and output are Elastics, there is a need to send in headers as host input and output headers. with current configuration capabilities it is possible to specify only one.

**Solution I like**
current headers options leave and add two others input-headers and output headers, and if second one specified, then use values for them, and combine with general ones from headers if it is configured

**Alternate Solution**
is to use custom transports with the following parameters, but its to complex for such small need
  --inputTransport
  --outputTransport

**Example of usage**
    elasticdump \
    --input="https://$INPUT_USER:$INPUT_PASS@localhost:8000/$ES_INDEX_NAME" \
    --input-headers "{\"Host\": \"$INPUT_HOST\"}" \
    --output="https://$OUTPUT_USER:$OUTPUT_PASS@localhost:8001/$ES_INDEX_NAME" \
    --output-headers "{\"Host\": \"$OUTPUT_HOST\"}" \
    --limit="10000"

**Comment by ferronrsmith** [comment]
feel free to submit a PR

**Comment by akovov** [comment]
I can, but i never did that before, and also I'm not so deep in knowledge with JavaScript to perform any changes

**Comment by ferronrsmith** [comment]
Can you explain to me a bit more why this feature is needed. I just don't see the value, so I'm having a very hard time adding it. I'm open to listening.

**Comment by akovov** [comment]
Yes sure. I have 2 setups in CloudFoundry, and have a need of migrating 180 Gb of indices between them.
With current options it is possible specify only one common header, what causes impossible to use direct Elastic-2-Elastic connection, which i hope should be very fast.
Thus currently it's a boring task with intermediate step by downloading everything to local machine, and then pushing to 2nd Elastic. And this is because during connection both require to get correct elastic host in headers to check against certificate.

**Comment by ferronrsmith** [comment]
Got ya
