### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by akovov** [elasticsearch-dump/elasticsearch-dump#789]
**Context**
Tried to use new  input/output headers, but it failed
- ElasticDump version - 6.69.0
- Elasticsearch version - 7.5.2
- Node.js version - 16.0.0
- Full command:
`elasticdump \
    --input="https://$INPUT_USER:$INPUT_PASS@localhost:8000/$ES_INDEX" \
	--input-headers  "{\"Host\": \"$INPUT_HOST\"}" \
    --output="https://$OUTPUT_USER:$OUTPUT_PASS@localhost:8001/$ES_INDEX" \
	--output-headers "{\"Host\": \"$OUTPUT_HOST\"}" \
	--limit="10000" \`

**Description**
Dump ended with error (get phase) => Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames, same as when not correct he

**To Reproduce**
2 setups of elastic search
run the command above with substituted values

**Current behavior**
getting error that provided hostname not as expected, while when using elastic-file/file to elastic with parameter Headers works well

**Expected behavior**
Expected that process will go with reading 10k records and writing them to another elastic

**Error record**
`Thu, 22 Apr 2021 12:50:01 GMT | starting dump
Thu, 22 Apr 2021 12:50:01 GMT | Error Emitted => Hostname/IP does not match certificate's altnames: Host: localhost. is not in the cert's altnames: DNS:*.xxxxx.com, DNS:xxxxx.com
Thu, 22 Apr 2021 12:50:01 GMT | Error Emitted => Hostname/IP does not match certificate's altnames: Host: localhost. is not in the cert's altnames: DNS:*.xxxxx.com, DNS:xxxxx.com
Thu, 22 Apr 2021 12:50:01 GMT | Total Writes: 0
Thu, 22 Apr 2021 12:50:01 GMT | dump ended with error (get phase) => Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: localhost. is not in the cert's altnames: DNS:*.xxxxx.com, DNS:xxxx.com`

**Comment by ferronrsmith** [comment]
Check to ensure that your env_vars are getting resolved. No reason you should have any errors

**Comment by ferronrsmith** [comment]
Added a new release, this will allow input/output headers to be parseable
