### ISSUE TITLE
Export and import ILM policies

### ISSUE THREAD

**Issue by archfz** [elasticsearch-dump/elasticsearch-dump#792]
**Is your feature request related to a problem? Please describe.**
ILM (index lifecycle management policies / policy) are not exported.

**Describe the solution you'd like**
Ability to export / import ILM.

**Describe alternatives you've considered**
-

**Give some examples of implementations**
-

**Additional context**
-

**Comment by archfz** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/index-lifecycle-management-api.html

**Comment by ferronrsmith** [comment]
that's xpack. You can create your own transport for this.

**Comment by archfz** [comment]
Do you mean by xpackl that it's payed feature? As I see the ILM is free. So this tool should not support it? 
Own transport meaning custom code I would assume.

**Comment by ferronrsmith** [comment]
It's only been available since ES 6.6. I can add it, that's fine.

**Comment by ferronrsmith** [comment]
Ok feature added, I haven't tested it yet, but it should be working

**Comment by archfz** [comment]
How could I try it?

**Comment by ferronrsmith** [comment]
No worries I'll merge in a few so you can test

**Comment by ferronrsmith** [comment]
released in `v6.70.0`

**Comment by archfz** [comment]
I get error: `'getPolicies()' is missing!` . Also it would be nice if `multielasticdump` also supported this.
With rollover functionality it just does not working since index names always change (get incremented) thus cannot even hardcode which indexes ilm's to export.

Example command I'd need to run (observe the index name):
```bash
multielasticdump --input http://localhost:9200/filebeat-7.11.2-2021.04.26-000004 --output /usr/share/elasticsearch/saved_objects_exports/filebeat.policy.json
```

**Comment by ferronrsmith** [comment]
I get that part about `multielasticdump`. I am asking you to test the feature before doing all that work.

**Comment by archfz** [comment]
In any case, as stated before, tested and I get that error.

**Comment by ferronrsmith** [comment]
I just made a new release. Usually persons would test the branch directly to avoid releasing stuff not fully baked.

**Comment by archfz** [comment]
Give me a diff with fix, and I will modify the module under node_modules, instead of doing releases. 

By rollover I mean https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-rollover.html

**Comment by archfz** [comment]
Looking at your changes in the commit actually I think it would work with hardcoded version as well, since the parameter is not the index this time, but the policy name.

**Comment by archfz** [comment]
Export working, data seems correct.
Import not working:
```bash
elasticdump --output http://elastic:$ELASTIC_PASSWORD@localhost:9200/filebeat --input /usr/share/elasticsearch/saved_objects_exports/filebeat.policy.json --type=policy
```
I get:
```
Mon, 03 May 2021 16:46:29 GMT | starting dump
Mon, 03 May 2021 16:46:29 GMT | got 1 objects from source file (offset: 0)
Mon, 03 May 2021 16:46:29 GMT | Error Emitted => {"error":{"root_cause":[{"type":"x_content_parse_exception","reason":"[1:2] [put_lifecycle_request] unknown field [version]"}],"type":"x_content_parse_exception","reason":"[1:2] [put_lifecycle_request] unknown field [version]"},"status":400}
Mon, 03 May 2021 16:46:29 GMT | Error Emitted => {"error":{"root_cause":[{"type":"x_content_parse_exception","reason":"[1:2] [put_lifecycle_request] unknown field [version]"}],"type":"x_content_parse_exception","reason":"[1:2] [put_lifecycle_request] unknown field [version]"},"status":400}
Mon, 03 May 2021 16:46:29 GMT | Total Writes: 0
Mon, 03 May 2021 16:46:29 GMT | dump ended with error (get phase) => BAD_REQUEST: {"error":{"root_cause":[{"type":"x_content_parse_exception","reason":"[1:2] [put_lifecycle_request] unknown field [version]"}],"type":"x_content_parse_exception","reason":"[1:2] [put_lifecycle_request] unknown field [version]"},"status":400
```

**Comment by archfz** [comment]
Example export:

```json
"{\"filebeat\":{\"version\":3,\"modified_date\":\"2021-04-11T16:41:49.582Z\",\"policy\":{\"phases\":{\"hot\":{\"min_age\":\"0ms\",\"actions\":{\"rollover\":{\"max_size\":\"500mb\",\"max_age\":\"5d\"},\"set_priority\":{\"priority\":100}}},\"delete\":{\"min_age\":\"25d\",\"actions\":{\"delete\":{\"delete_searchable_snapshot\":true}}}}}}}"
```

**Comment by ferronrsmith** [comment]
What's the import url used ?

**Comment by archfz** [comment]
Tried both http://elastic:$ELASTIC_PASSWORD@localhost:9200/filebeat and http://elastic:$ELASTIC_PASSWORD@localhost:9200/ , same results

**Comment by ferronrsmith** [comment]
The diff is here : https://github.com/elasticsearch-dump/elasticsearch-dump/pull/794/files
(The input needed to be sanitized before pushing)

**Comment by ferronrsmith** [comment]
Once it's working i'll add the `multielasticdump` support after validation

**Comment by archfz** [comment]
Confirmed it's working.

Now one thing I would want to note for multielasticdump. While setting up these ILM policies, I have found that in order to apply an update to a policy on an index, one would need to recreate the index, so I think it would be wise to first import the policies and after that the indexes.

**Comment by ferronrsmith** [comment]
👍🏾

**Comment by ferronrsmith** [comment]
added `multielasticdump` support

**Comment by archfz** [comment]
Doesn't work.

```
Tue, 04 May 2021 17:08:33 GMT | dumping http://elastic:UTJbppp4a5HcAKX8bBzeTAY7@localhost:9200 to /usr/share/elasticsearch/saved_objects_exports/filebeat-7.11.2-2021.04.11-000001.policy.json
Tue, 04 May 2021 17:08:34 GMT | dumping http://elastic:UTJbppp4a5HcAKX8bBzeTAY7@localhost:9200 to /usr/share/elasticsearch/saved_objects_exports/.async-search.policy.json
Tue, 04 May 2021 17:08:34 GMT | starting dump
Tue, 04 May 2021 17:08:34 GMT | Error Emitted => {"error":{"root_cause":[{"type":"resource_not_found_exception","reason":"Lifecycle policy not found: *"}],"type":"resource_not_found_exception","reason":"Lifecycle policy not found: *"},"status":404}
```

Looking at your code you will have to make some modifications. The input will have to be the policy name, but currently is options.input, which in case of multidump it's actually just the base url. I think you need to call the [`GET _ilm/policy`](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-get-lifecycle.html) to discover what policy names there are, Object.keys on it's return value. Example response:

```json
{
  "ilm-history-ilm-policy" : {
    "version" : 1,
    "modified_date" : "2021-04-03T07:36:11.604Z",
    "policy" : {
      "phases" : {
        "hot" : {
          "min_age" : "0ms",
          "actions" : {
            "rollover" : {
              "max_size" : "50gb",
              "max_age" : "30d"
            }
          }
        },
        "delete" : {
          "min_age" : "90d",
          "actions" : {
            "delete" : {
              "delete_searchable_snapshot" : true
            }
          }
        }
      }
    }
  },
  "heartbeat" : {
    "version" : 12,
    "modified_date" : "2021-04-11T16:45:07.735Z",
    "policy" : {
      "phases" : {
        "hot" : {
          "min_age" : "0ms",
          "actions" : {
            "rollover" : {
              "max_size" : "500mb",
              "max_age" : "5d"
            },
            "set_priority" : {
              "priority" : 100
            }
          }
        },
        "delete" : {
          "min_age" : "25d",
          "actions" : {
            "delete" : {
              "delete_searchable_snapshot" : true
            }
          }
        }
      }
    }
  }
}
```

And with this call the forks. But to be honest I think it would work much faster if this API is called once and processed into the multiple files, just to support the fork import since the PUT api only accepts them one by one.

**Comment by ferronrsmith** [comment]
Yea it doesn't support wildcards. I already updated it.

**Comment by ferronrsmith** [comment]
I've actually removed `multielasticdump` support. It's not necessary. 

```bash
# dumps a specific policy
elasticdump --input http://localhost:9200/filebeat --output filebeat.policy.json --type=policy

# dumps all policy
elasticdump --input http://localhost:9200 --output policies.json --type=policy


# restores all policy
elasticdump --output http://localhost:9200 --input policies.json --type=policy
```

**Comment by archfz** [comment]
Sorry for taking this long on testing.

Here are the last two things you need to do to make this work:
1. `        url: `${this.base.host}/_ilm/policy/${this.base.index || '*'}`,` remove the star here
2. The exported fields `version` and `modified_date` need to be purged from the policies. These fields cannot be imported and it fails if present in request.

Otherwise tested with the above changes and it works.

**Comment by ferronrsmith** [comment]
1. Was already fixed and resolved.
2. Only the policy is imported, but these fields are kept since they are good filter identifiers (It wouldn't make sense to remove them)

**Comment by archfz** [comment]
If the version and modified date is not removed before put then the import fails. It can remain in the output but when used as input it needs to be removed before passing to elastic for put.

**Comment by ferronrsmith** [comment]
i don't know what version you're using, but in the version released. It's the only thing that's passed to the ILM endpoint

**Comment by ferronrsmith** [comment]
```patch
From 2124112db07020a570b62293e6f892ed82c0c232 Mon Sep 17 00:00:00 2001
From: ferron <ferronrsmith@gmail.com>
Date: Mon, 3 May 2021 13:30:18 -0400
Subject: [PATCH] added fix for multi-get policy

---
 README.md                        | 2 +-
 lib/help.txt                     | 2 +-
 lib/transports/__es__/_policy.js | 4 ++--
 3 files changed, 4 insertions(+), 4 deletions(-)

diff --git a/README.md b/README.md
index e6d1961b..88249893 100644
--- a/README.md
+++ b/README.md
@@ -311,7 +311,7 @@ Usage: elasticdump --input SOURCE --output DESTINATION [OPTIONS]
                     (default: false)
 --type
                     What are we exporting?
-                    (default: data, options: [settings, analyzer, data, mapping, alias, template, component_template, index_template])
+                    (default: data, options: [settings, analyzer, data, mapping, policy, alias, template, component_template, index_template])
 --filterSystemTemplates
                     Whether to remove metrics-*-* and logs-*-* system templates 
                     (default: true])
diff --git a/lib/help.txt b/lib/help.txt
index a5ec3908..0b5db918 100644
--- a/lib/help.txt
+++ b/lib/help.txt
@@ -59,7 +59,7 @@ Usage: elasticdump --input SOURCE --output DESTINATION [OPTIONS]
 
 --type
                     What are we exporting?
-                    (default: data, options: [settings, analyzer, data, mapping, alias, template, component_template, index_template])
+                    (default: data, options: [settings, analyzer, data, mapping, policy, alias, template, component_template, index_template])
 --filterSystemTemplates
                     Whether to remove metrics-*-* and logs-*-* system templates 
                     (default: true])
diff --git a/lib/transports/__es__/_policy.js b/lib/transports/__es__/_policy.js
index eb8999ca..0f34a38d 100644
--- a/lib/transports/__es__/_policy.js
+++ b/lib/transports/__es__/_policy.js
@@ -8,7 +8,7 @@ class Policy {
       callback(null, [])
     } else {
       const esRequest = {
-        url: `${this.base.host}/_ilm/policy/${this.base.index || '*'}`,
+        url: `${this.base.host}/_ilm/policy/${this.base.index || ''}`,
         method: 'GET'
       }
       aws4signer(esRequest, this.parent).then(() => {
@@ -43,7 +43,7 @@ class Policy {
       const esRequest = {
         url: `${this.base.host}/_ilm/policy/${policyName}`,
         method: 'PUT',
-        body: jsonParser.stringify(_policy)
+        body: jsonParser.stringify({ policy: _policy.policy })
       }
       aws4signer(esRequest, this.parent).then(() => {
         this.baseRequest(esRequest, (err, response) => {


```

**Comment by archfz** [comment]
Yeah all good. Didn't have the latest changes. Thank you for the feature.
