### ISSUE TITLE
[BUG] 'does not exists' when attempting to dump to S3 via --output

### ISSUE THREAD

**Issue by imdadahad** [elasticsearch-dump/elasticsearch-dump#795]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version
elasticdump@6.33.4

- Elasticsearch version
7.9

- Node.js version *(note that nodejs v10+ is required for this tool)*
Node.js 14.x

- Full command you are having issue with (with inputs and outputs)

```
./node_modules/elasticdump/bin/multielasticdump \
  --direction=dump \
  --input=http://${vpc_url} \
  --output 's3://${bucket_name}'
```

- A data-set you can share publicly which reproduces the problem

N/A

**Describe the bug**

The following message appears: "does not exists" when setting the `--output` parameter for the command to an S3 bucket. Here is the stacktrace:

```
Wed, 05 May 2021 11:26:09 GMT | We are performing : dump
Wed, 05 May 2021 11:26:09 GMT | options: {"debug":true,"parallel":8,"match":"^.*$","input":"http://localhost:9200","output":"s3://sc-es-backups","scrollId":null,"scrollTime":"10m","timeout":null,"limit":100,"offset":0,"direction":"dump","support-big-int":false,"big-int-fields":"","ignoreAnalyzer":true,"ignoreChildError":false,"ignoreData":false,"ignoreMapping":false,"ignoreSettings":false,"ignoreTemplate":false,"ignoreAlias":true,"ignoreType":[],"includeType":null,"interval":1000,"prefix":"","suffix":"","transform":null,"headers":null,"searchBody":null,"searchWithTemplate":null,"cert":null,"key":null,"pass":null,"ca":null,"tlsAuth":false,"input-cert":null,"input-key":null,"input-pass":null,"input-ca":null,"output-cert":null,"output-key":null,"output-pass":null,"output-ca":null,"httpAuthFile":null,"concurrency":1,"carryoverConcurrencyCount":true,"intervalCap":5,"concurrencyInterval":5000,"overwrite":false,"fsCompress":false,"quiet":false}
Directory --output : `s3://sc-es-backups` does not exists
```

**Additional context**

My current IAM profile has permissions to access this bucket. This is why I have not explicitly set values for `s3AccessKeyId` or `s3SecretAccessKey` as I believe these are implied from the role?

**Comment by ferronrsmith** [comment]
The assumption here is that the credentials are located in `~/.aws/credentials` (already authenticated with aws cli). s3 currently doesn't support credentials/credentials provider authention type

**Comment by imdadahad** [comment]
Is this required even when the credentials are passed explicitly.

As an example, attempting to run the following command yields the same error:

```
                    multielasticdump \
                    --direction=load \
                    --input "s3://${bucket_name}" \
                    --s3AccessKeyId "..." \
                    --s3SecretAccessKey "..." \
                    --output=http://elasticsearch:9200 
```

**Comment by ferronrsmith** [comment]
s3 params aren't supported in `multielasticdump`. have u tried just using elasticdump ?
