### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rohit18-desai** [elasticsearch-dump/elasticsearch-dump#798]
I am trying to copy data form AWS-ES to my local machine ES using ElasticDump.

- Elasticsearch version- 7.12.1
- Node.js version - 12
- Full command-
----------------------------------------------------
elasticdump \
  --input=https://url....... \
  --output=http://localhost:9200/my-index1 \
  --type=mapping
--------------------------------------------------------------
getting error like --
dump ended with error (get phase) => FORBIDDEN: {"Message":"User: anonymous is not authorized to perform: es:ESHttpGet"}

Please Give me suggestion of this

**Comment by ferronrsmith** [comment]
Have you tried passing the credentials in ? Check the docs on how to authenticate AWS/Basic Auth
