### ISSUE TITLE
Do shards or replicas matter when doing dump?

### ISSUE THREAD

**Issue by behrygood1982** [elasticsearch-dump/elasticsearch-dump#800]
Hello,

Our prod cluster is setup to have on index have 5 shards and 1 replica.  When dumping the settings of an index to our non-prod environment is this going to be an issue or will it ever be an issue with other replica and shard counts?

**Comment by ferronrsmith** [comment]
Depends on if there are enough nodes for replica/shard. Ideally it would just be [yellow](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html) state
