### ISSUE TITLE
METHOD_NOT_ALLOWED: {"error":"Incorrect HTTP method for uri [/] and method [PUT], allowed: [HEAD, GET, DELETE]","status":405}

### ISSUE THREAD

**Issue by indapublic** [elasticsearch-dump/elasticsearch-dump#803]
> ElasticDump version

6.72.0

> Elasticsearch version

7.1.1

> Node.js version *(note that nodejs v10+ is required for this tool)*

v14.16.1

> Full command you are having issue with (with inputs and outputs)

./node_modules/elasticdump/bin/elasticdump --input=http://elastic:password@staging-url:9200 --output=http://elastic:changeme@127.0.0.1:9200 --type=analyzer

> Log
```
Wed, 16 Jun 2021 12:13:55 GMT | starting dump
Wed, 16 Jun 2021 12:13:57 GMT | got 1 objects from source elasticsearch (offset: 0)
Wed, 16 Jun 2021 12:13:57 GMT | Error Emitted => {"error":"Incorrect HTTP method for uri [/] and method [PUT], allowed: [HEAD, GET, DELETE]","status":405}
Wed, 16 Jun 2021 12:13:57 GMT | Error Emitted => {"error":"Incorrect HTTP method for uri [/] and method [PUT], allowed: [HEAD, GET, DELETE]","status":405}
Wed, 16 Jun 2021 12:13:57 GMT | Total Writes: 0
Wed, 16 Jun 2021 12:13:57 GMT | dump ended with error (get phase) => METHOD_NOT_ALLOWED: {"error":"Incorrect HTTP method for uri [/] and method [PUT], allowed: [HEAD, GET, DELETE]","status":405}
```

**Comment by indapublic** [comment]
excellent

**Comment by ferronrsmith** [comment]
There isn't enough information in this issue to help with anything. I don't have the time to be fishing for information. Any issue that doesn't have the sufficient information to help diagnose the problem will be closed.

Questions you need answer

1. What's the source + target ES version ?
2. What kind of environment. Is this a managed ES instance etc ?
3. It could be a permission issue, but I don't know the ACL configuration, the environment nothing.

**Comment by ferronrsmith** [comment]
The analyzer type uses the settings endpoint, which does a [PUT](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html#update-index-settings-api-request)

**Comment by phlegx** [comment]
Hi Guys. I'm having exactly the same issue with importing the Analyzer.

This is how I try to import:

```
    NODE_TLS_REJECT_UNAUTHORIZED=0 elasticdump \
      --input="$analyzer_file" \
      --output="https://elastic:$ELASTIC_PASSWORD:es-host-internal-kubernetes:9200" \
      --type=analyzer
```

Then getting this error:

```
core-elasticsearch-backup-restore-lmbjv Fri, 16 Jun 2023 07:58:01 GMT | starting dump
core-elasticsearch-backup-restore-lmbjv Fri, 16 Jun 2023 07:58:01 GMT | got 1 objects from source file (offset: 0)
core-elasticsearch-backup-restore-lmbjv Fri, 16 Jun 2023 07:58:01 GMT | Error Emitted => {"error":"Incorrect HTTP method for uri [/] and method [PUT], allowed: [DELETE, HEAD, GET]","status":405}
core-elasticsearch-backup-restore-lmbjv Fri, 16 Jun 2023 07:58:01 GMT | Error Emitted => {"error":"Incorrect HTTP method for uri [/] and method [PUT], allowed: [DELETE, HEAD, GET]","status":405}
core-elasticsearch-backup-restore-lmbjv Fri, 16 Jun 2023 07:58:01 GMT | Total Writes: 0
core-elasticsearch-backup-restore-lmbjv Fri, 16 Jun 2023 07:58:01 GMT | dump ended with error (get phase) => METHOD_NOT_ALLOWED: {"error":"Incorrect HTTP method for uri [/] and method [PUT], allowed: [DELETE, HEAD, GET]","status":405}
```

Some more infos:

- Using latest docker image of Elasticdump `v6.103.0`
- My Source and target ES version I export and import to is:` 8.8.0`
- I'm using self hosted ECK Kubernetes Operator (version `2.8.0`) with currently self  signed cert and user/password enabled
- Regarding permissions I have the default configuration and access as default admin user "elastic". Importing the index itself with Elasticdump for example was no problem


If you guys have an idea what the issue could be or how to debug it further, let me know.
