### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SowmyaM84** [elasticsearch-dump/elasticsearch-dump#804]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- 6.72.0
- 6.2.3

elasticdump \
  --s3AccessKeyId "${AWS_ACCESS_KEY_ID}" \
  --s3SecretAccessKey "${AWS_SECRET_ACCESS_KEY}" \
  --input="<ES_URL>" \
  --output "s3://${S3_BUCKET}/${S3_FOLDER}/$(date "+%Y%m%d-%H%M%S")/${FILE_NAME}_$(date "+%Y%m%d-%H%M%S").json" \
  --type="data" \
  --size="-1" \
  --sourceOnly=true \
  --fileSize="100mb" \
  --limit="500"

**Describe the bug**
During few runs, file is not generated and missed. 
Example- Everyday we get 58 files as part of this process but few times we miss 1 file and get only 57 files in our S3 bucket.

**Comment by ferronrsmith** [comment]
It's not possible to reproduce this with the information provided.

This could be because : 

1. Your elastic instance failed (I have no logs to confirm)
2. You have less data today that yesterday (I have no logs to confirm)
3. Could be an AWS failure to send **chunk** (I have no logs to confirm)
