### ISSUE TITLE
[BUG]when dumping an index to file, lose one batch data with limit=10000 or limit=5000

### ISSUE THREAD

**Issue by migowei0621** [elasticsearch-dump/elasticsearch-dump#806]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version 6.72.0
- Elasticsearch version 7.7.0
- Node.js version *(note that nodejs v10+ is required for this tool)* v10.10.0
- Full command you are having issue with (with inputs and outputs) 
  `elasticdump --input http://eshost:port/20201012-20201018_error_info --output 20201012-20201018_error_info_limit5000.json --type data --limit 5000 --overwrite`

**Describe the bug**
when limit = 5000, elasticdump loses 5000 documents. 
![Screenshot from 2021-06-23 10-21-28](https://user-images.githubusercontent.com/2839878/123026302-80c5a800-d40e-11eb-9887-1e0cbfa0bf28.png)
![Screenshot from 2021-06-23 10-43-20](https://user-images.githubusercontent.com/2839878/123027158-f5e5ad00-d40f-11eb-8527-c3b08e8a518e.png)

and when limit = 10000, loses 10000 documents.

.

**Comment by ferronrsmith** [comment]
This isn't necessarily a bug and it's hard to state who's fault it is. It could be unbalanced cluster (data not replicated across all 3 indices) or something ES related. Whatever data is pulled by esDump gets dumped into the destination. I'll need more info
