### ISSUE TITLE
[BUG] No Error Code if Dump into s3 Bucket Fails

### ISSUE THREAD

**Issue by DebakelOrakel** [elasticsearch-dump/elasticsearch-dump#807]
**Context**
- ElasticDump version: docker.io/elasticdump/elasticsearch-dump:v6.72.0
- Openshift: openshift v3.11.318
- ElasticDump as CronJob

**Describe the bug**
There are no errors thrown if writing to an s3 bucket goes wrong. In my case i submitted the wrong bucket name and from the outputs i wouldn't see that something went wrong:
```
# oc -n openshift-logging get jobs
NAME                                            DESIRED   SUCCESSFUL   AGE
es-dump-gva-tg-mt-649916c8ca4daebf-1624423200   1         1            42m
```

**To Reproduce**
1. Create a Job or Pod with a wrong bucket name or no access to the bucket
2. Run Job

**Current behavior**
Job finishes without an error.

**Expected behavior**
Job throws error

**Screenshots**
```
Wed, 23 Jun 2021 04:40:09 GMT | starting dump
Wed, 23 Jun 2021 04:40:10 GMT | got 5000 objects from source elasticsearch (offset: 0)
Wed, 23 Jun 2021 04:40:10 GMT | sent 5000 objects to destination s3, wrote 5000
Wed, 23 Jun 2021 04:40:10 GMT | Error Emitted => You are not authorized to perform sos/putObject on bucket es-dump-gva
Wed, 23 Jun 2021 04:40:10 GMT | got 5000 objects from source elasticsearch (offset: 5000)
...
Wed, 23 Jun 2021 05:00:03 GMT | Error Emitted => You are not authorized to perform sos/putObject on bucket es-dump-gva
...
Wed, 23 Jun 2021 05:00:10 GMT | sent 639 objects to destination s3, wrote 639
Wed, 23 Jun 2021 05:00:10 GMT | got 0 objects from source elasticsearch (offset: 6005639)
Wed, 23 Jun 2021 05:00:10 GMT | Total Writes: 6005639
Wed, 23 Jun 2021 05:00:10 GMT | dump complete
```

**Comment by ferronrsmith** [comment]
https://github.com/elasticsearch-dump/elasticsearch-dump/commit/05effff675499d486f271e71a1050e2db4408ed8
