### ISSUE TITLE
Question: Dumping data in order of id

### ISSUE THREAD

**Issue by dandago** [elasticsearch-dump/elasticsearch-dump#808]
Hi,

I currently use elasticdump to take snapshots of Elasticsearch data before and after making software changes, and compare the data to see that it was not affected.

In order to compare the data using standard diff tools, it's important that the data is downloaded in order of id.

I currently use elasticdump, then sort the data as a post-processing step; however I wonder whether elasticdump has any in-built option to get all the data in order.

Thanks in advance!

**Comment by ferronrsmith** [comment]
use the `--searchBody` flag to sort the data coming from elastic. Assuming you didn't set concurrency then it should dump in a sorted order.

More info on sorting : https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-sort.html
