### ISSUE TITLE
[FEATURE] provide a simple way to use ES bulk api

### ISSUE THREAD

**Issue by parisni** [elasticsearch-dump/elasticsearch-dump#809]
I haven't found a easy way to produce ndjson compatible with the ES _bulk api
Only the use of transformers

**Comment by ferronrsmith** [comment]
I'm not sure what the question is. 

The library uses the bulk api to index data. It's fairly simple to write a module that converts your data to a format that can be consumed by ndjson (this is done internally by es-dump). 

If you have ndjson and wish to index it just use a transform and not all es ndjson format is supported, only indexing
