### ISSUE TITLE
[BUG] oracle linux 8 installation

### ISSUE THREAD

**Issue by TristisOris** [elasticsearch-dump/elasticsearch-dump#810]
have some problems with installation on Oracle linux 8.

# npm -v
6.14.11

# npm install elasticdump -g
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated s3signed@0.1.0: This module is no longer maintained. It is provided as is.
/usr/local/bin/elasticdump -> /usr/local/lib/node_modules/elasticdump/bin/elasticdump
/usr/local/bin/multielasticdump -> /usr/local/lib/node_modules/elasticdump/bin/multielasticdump
+ elasticdump@6.72.0
updated 1 package in 6.665s

# npm install elasticdump
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated s3signed@0.1.0: This module is no longer maintained. It is provided as is.
npm WARN keywords No repository field.
npm WARN keywords No license field.

npm ERR! code EEXIST
npm ERR! path /var/scripts/keywords/node_modules/.bin/elasticdump
npm ERR! Refusing to delete /var/scripts/keywords/node_modules/.bin/elasticdump: is outside /var/scripts/keywords/node_modules/elasticdump and not a link
npm ERR! File exists: /var/scripts/keywords/node_modules/.bin/elasticdump
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-29T08_18_54_729Z-debug.log

[2021-06-29T08_18_54_729Z-debug.log](https://github.com/elasticsearch-dump/elasticsearch-dump/files/6731771/2021-06-29T08_18_54_729Z-debug.log)

**Comment by ferronrsmith** [comment]
Seems like it's trying to install over an existing. Have you tried uninstalling then reinstalling.

**Comment by TristisOris** [comment]
same on Centos 7

# npm install elasticdump -g
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated querystring@0.2.0: The
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated s3signed@0.1.0: This module is no longer maintained. It is provided as is.
/usr/bin/elasticdump -> /usr/lib/node_modules/elasticdump/bin/elasticdump
/usr/bin/multielasticdump -> /usr/lib/node_modules/elasticdump/bin/multielasticdump

> aws-sdk@2.920.0 postinstall /usr/lib/node_modules/elasticdump/node_modules/aws-sdk
> node scripts/check-node-version.js

The AWS SDK for JavaScript (v2) will no longer support Node.js v6.17.1
as of November 1, 2021. To continue receiving updates to AWS services
and bug fixes please upgrade to Node.js 10.x or later.

# elasticdump
/usr/lib/node_modules/elasticdump/lib/processor.js:40
  async _loop (limit, offset, totalWrites) {
        ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/elasticdump/elasticdump.js:3:28)

**Comment by ferronrsmith** [comment]
The version of node required is v10 or higher
