### ISSUE TITLE
maybe need replace -> {yyyy} {name of copyright owner}. 

### ISSUE THREAD

**Issue by kyadet** [elasticsearch-dump/elasticsearch-dump#811]
template text exists yet here.
https://github.com/elasticsearch-dump/elasticsearch-dump/blob/c8ee996eb49a78e85fa24bdac8c3afb01bd1fc3b/LICENSE.txt#L189

maybe need replace to year and your name for your great tool and your rights.

**Comment by ferronrsmith** [comment]
No my friend, the tool belongs to you 🙂. Everyone who uses it, shares it, reports a bug and submit fixed. For me to be the "owner " wouldn't be fair to all the persons who have contributed. Thanks for the note, but I think I'll let it stay 😎
