### ISSUE TITLE
[BUG] fails to use url when behind nginx forwarding without port

### ISSUE THREAD

**Issue by rorimac** [elasticsearch-dump/elasticsearch-dump#813]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 6.72.1
- Elasticsearch version: 7.9.3
- Node.js version *(note that nodejs v10+ is required for this tool)*: latest when installing elasticdump
- Full command you are having issue with (with inputs and outputs)
bin/elasticdump --input=https://product-url.com/es-test/index_202009 --output='test_index.json' --type=data
- A data-set you can share publicly which reproduces the problem
Works with any data you have in elasticsearch. Even an empty elasticsearch should be possible to uwe to reproduce the issue

**Describe the bug**
We have our product deployed using kubernetes and have temporarily opened elasticsearch to https://product-url.com/es-test using ingress rather than port 9200. When running the above command, elasticdump tries to access https://product-url.com directly rather than the correct path https://product-url.com/es-test as the url.

**To Reproduce**
1. set up an nginx server to forward localhost/es to a port where you have elasticsearch runnning
2. run the following command
bin/elasticdump --input=http://localhost/es/index_202009 --output='test_index.json' 

**Current behavior**
elasticdump tries to access https://product-url.com directly rather than https://product-url.com/es-test

**Expected behavior**
elasticdump access https://product-url.com/es-test correctly

**Screenshots**

**Additional context**
I have made a temporary fix for me by updating the file lib/parse-base-url.js where I have changed
```
else if (hostParts.length <= 3) {
    //
  } else if (hostParts.length > 4) {
    host = hostParts.slice(0, -2).join('/')
    index = hostParts[hostParts.length - 2]
    type = hostParts[hostParts.length - 1]
```
to instead be
```
else if (hostParts.length <= 4) {
    //
  } else if (hostParts.length > 5) {
    host = hostParts.slice(0, -2).join('/')
    index = hostParts[hostParts.length - 2]
    type = hostParts[hostParts.length - 1]
```
that is, increasing the length by one. Note that this solution of course does not work in general and would break the current setup for users who specify the elasticsearch location with a port number. I will thus not make a pull request for this.
> A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What was the url? What steps will reproduce the issue? What OS experience the problem? All these details will help to fix any potential bugs as soon as possible.

**Comment by ferronrsmith** [comment]
### Alternate approach


```bash
# --input-index : Specifies the source index and type
bin/elasticdump --input=https://product-url.com --input-index=index_202009/es-test --output='test_index.json' --type=data
```
