### ISSUE TITLE
[BUG] Unauthorized when trying to connect to AWS ElasticSearch OpenDistro

### ISSUE THREAD

**Issue by yogeek** [elasticsearch-dump/elasticsearch-dump#816]
**Context**

- ElasticDump version : docker pull elasticdump/elasticsearch-dump:latest
- Elasticsearch version : 7.7 (AWS ElasticSearch OpenDistro in China Region)
- Node.js version : (the one from docker image)
- Full command you are having issue with (with inputs and outputs)

```
export ES_USER="admin"
export ES_PWD="xxx"
export ES_HOST="myelasticsearch-instance.cn-north-1.es.amazonaws.com.cn"

mkdir es_dir
cat <<EOF >> ./es_dir/http_auth_file
user=$ES_USER
password=$ES_PWD
EOF

docker run --rm -it --net=host -v $(pwd)/es_dir:/app -w /app \
	 -e ES_USER -e ES_PWD -e ES_HOST
	 -e NODE_TLS_REJECT_UNAUTHORIZED=0 \
	elasticdump/elasticsearch-dump:latest \
		--input=https://$ES_HOST/.opendistro_security \
		--httpAuthFile=/app/http_auth_file \
		--output=$

(node:1) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
Fri, 16 Jul 2021 13:04:43 GMT | Error Emitted => Unauthorized
Fri, 16 Jul 2021 13:04:43 GMT | Error Emitted => Unauthorized
```

**Describe the bug**
When trying to connect to AWS ElasticSearch with http auth file, getting an `Unauthorized` with elasticdump whereas an API call with curl is OK.

**Current behavior**

The above command returns :
```
(node:1) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
Fri, 16 Jul 2021 13:04:43 GMT | Error Emitted => Unauthorized
Fri, 16 Jul 2021 13:04:43 GMT | Error Emitted => Unauthorized

```

**Additional context**

A curl command to the ES API is working well from the same docker container :
```
$ docker run --rm -it --net=host -v $(pwd)/es_dir:/app -w /app -e ES_USER -e ES_PWD -e ES_HOST -e NODE_TLS_REJECT_UNAUTHORIZED=0 --entrypoint bash elasticdump/elasticsearch-dump:latest

#### Inside the container
$ apt update
$ apt install -y curl
$ curl -L -X GET -u $ES_USER:$ES_PWD https://$ES_HOST/_cat/indices/.opendistro_security
green open .opendistro_security _Nqs4B4YRIKy7Bpy_Acc0w 1 1 8 3 161.6kb 61.7kb
```

Is there a specific way to do for OpenDistro ElasticSearch ?

**Comment by ferronrsmith** [comment]
Have you tried 

```
--input=http://name:password@production.es.com:9200/my_index
```

Does sound like maybe an error in the ini file defined

**Comment by yogeek** [comment]
@ferronrsmith yes I have tried it and it complained because he tried to search a host called 'name' ('admin' in my case)...
I did not manage to use the syntax with http://user:password@host because of this and that's why I tried the auth file instead

**Comment by ferronrsmith** [comment]
Did you properly escape the username and password ?

**Comment by yogeek** [comment]
@ferronrsmith indeed, my password conained a '#' and needed to be percent-encoded ! Thank you for your help 👍
