### ISSUE TITLE
[BUG] self signed certificate in certificate chain

### ISSUE THREAD

**Issue by gerbdla** [elasticsearch-dump/elasticsearch-dump#820]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version v6.65.3
- Elasticsearch version 7.10d
- Node.js version v14.15.4
- Full command you are having issue with (with inputs and outputs)
elasticdump --input=https://example-test-es-02.example.com:443/test_index --output=/usr/share/backups/test_index.json 
elasticdump --input=https://example-test-es-02.example.com:443/test_index --output=/usr/share/backups/test_index.json -ca=/usr/share/certs/ca/pem
elasticdump --input=https://example-test-es-02.example.com:443/test_index --output=/usr/share/backups/test_index.json -cert=/usr/share/certs/ca.pem

**Describe the bug**
this is most likely not a bug and just the way elasticdump works within a docker container with npm.  I am just trying to get more clarity and looking for someone who solved this issue. because the NODE_TLS_REJECT_UNAUTHORIZED=0 solution is not acceptable in our production environment.
Error Emitted => self signed certificate in certificate chain
Error Emitted => self signed certificate in certificate chain
The request works fine with curl.
curl https://example-test-es-02.example.com:443  --cacert /usr/share/certs/ca.pem

Thanks You

**Comment by ferronrsmith** [comment]
The only way around this is to get a valid certificate. [letsencrypt](https://letsencrypt.org) is giving them away for free. 
NODE_TLS_REJECT_UNAUTHORIZED isn't good for a production system, but if this communication between the 2 systems are trusted then it really doesn't matter. 

The choice is yours.

**Comment by krisan** [comment]
Just in case someone has stuck on the same error... if you are using `ca/cert/etc` parameter(s) - ensure that you are using also **`--tlsAuth`** parameter, this can be missed reading documentation.

Only with the `--tlsAuth` parameter included, others - related will be in use:

https://github.com/elasticsearch-dump/elasticsearch-dump/blob/d2f257a8b95661dec90075293124fafbd75c2908/lib/transports/elasticsearch.js#L55-L60

FYI: @gerbdla, @ferronrsmith

**Comment by ferronrsmith** [comment]
https://nodejs.org/api/cli.html#node_extra_ca_certsfile should work:

```
NODE_EXTRA_CA_CERTS=/path/to/your/cert.pem
```

_Originally posted by @ebuildy in https://github.com/elasticsearch-dump/elasticsearch-dump/issues/992#issuecomment-1737377727_
            
> Added for future reference.
