### ISSUE TITLE
[BUG] "ERR_STRING_TOO_LONG" during export

### ISSUE THREAD

**Issue by sirkus7** [elasticsearch-dump/elasticsearch-dump#821]
**Context**
- ElasticDump version: 6.72.0
- Elasticsearch version: 7.13.3
- Node.js version: (I'm running elasticdump from docker image, using the version of Node.js provided)
- The following is the full command being used, and the resulting error:
```
$ docker run --rm -ti --network host -v /tmp:/tmp elasticdump/elasticsearch-dump \
   --input=http://localhost:9200/net-log-2021 \
   --output=/tmp/net-log-2021.ndjson \
   --type=data

Fri, 03 Sep 2021 22:01:57 GMT | starting dump
buffer.js:798
    return this.utf8Slice(start, end);
                ^

Error: Cannot create a string longer than 0x1fffffe8 characters
    at Buffer.toString (buffer.js:798:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:1128:39)
    at Request.emit (events.js:375:28)
    at Request.emit (domain.js:470:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:481:28)
    at IncomingMessage.emit (events.js:387:35)
    at IncomingMessage.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ERR_STRING_TOO_LONG'
}
```

**Describe the bug**
While trying to use elasticdump to export the data of an index using the above command, it runs for a bit and then returns the above error. 

**To Reproduce**
I'm not able to provide the dataset from the index since I can't export it, but this index does have some fields where the value may be rather long. 

**Other comments**
Searching for this particular error online highlights that this is likely a Node.js error related to a fixed limitation on the size of strings in Node.js.  

If this is a limitation in Node.js, is there a way I can get around this to successfully export the data?

**Comment by ferronrsmith** [comment]
You're dumping too much data. Try using the split function

**Comment by ferronrsmith** [comment]
Related to https://github.com/nodejs/node/commit/d2b9e7cb01166da0e6cfd77d1cf362b8d49c6c68

**Comment by siccovansas** [comment]
I also ran into this issue. After a lot of experimentation I was able to complete a dump using `--limit=1000 --fileSize=100mb`. No idea if this works for others.

**Comment by ferronrsmith** [comment]
It's works because you're segmenting the document into smaller chunks and not reading the large string into memory.
