### ISSUE TITLE
[BUG]When exporting index data using elasticdump, 32-Bit length text type converted to int type，But this problem will not occur through curl queries

### ISSUE THREAD

**Issue by cmh200704** [elasticsearch-dump/elasticsearch-dump#822]
node --version > v12.16.0
npm --version >6.13.4
elasticdump --version > 6.72.0
elasticsearch --version >6.x

```
PUT test_01
{
  "mappings": {
      "_doc": {
        "dynamic": "strict",
        "properties": {
          "uuid": {
            "type": "text"
          }
        }
      }
  }  
}
```

---insert 
```
POST test_01/_doc/10021042309491564510020011410144
{
  "uuid":10021042309491564510020011410144
}
```
elasticdump --limit=100 --input=http://elastic:xxxx@172.xx.xx.xx:9200/test_01 --output=/tmp/test_01.json --support-big-int --type=data

----------------------

```
cat /tmp/test_01.json
{"_index":"test_01","_type":"_doc","_id":10021042309491564510020011410144,"_score":1,"_source":{"uuid":1.0021042309491564510020011410144e+31}}
```

uuid converted to int type
-----------------------

```bash
curl -u elastic:xxx  -H "Content-Type: application/json"  -XGET "http://172.xx.xx.xx:9200/test_01/_doc/10021042309491564510020011410144"
```

```json
{"_index":"test_01","_type":"_doc","_id":"10021042309491564510020011410144","_version":1,"found":true,"_source":{
  "uuid":10021042309491564510020011410144
}
```

**Comment by ferronrsmith** [comment]
If the mapping of the field is **text**, then it can't be a string. The problem is you inserted the value without string wrapping

integer => 10021042309491564510020011410144
string => "10021042309491564510020011410144"

Seems to me that the value was inserted the way you wanted.

**Comment by cmh200704** [comment]
sorry,My previous demo was wrong

POST test_01/_doc/10021042309491564510020011410144
{
  "uuid":"10021042309491564510020011410144"
}

//Export using elatisdump 
elasticdump --input=http://elastic:xxxx@172.xx.xx.xx:9200/test_01 --output=/tmp/test_01.json --support-big-int --type=data

cat /tmp/test_01.json 

{"_index":"test_01","_type":"_doc","_id":10021042309491564510020011410144,"_score":1,"_source":{"uuid":10021042309491564510020011410144}}

The derived value becomes a number

Export data to write to test_02 index

PUT test_02
{
  "mappings": {
      "_doc": {
        "dynamic": "strict",
        "properties": {
          "uuid": {
            "type": "text"
          }
        }
      }
  }  
}
elasticdump --input=http://elastic:xxxx@172.xx.xx.xx:9200/test_01 --output=http://elastic:xxxx@172.xx.xx.xx:9200/test_02 --support-big-int --type=data

curl -u elastic:xxx  -H "Content-Type: application/json"  -XGET "http://172.xx.xx.xx:9200/test_02/_doc/10021042309491564510020011410144"

{"_index":"test_02","_type":"_doc","_id":"10021042309491564510020011410144","_version":1,"found":true,"_source":{"uuid":10021042309491564510020011410144}}

test_02 uuid converted to int type

"hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "test_01",
        "_type": "_doc",
        "_id": "10021042309491564510020011410144",
        "_score": 1,
        "_source": {
          "uuid": "10021042309491564510020011410144"
        }
      }
    ]
  }


"hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "test_02",
        "_type": "_doc",
        "_id": "10021042309491564510020011410144",
        "_score": 1,
        "_source": {
          "uuid": 1.0021042309491564e+31
        }
      }
    ]
  }

**Comment by cmh200704** [comment]
> If the mapping of the field is **text**, then it can't be a integer. The problem is you inserted the value without string wrapping
> 
> 如果字段的映射是文本，那么它就不能是整数。问题是插入值时没有进行字符串环绕
> 
> integer => 10021042309491564510020011410144
> string => "10021042309491564510020011410144"
> 
> Integer = > 10021042309491564510020011410144 string = > “10021042309491564510020011410144”
> 
> Quotes are important for javascript.
> 
> 引号对 javascript 来说很重要。
