### ISSUE TITLE
[BUG]When exporting index data using elasticdump, 32-Bit length text type converted to int type

### ISSUE THREAD

**Issue by cmh200704** [elasticsearch-dump/elasticsearch-dump#823]
node --version > v12.16.0
npm --version >6.13.4
elasticdump --version > 6.72.0
elasticsearch --version >6.x

```
**insert text type data**
POST test_01/_doc/10021042309491564510020011410144
{
"uuid":"10021042309491564510020011410144"
}
```

```
**Export using elatisdump**
elasticdump --input=http://elastic:xxxx@172.xx.xx.xx:9200/test_01 --output=/tmp/test_01.json --support-big-int --type=data
```

cat /tmp/test_01.json

```
{"_index":"test_01","_type":"_doc","_id":10021042309491564510020011410144,"_score":1,"_source":{"uuid":10021042309491564510020011410144}}
```

The derived value becomes a number

Export data to write to test_02 index

```
PUT test_02
{
	"mappings": {
		"_doc": {
			"dynamic": "strict",
			"properties": {
				"uuid": {
					"type": "text"
				}
			}
		}
	}
}
```

```
elasticdump --input=http://elastic:xxxx@172.xx.xx.xx:9200/test_01 --output=http://elastic:xxxx@172.xx.xx.xx:9200/test_02 --support-big-int --type=data
```

curl -u elastic:xxx -H "Content-Type: application/json" -XGET "http://172.xx.xx.xx:9200/test_02/_doc/10021042309491564510020011410144"

{"_index":"test_02","_type":"_doc","_id":"10021042309491564510020011410144","_version":1,"found":true,"_source":{"uuid":10021042309491564510020011410144}}

**test_01 is right**

```json
{
	"hits": {
		"total": 1,
		"max_score": 1,
		"hits": [{
			"_index": "test_01",
			"_type": "_doc",
			"_id": "10021042309491564510020011410144",
			"_score": 1,
			"_source": {
				"uuid": "10021042309491564510020011410144"
			}
		}]
	}
}
```

**test_02 uuid converted to int type**

```json
{
	"hits": {
		"total": 1,
		"max_score": 1,
		"hits": [{
			"_index": "test_02",
			"_type": "_doc",
			"_id": "10021042309491564510020011410144",
			"_score": 1,
			"_source": {
				"uuid": 1.0021042309491564e+31
			}
		}]
	}
}
```

**Comment by ferronrsmith** [comment]
Related to #822

**Comment by ferronrsmith** [comment]
The problem you're having is because you're using `--support-big-int`. This flag converts fields matchings numeric decimal to BigNumber format, but in the above expression it needs to be a string.


```
**insert text type data**
POST test_01/_doc/10021042309491564510020011410144
{
"uuid":"10021042309491564510020011410144"
}
```

```
**Export using elatisdump**
elasticdump --input=http://elastic:xxxx@172.xx.xx.xx:9200/test_01 --output=/tmp/test_01.json --support-big-int --type=data
```

cat /tmp/test_01.json (notice that the value is quoted, it's saved as a string)

```json
{"_index":"test_01","_type":"_doc","_id":10021042309491564510020011410144,"_score":1,"_source":{"uuid":"10021042309491564510020011410144"}}
```

```
elasticdump --input=http://elastic:xxxx@172.xx.xx.xx:9200/test_01 --output=http://elastic:xxxx@172.xx.xx.xx:9200/test_02 --support-big-int --type=data
```

curl -u elastic:xxx -H "Content-Type: application/json" -XGET "http://172.xx.xx.xx:9200/test_02/_doc/10021042309491564510020011410144"

```json
{
    "_index": "test_02",
    "_type": "_doc",
    "_id": "10021042309491564510020011410144",
    "_version": 1,
    "_seq_no": 0,
    "_primary_term": 1,
    "found": true,
    "_source": {
        "uuid": "10021042309491564510020011410144"
    }
}
```

Do not use `--support-big-int` on string values. String values must be QUOTED

**Comment by cmh200704** [comment]
yes,Do not use --support-big-int No problem，bug Will have this problem：https://github.com/elasticsearch-dump/elasticsearch-dump/issues/799

**Comment by ferronrsmith** [comment]
That won't be an issue if the data is inserted into elastic search quoted. 

10021042309491564510020011410144 <--- javascript interprets as a integer
"10021042309491564510020011410144" <-- javascript interprets as a string

**Comment by cmh200704** [comment]
This kind of super-long numbers need to be brought with letters at the product design level to make it stronger and consistent, so this problem will not occur, but now because the character string is a string of super-long numbers, the display becomes reshaped after the elasticdump is exported, and the value becomes reshaped after the ES cluster is inserted. If you remove --support-big-int for the super-long 17-bit reshaping export, it will be truncated and cannot be removed

**Comment by ferronrsmith** [comment]
The is representation issue. String need to be quoted. If they aren't, when they are serialized they will be treated as numbers. This is JavaScript issue. Just wrap the number with quotes and you should be fine.
