### ISSUE TITLE
[BUG] No Error when S3 access key is not available / got deleted

### ISSUE THREAD

**Issue by DebakelOrakel** [elasticsearch-dump/elasticsearch-dump#824]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: docker.io/elasticdump/elasticsearch-dump:v6.72.0

**Describe the bug**

During operations the access token to the S3 bucket got deleted, elasticsearch-dump only reported an error but did not exit with an error code.
`Thu, 09 Sep 2021 05:40:42 GMT | Error Emitted => Access Key you provided does not exist in our records.`

**Current behavior**

Elasticsearch-dump just continues to run, without reporting any errors.

**Expected behavior**

Elasticsearch-dump should immediatly exit with an error code.

**Additional context**

We run elasticsearch-dump on an openshift-cluster as a cronjob, so we need a reliable error handling.

**Comment by ferronrsmith** [comment]
Fixed by https://github.com/elasticsearch-dump/elasticsearch-dump/commit/2c5e435770fdd32361a7e71735623ae340d69581

Will be in the next release

**Comment by DebakelOrakel** [comment]
would you mind pushing the latest release to docker hub, or is it available elsewhere?

**Comment by ferronrsmith** [comment]
I'll do that in a bit. Docker got cheap and removed auto build for free users.

**Comment by ferronrsmith** [comment]
Pushed

**Comment by DebakelOrakel** [comment]
Perfect, thank you very much :D
