### ISSUE TITLE
elasticDump throws an error "json_parse_exception" when dumping OpenSearch index to local file

### ISSUE THREAD

**Issue by Zhangxunmt** [elasticsearch-dump/elasticsearch-dump#835]
Run elasticDump to dump index to a file based on below versions:
1. opensearch-1.1.0
2. elasticdump  6.75.0
3. operating System: Linux

The tool gives an error for "json_parse_exception", but I don't know where is the error?  The index to be dumped is not empty and has docs in it. 

curl "localhost:9200/_cat/indices?v&s=i"
health status index                                            uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   tms-issue-ap-northeast-1-filtered-combined-dates QDWoPBb-QN-TDfqqg56yPQ   1   1      22848            0      9.3mb          9.3mb

elasticdump  --input=http://localhost:9200/tms-issue-ap-northeast-1-filtered-combined-dates  --output=my_index.json  --type=data
Thu, 11 Nov 2021 02:58:00 GMT | starting dump
Thu, 11 Nov 2021 02:58:00 GMT | got 100 objects from source elasticsearch (offset: 0)
Thu, 11 Nov 2021 02:58:00 GMT | sent 100 objects to destination file, wrote 100
Thu, 11 Nov 2021 02:58:00 GMT | Error Emitted => {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Failed to parse request body"}],"type":"illegal_argument_exception","reason":"Failed to parse request body","caused_by":{"type":"json_parse_exception","reason":"Unrecognized token 'FGluY2x1ZGVfY29udGV4dF91dWlkDXF1ZXJ5QW5kRmV0Y2gBFl9NRmdISVNJVFR5UDN5VmM3VWplOUEAAAAAAAAABRZ5bDZhZUpYX1JpT0w3ZmRqaGs4WXJR': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (org.opensearch.common.io.stream.InputStreamStreamInput); line: 1, column: 121]"}},"status":400}
Thu, 11 Nov 2021 02:58:00 GMT | Error Emitted => {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Failed to parse request body"}],"type":"illegal_argument_exception","reason":"Failed to parse request body","caused_by":{"type":"json_parse_exception","reason":"Unrecognized token 'FGluY2x1ZGVfY29udGV4dF91dWlkDXF1ZXJ5QW5kRmV0Y2gBFl9NRmdISVNJVFR5UDN5VmM3VWplOUEAAAAAAAAABRZ5bDZhZUpYX1JpT0w3ZmRqaGs4WXJR': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (org.opensearch.common.io.stream.InputStreamStreamInput); line: 1, column: 121]"}},"status":400}
Thu, 11 Nov 2021 02:58:00 GMT | Total Writes: 0
Thu, 11 Nov 2021 02:58:00 GMT | dump ended with error (get phase) => BAD_REQUEST: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Failed to parse request body"}],"type":"illegal_argument_exception","reason":"Failed to parse request body","caused_by":{"type":"json_parse_exception","reason":"Unrecognized token 'FGluY2x1ZGVfY29udGV4dF91dWlkDXF1ZXJ5QW5kRmV0Y2gBFl9NRmdISVNJVFR5UDN5VmM3VWplOUEAAAAAAAAABRZ5bDZhZUpYX1JpT0w3ZmRqaGs4WXJR': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (org.opensearch.common.io.stream.InputStreamStreamInput); line: 1, column: 121]"}},"status":400}

**Comment by ferronrsmith** [comment]
**6.75.0** doesn't have compatibility with OpenSearch. This was added in **6.76.0**
