### ISSUE TITLE
Support for S3 StorageClass selection 

### ISSUE THREAD

**Issue by escoriza** [elasticsearch-dump/elasticsearch-dump#836]
**Is your feature request related to a problem? Please describe.**
When trying to upload an object to a particular bucket, I need this object to be stored in a different storageclass than STANDARD, i.e. ONEZONE_IA
There is no configuration parameter available to set this property.

**Describe the solution you'd like**
I'd like to have an argument that would allow me to set the desired StorageClass for the object being uploaded
For example:

elasticdump \
        --input="https://elastic-hostname/index-name" \
        --output "s3://bucket-name/backup-index.json.gzip" \
        --s3AccessKeyId "$ACCESS_KEY_ID" \
        --s3SecretAccessKey "$SECRET_ACCESS_KEY" \
        --s3Region "$REGION" \
        --s3Compress
        --s3StorageClass "ONEZONE_IA"

**Comment by ferronrsmith** [comment]
Feel free to submit a PR, I don't use s3, so I can't add a feature that I am not able to test

**Comment by TirushV** [comment]
Are you getting the data from ES to store it on S3 with the above command?
