### ISSUE TITLE
[BUG] MultiElasticDump uses wrong URL when creating mappings

### ISSUE THREAD

**Issue by robbie-unlikelyai** [elasticsearch-dump/elasticsearch-dump#842]
**Context**

- ElasticDump version: v6.79.0 (via docker container)
- Elasticsearch version: 7.10.0 (running locally on a mac)
- Node.js version *(note that nodejs v10+ is required for this tool)*: v15.6.0
- Full command you are having issue with (with inputs and outputs): "docker run --net=host --rm -ti -v {PATH_TO_DATA_DIR}/data:/data elasticdump/elasticsearch-dump:v6.79.0 multielasticdump --direction=load --match='test' --ignoreType='data,settings,template' --output=http://localhost:9200/ --input=/data"
- A data-set you can share publicly which reproduces the problem:
`/data` directory contains a single file `test.mapping.json` which contains `{"test":{"mappings":{"properties":{"dateCreated":{"type":"date"}}}}}`

**Describe the bug**
When this command is run, it produces the following error:

`Error Emitted => {"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}`

**To Reproduce**
1. Run elasticsearch locally
2. Create the `data` directory mention above with the `test.mapping.json` file
3. Run the command mentioned above, and you will see the error

**Current behavior**
Error produced

**Expected behavior**
Mapping created correctly

**Screenshots**
n/a

**Additional context**
The log looks as follows:
```
Fri, 26 Nov 2021 16:20:59 GMT | list of indexes["test"]
Fri, 26 Nov 2021 16:20:59 GMT | Working on test
Fri, 26 Nov 2021 16:20:59 GMT | indexing mapping /data/test.mapping.json to http://localhost:9200//test
Fri, 26 Nov 2021 16:20:59 GMT [debug] | fork: /usr/local/lib/node_modules/elasticdump/bin/elasticdump --type=mapping,--input=/data/test.mapping.json,--output=http://localhost:9200//test,--headers=null,--cert=null,--key=null,--pass=null,--ca=null,--tlsAuth=false,--input-cert=null,--input-key=null,--input-pass=null,--input-ca=null,--output-cert=null,--output-key=null,--output-pass=null,--output-ca=null,--httpAuthFile=null,--concurrency=1,--carryoverConcurrencyCount=true,--intervalCap=5,--concurrencyInterval=5000,--overwrite=false,--fsCompress=false,--awsChain=false,--awsAccessKeyId=null,--awsSecretAccessKey=null,--awsIniFileProfile=null,--awsService=null,--awsRegion=null,--s3AccessKeyId=null,--s3SecretAccessKey=null,--s3Region=null,--s3Endpoint=null,--s3SSLEnabled=true,--s3ForcePathStyle=false,--s3Compress=false,--s3ServerSideEncryption=null,--s3SSEKMSKeyId=null,--s3ACL=null,--quiet=false,--scroll-with-post=false
Fri, 26 Nov 2021 16:20:59 GMT | starting dump
Fri, 26 Nov 2021 16:20:59 GMT | got 1 objects from source file (offset: 0)
Fri, 26 Nov 2021 16:20:59 GMT | Error Emitted => {"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}
Fri, 26 Nov 2021 16:20:59 GMT | Error Emitted => {"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}
Fri, 26 Nov 2021 16:20:59 GMT | Total Writes: 0
Fri, 26 Nov 2021 16:20:59 GMT | dump ended with error (get phase) => [object Object]
Fri, 26 Nov 2021 16:20:59 GMT | Error: CHILD PROCESS EXITED WITH ERROR.  Stopping process
```

From `--output=http://localhost:9200//test`, it looks like the output URL has an extra `/` in it. When I run the same `elasticdump` command with `--output=http://localhost:9200/test` (single `/`), it works as expected.

**Comment by robbie-unlikelyai** [comment]
@ferronrsmith - have I brought this up in the wrong way? why was this closed?

**Comment by archaeogeek** [comment]
@robbie-unlikelyai thanks for raising this ticket- your catch about the additional / at the end of the output URL helped me resolve this same problem.
