### ISSUE TITLE
[FEATURE] Ignore existing documents matching the same _id or custom field

### ISSUE THREAD

**Issue by samhagin** [elasticsearch-dump/elasticsearch-dump#846]
**Is your feature request related to a problem? Please describe.**
I don't know if this is already built into elasticdump but if it is not, can it be added? A feature to ignore existing documents that match the default _id field or another field you specify. 

**Describe the solution you'd like**
For instance is there is a document with _id:0 , when elasticdump is writing data, it should ignore _id:0 since it already exists. There can be an optional feature to overwrite it also. 

**Additional context**
The main purpose of this feature is to do a differential migration - migrate documents that do not already exist. 

Thanks

**Comment by ferronrsmith** [comment]
The logic that pushes data to ES uses ES bulk. ES bulk doesn't support pre-checking in the way you're expecting. It can be done relatively easily, but that's beyond the scope of this library. It's very easy to get the IDs from ES then generate a sub-set for insertion.

**Comment by samhagin** [comment]
Thanks for your reply. What is the most efficient way to insert documents for specific IDs only?
