### ISSUE TITLE
Mapping from 6.5 to 7.7 error

### ISSUE THREAD

**Issue by iastinf** [elasticsearch-dump/elasticsearch-dump#848]
While I'm trying to migrate an index from 6.5.4 to 7.7.0 with
elasticdump --input=http://source/index_name --input=http://destination/index_name --type=mapping
i got
Error Emitted => {"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}

**Comment by ferronrsmith** [comment]
> ES 7.x.x & higher no longer supports type property. All templates prior to ES 6.0 has to be upgraded to remove the type property


Mapping/Templates has to be updated manually. There is no automatic conversion.
