### ISSUE TITLE
[FEATURE] Add option to configure maximum request payload size when loading into elasticsearch

### ISSUE THREAD

**Issue by zweger** [elasticsearch-dump/elasticsearch-dump#855]
**Is your feature request related to a problem? Please describe.**
AWS OpenSearch imposes [limits on HTTP request payloads](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/limits.html#network-limits). If a request payload goes over the limit, the request is rejected:

```
dump ended with error (get phase) => REQUEST_ENTITY_TOO_LARGE: {"Message":"Request size exceeded 10485760 bytes"}
```

**Describe the solution you'd like**
I'd like to see a --request-payload-limit option, which instead of counting objects (like `--limit`), tracks the total payload size for a batch and makes sure no batch goes over the limit.

**Describe alternatives you've considered**
`--limit` could work for this use case, except it's difficult to tune appropriately: too small and loading is slowed down dramatically, but too large and you risk going over the payload limit. This goes extra for cases when you don't know the average size of documents in the indexes.

**Comment by ferronrsmith** [comment]
This is a server side configuration that should be updated.

**Comment by zweger** [comment]
With Amazon hosted OpenSearch, the payload limit is set by Amazon and cannot be changed.

I think `--request-payload-limit` would be a more user-friendly alternative to `--limit`. `--limit` is difficult to configure because it only limits the request payload size indirectly.

**Comment by ferronrsmith** [comment]
Show the documentation that this can actually be controlled on the server side. This would be a huge security hole.

**Comment by zweger** [comment]
I think I haven't explained this feature request very clearly.

I'm not looking to control the server request payload size limit on the client side. I want the client to not exceed the server's limit. And to help the client do that, I think it makes sense to tell the client what the server's limit is. The client can use that to batch requests and stay below the limit. Does that make sense?

**Comment by ferronrsmith** [comment]
Makes sense but it doesn’t exactly work that way.
