### ISSUE TITLE
parseExtraFields seems to be not working 

### ISSUE THREAD

**Issue by dibdutta** [elasticsearch-dump/elasticsearch-dump#856]
- ElasticDump version: 6.79.4
- Elasticsearch version: 5.4.2
- Node.js version -16.13.1
- Full command you are having issue with (with inputs and outputs) : 
  - ./elasticsearch-dump/bin/elasticdump --input=http://127.0.0.1:9200/snippet  --output=snippet.csv   --type=data --parseExtraFields='index,id,routing,score' --size=5
  - ./elasticsearch-dump/bin/elasticdump --input=http://127.0.0.1:9200/snippet  --output=snippet.csv   --type=data --parseExtraFields=['index','id','routing','score'] --size=5

**Describe the bug**
I have one `_meta` field `_parent` in ES 5.4.2 which has been deprecated since ES 6.0 . I want to export the ES data excluding the `_parent` `mata` field . But both command seems not taking affect . Its still exporting all `_meta` field including `_parent` .

**Comment by ferronrsmith** [comment]
**parseExtraFields** is used to parse data on input (to elasticsearch)

**Comment by dibdutta** [comment]
Can you kindly share a example , I didn't find any. That will be very helpful

**Comment by ferronrsmith** [comment]
You can use a transform (--transform) to modify the input before saving it to a file. Examples are in the doc already

**Comment by dibdutta** [comment]
Ok. Can I drop a `meta field` sing `transform` . I found its more to modify any value under `_source` .

**Comment by ferronrsmith** [comment]
The entire record is passed to the transform. The example provided in the project chose to only use the `_source` property
