### ISSUE TITLE
Link "How to Apply Index Template changes in existing Indexes" lead to a protected Jira site

### ISSUE THREAD

**Issue by dsentker24** [elasticsearch-dump/elasticsearch-dump#857]
As shown in Section [Articles on ElasticDump](https://github.com/elasticsearch-dump/elasticsearch-dump#articles-on-elasticdump), there is a link to page labelled  "[How to Apply Index Template changes in existing Indexes using Elasticdump](https://prophecyinternational.atlassian.net/wiki/spaces/eMite/pages/83787777/HOW+TO+Apply+Index+Template+changes+in+existing+indexes+using+Elasticdump)". This is linking to a protected page i cannot access.

**Comment by ferronrsmith** [comment]
I didn't write the article so I can't say much on this, my apologies.

**Comment by ferronrsmith** [comment]
# Import templates into ES
elasticdump \
  --input=./templates.json \
  --output=http://es.com:9200/ \
  --type=index-template


> Index Template sample https://github.com/elasticsearch-dump/elasticsearch-dump/blob/master/test/test-resources/template_7x_index_template.json
