### ISSUE TITLE
Async function in transformer

### ISSUE THREAD

**Issue by cuongthamhl** [elasticsearch-dump/elasticsearch-dump#860]
Does the `transform` argument take async function? I want the transform function calls an external service and perform some transformations. 

This works:
```
module.exports = function (doc, options) {
```

This doesn't:
```
module.exports = async function (doc, options) {
```

**Comment by ferronrsmith** [comment]
Short answer is no

https://github.com/elasticsearch-dump/elasticsearch-dump/blob/4710c31babc5fd1a126fe0297af907c602fd0de6/elasticdump.js#L45-L47
