### ISSUE TITLE
[FEATURE] Is it possible to package it into a binary file and run it without nodejs?

### ISSUE THREAD

**Issue by zihjiang** [elasticsearch-dump/elasticsearch-dump#861]
as the title

In most scenarios, I only need to use the elasticdump tool to import data, but I also need to consider nodejs dependencies in the process of use, which is very annoying to me, can I package it into a binary file, and use it as an exe, linux executable, or binary for mac os?

**Comment by ferronrsmith** [comment]
It's possible, there are tools like nexe, that can be used, but that's beyond the scope of this project.
