### ISSUE TITLE
[FEATURE] support of tlsAuth with multielasticdump

### ISSUE THREAD

**Issue by gpicron** [elasticsearch-dump/elasticsearch-dump#864]
**Is your feature request related to a problem? Please describe.**
Very simple, the initial query for _alias in multielasticdump is not taking into account --authTLS

**Describe the solution you'd like**
Adding that support would be marvelous

**Describe alternatives you've considered**
Manual script to make a loop on _cat/indices query

**Comment by ferronrsmith** [comment]
feature is here : https://github.com/elasticsearch-dump/elasticsearch-dump/pull/865

Test and let me know if it works as expected

**Comment by ferronrsmith** [comment]
will be in the next release
