### ISSUE TITLE
Security Vulnerability in minimist Dependency

### ISSUE THREAD

**Issue by AhmedAbdelmoneim** [elasticsearch-dump/elasticsearch-dump#867]
Hello!

There's currently a high severity security issue with the minmist package: https://github.com/advisories/GHSA-xvch-5gv4-984h

Does not seem like an actively-maintained project, and there's no ETA on when a fix would be available. There's an ongoing fork though (minimist-lite) that can be used instead of the original package. Was wondering if it'd be possible to switch out the dpenendency on minimist to minimist-lite.

Ongoing issue: https://github.com/substack/minimist/issues/164

**Comment by ferronrsmith** [comment]
https://github.com/elasticsearch-dump/elasticsearch-dump/commit/42610e1a6ce905e2a7a6075943da855472701955
