### ISSUE TITLE
[BUG] Old issue (#870) hasn't been fixed

### ISSUE THREAD

**Issue by trangiang295** [elasticsearch-dump/elasticsearch-dump#871]
**Context**

- ElasticDump version: 6.82.2
- Elasticsearch version: 8.1.1
- Node.js version: v14.17.6

**Describe the bug**
I raised [this issue](https://github.com/elasticsearch-dump/elasticsearch-dump/issues/870). Then I update ElasticDump version to 6.82.2 and test again, but that issue hasn't been fixed. I have same output when running command.
I checked [your commit](https://github.com/elasticsearch-dump/elasticsearch-dump/commit/ee3e0efed6007f2c6dc77b96012a74e75fb98a53). I think that `encodeURIComponent` function return a string: `'undefined'`. So `'undefined' || '_doc'` still equal `'undefined'`. 
Please check this issue again. Thank you.

**Comment by ferronrsmith** [comment]
It should actually be undefined, not 'undefined'. I'll have a look, apologies.

**Comment by ferronrsmith** [comment]
Sorry about, in a rush to resolve the issue, I mixed up the bracket matching. Thanks for testing this, will be adding tests for this in the future. Thanks again and my apologies 

6.82.3

**Comment by trangiang295** [comment]
Thank you. After updating with version 6.82.3, my issue has been fixed. Now I can use `--delete` flag.
And I want to notice about another small issue. To use a specific query with `multielasticdump`, we must use `--searchBody` flag. But in README.md file, you wrote '--searchbody`. I think that you need edit that file.

**Comment by ferronrsmith** [comment]
Thanks for the update

**Comment by ferronrsmith** [comment]
https://github.com/elasticsearch-dump/elasticsearch-dump/commit/ad925be8dc7281e731acb1314ac3d0d17f128c95 doc updated
