### ISSUE TITLE
[FEATURE] Output scrollId by default

### ISSUE THREAD

**Issue by Diego-Hernandez-Moodys** [elasticsearch-dump/elasticsearch-dump#874]
**Is your feature request related to a problem? Please describe.**
This would assist in most scenarios when a dump fails, especially for new users.

**Describe the solution you'd like**
Output the scrollID without the need for debug, as the debug option simply prints too much information to the console.

**Comment by Diego-Hernandez-Moodys** [comment]
Also, does the scrollId also include the == sign at the end?
e.g.,
```
akajsdfkjahsdfkasdfa==
```

**Comment by ferronrsmith** [comment]
There is a `--debug` flag for this.

**Comment by Diego-Hernandez-Moodys** [comment]
> without the need for debug, as it simply prints too much information to the console.

**Comment by ferronrsmith** [comment]
That would actually break the pipe functionality, so I can't do that.

I wouldn't be able to do this 


```bash
# Backup and index to a gzip using stdout:
elasticdump \
  --input=http://production.es.com:9200/my_index \
  --output=$ \
  | gzip > /data/my_index.json.gz
```

The scroll info would be logged into the file
