### ISSUE TITLE
[BUG] dump ended with error (get phase) => Error: socket hang up

### ISSUE THREAD

**Issue by KaMaToZzz** [elasticsearch-dump/elasticsearch-dump#876]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump latest
- Elasticsearch 7
- Node.js 12 *(note that nodejs v10+ is required for this tool)*
- elasticdump --input=http://esp.domain.local:9200/chart_item-01.12.2019 --output=http://test:test@esw.domain.local:9200/chart_item-01.12.2019 --debug
Fri, 15 Apr 2022 07:42:04 GMT | starting dump
Fri, 15 Apr 2022 07:42:04 GMT [debug] | discovered elasticsearch input major version: 6
Fri, 15 Apr 2022 07:47:25 GMT | Error Emitted => socket hang up
Fri, 15 Apr 2022 07:47:25 GMT | Error Emitted => socket hang up
Fri, 15 Apr 2022 07:47:25 GMT | Total Writes: 0
Fri, 15 Apr 2022 07:47:25 GMT | dump ended with error (get phase) => Error: socket hang up

**Describe the bug**

**To Reproduce**

**Current behavior**
Describe what's happening now.

**Expected behavior**

**Screenshots**

**Additional context**

> A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What was the url? What steps will reproduce the issue? What OS experience the problem? All these details will help to fix any potential bugs as soon as possible.

**Comment by ferronrsmith** [comment]
> When you, as a client, send a request to a remote server, and receive no timely response. Your socket is ended which throws this error. You should catch this error and decide how to handle it: whether retry the request, queue it for later, etc.

Please see : https://stackoverflow.com/questions/16995184/nodejs-what-does-socket-hang-up-actually-mean
