### ISSUE TITLE
Create possibility to provide arguments which can be in CURL request[FEATURE]

### ISSUE THREAD

**Issue by vladimircape** [elasticsearch-dump/elasticsearch-dump#877]
I want to make dump from OpenSearch
and we use Boundary security
I can make such CURL request

`curl -XGET https://127.0.0.1:38087/_cat/indices?v -u 'dasdasn:e4e%wfsdfsdsfdsdfsdfsdiyBynu89ZLXHgwnqcJv4Q' --insecure
`
but in elasticdump i don't have possibility to provide such parameter.

` -u 'dasdasn:e4e%wfsdfsdsfdsdfsdfsdiyBynu89ZLXHgwnqcJv4Q'`

**Comment by ferronrsmith** [comment]
```
If you need basic http auth, you can use it like this: --input=http://name:password@production.es.com:9200/my_index
```
> From the documentation

If the password included characters that will cause http to choke, just encode it.

**Comment by vladimircape** [comment]
@ferronrsmith This not works, I want to make dump from OpenSearch

**Comment by ferronrsmith** [comment]
not really sure what you're asking. The point of the project is to dump indices, it's a targeted request utility. Not general purpose like curl
