### ISSUE TITLE
Push updates to Docker

### ISSUE THREAD

**Issue by coltonfreeman26** [elasticsearch-dump/elasticsearch-dump#887]
Good day all,
Do you plan on pushing the latest release of elasticsearch-dump v6.84.1 to your [docker](https://hub.docker.com/r/elasticdump/elasticsearch-dump) registry? Some of the updates you have made to that version would resolve a few of our CVE findings from our scan tools. 
Please let me know if you need any more information.

**Comment by ferronrsmith** [comment]
Done, sorry for the slow turnaround
