### ISSUE TITLE
[BUG] Incomplete dump

### ISSUE THREAD

**Issue by elouanKeryell-Even** [elasticsearch-dump/elasticsearch-dump#889]
**Context**

- ElasticDump version: `6.84.1`
- Elasticsearch version: `7.17.5`
- Node.js version: `v10.19.0`
- Full command you are having issue with (with inputs and outputs)

```bash
elasticdump \
  --input="http://localhost:9200/articles" \
  --output="/myfolder/elasticdump.json"
```

- A data-set you can share publicly which reproduces the problem: too cumbersome unfortunately

**Describe the bug**

I have an index with a few thousands documents

```
$ curl localhost:9200/_cat/indices/articles?v=true
health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   articles qonO_DQmQFOljKYctmtv7A   1   1       5952         2102      7.1mb          3.4mb
```

When dumping it, only 85 docs are extracted:

```
$ elasticdump \
  --input="http://localhost:9200/articles" \
  --output="/myfolder/elasticdump.json"
Mon, 04 Jul 2022 08:47:46 GMT | starting dump
Mon, 04 Jul 2022 08:47:48 GMT | got 85 objects from source elasticsearch (offset: 0)
Mon, 04 Jul 2022 08:47:48 GMT | sent 85 objects to destination file, wrote 85
Mon, 04 Jul 2022 08:47:48 GMT | got 0 objects from source elasticsearch (offset: 85)
Mon, 04 Jul 2022 08:47:48 GMT | Total Writes: 85
Mon, 04 Jul 2022 08:47:48 GMT | dump complete
```

The same 85-documents are seen when importing the dump into a new cluster:

```
$ curl localhost:9200/_cat/indices/articles?v=true
health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   articles lBbJ3ehNSuSBw8DSSmG9ew   1   1         85            0      3.7mb          1.9mb
```

Is there something wrong with the way I am using the tool?

**To Reproduce**

I don't have a process to reproduce

**Current behavior**

Only 85 documents are exported

**Expected behavior**

I expected my whole few thousands docs to be exported

**Comment by ferronrsmith** [comment]
I doubt there is something wrong, but it would hard to say. If the scroll returns 85 then that's what it got, unfortunately. Highly modified indices can sometimes have this effect, but it's very hard to say without debugging the actual index.
