### ISSUE TITLE
[FEATURE] Ability to remove the @id,@index,@type CSV columns

### ISSUE THREAD

**Issue by fmartinou** [elasticsearch-dump/elasticsearch-dump#890]
Hi,

First of all, thank you for this amazing tool 😃 

I'm trying to use elasticsearch-dump to dump some data from ES to CSV.
My goal is to compare this data to another referential (gathered from a SQL DB).

My problem is that I don't want the CSV to contain the columns @id,@index and @type.
I've played with all the current CSV options without any success.

Using a transform option, I can achieve to get rid of the values but the commas are still there.
Example of transform to get rid of @id,@index and @type values
```js
module.exports = function (doc, options) {
  delete doc._index;
  delete doc._id;
  delete doc._type;
};
```

But the columns are still included
```
id,created,amount_value,amount_currency,@id,@index,@type
0259760a4bb040bda055211f210949d5,1650537368000,8120,EUR,,,
03bf5b479b264f308d1b567a14ec2a28,1649750608000,9992,EUR,,,
```

I think an option to include/exclude these columns would be useful.

Maybe based on the current `--csvIdColumn`, `csvIndexColumn`, `csvTypeColumn` options?
A `null` value could mean not to include them?

**Comment by ferronrsmith** [comment]
The ability to remove these fields from the export correct ?

**Comment by ferronrsmith** [comment]
Added a new option `--csvIgnoreAutoColumns`

https://github.com/elasticsearch-dump/elasticsearch-dump/pull/891

Test and let me know if this is what you desire
