### ISSUE TITLE
[BUG] certain range of number in ES is converted to 9223372036854776000 unexpectedly.

### ISSUE THREAD

**Issue by jinwookh** [elasticsearch-dump/elasticsearch-dump#897]
**Context**
- ElasticDump version : 6.87.0
- Elasticsearch version : 7.3.2 
- Node.js version : v12.11.0
- Full command example:
`elasticdump --input=http://127.0.0.1:9200/test1234 --output=dumped.json`
Above command is just example, which bug can be reproduced with any command with specific data.

**Describe the bug**
Max value of Long, which is 9223372036854775807, is converted to 9223372036854776000 unexpectedly.

**To Reproduce**
1. create any index in es
2. create document which has value of `9223372036854775807` with any field
3. use elasticdump with the input of above index
4. check the output. 
`9223372036854776000` is shown instead of `9223372036854775807`.

**Expected behavior**
9223372036854775807 should be written as output, since it is the exact number stored in input.

**Screenshots**
![image](https://user-images.githubusercontent.com/31182783/179434445-1e878a23-c1cc-4183-8b0a-074fd555138e.png)

![image](https://user-images.githubusercontent.com/31182783/179434426-e481d009-47d9-4524-8af5-29f7275bd6ca.png)

**Additional context**
https://stackoverflow.com/questions/8104391/why-do-javascript-converts-some-number-values-automatically
Perhaps this happens because the elasticdump uses javascript number type(bigint type?) when dealing numbers.

**Comment by ferronrsmith** [comment]
It's over the maximum number that node supports, so rounding starts to occur


<img width="290" alt="Screen Shot 2022-07-19 at 4 48 55 AM" src="https://user-images.githubusercontent.com/159764/179708771-82ef1ceb-6797-4ff7-919c-509f864d3667.png">


That's where the `--support-big-int` & `--big-int-fields` flag come in handy. Read the docs and you should be fine.
