### ISSUE TITLE
[FEATURE] supply arm64 image

### ISSUE THREAD

**Issue by lusson-luo** [elasticsearch-dump/elasticsearch-dump#898]
**Is your feature request related to a problem? Please describe.**
i want elasticdump to run on arm server. now i clone code on arm server and build it. i want supply official arm64 image.
supply arm64 image in https://hub.docker.com/r/elasticdump/elasticsearch-dump/tags

**Describe the solution you'd like**
supply official arm64 image in https://hub.docker.com/r/elasticdump/elasticsearch-dump/tags

**Describe alternatives you've considered**
 now i clone code on arm server and build it.

**Give some examples of implementations**
in arm server，and run 'docker build -f dockerfile . -t xxx', and push to hub.docker, off cause, use ci is petty good

**Comment by ferronrsmith** [comment]
I can't support this since I don't use arm. Docker doesn't support autobuilds for OpenSource projects anymore. If I could I would, but I can't sorry.

**Comment by kbanka** [comment]
@ferronrsmith it seems your project utilizes now github actions, are you fine to contribue a dockerhub release workflow for both amd64/arm64 archs (using qemu/docker buildx)?

**Comment by ferronrsmith** [comment]
arm64 support is now available in the latest version of elasticsearch-dump
