### ISSUE TITLE
[FEATURE] Support multisearch for search requests

### ISSUE THREAD

**Issue by gustavom2998** [elasticsearch-dump/elasticsearch-dump#899]
**Is your feature request related to a problem? Please describe.**
Currently, we don't have any documented support for using searchBody to perform a search request using the multisearch API. I've looked through the documentation and havn't found an obvious way to send a /_msearch request.

**Describe the solution you'd like**
An optional flag `--msearch` flag or some method to override the default /search request that is performed.
This would use the the search json specified with `--searchBody` to filter the data before exporting with the multisearch API.

**Describe alternatives you've considered**
I've tried the following approach but that didn't seem to work.
```
elasticdump \
    --input "http://{ip}:{port}/_msearch" \
    --input-index="example-index" \
    --output="csv://local.csv" \
    --searchBody="{\"query\":{\"match_all\":{}}}" \
    --debug
```

I've also read through the documentation and looked at the articles but havn't seen this being performed.

Another alternative to actually implemented this would be to update the documentation to specify, if this is possible, how to perform the operation. 

**Give some examples of implementations**
If there is an easy way to do this, I'd be happy to update the documentation with a use case and some context.

**Additional context**

**Comment by gustavom2998** [comment]
Any help/suggestion to get this to work?

**Comment by ferronrsmith** [comment]
You can create a fork and implement the feature. The problem is the search 
APis weren't designed for large sets of data (You can have a look at the `max_result_window`)
To circumvent that the scroll APIs were designed with a scroll context instead of offset logic.
