### ISSUE TITLE
[BUG] Elasticdump import from file reports success, but no indexes are created

### ISSUE THREAD

**Issue by cawwot** [elasticsearch-dump/elasticsearch-dump#900]
**Context**
- ElasticDump version: docker :latest (sha256:72cbb126d31f4c2bf5211517a7eabccae5b141b7104444406352dd1a5444998c)
- Elasticsearch version: 7.17.5
- Node.js version: docker
- Full command you are having issue with: `elasticdump --output="10.85.5.241:9200" --input="/es/automation-292022-angular-sum.json"`
- A data-set you can share publicly which reproduces the problem: 
This is the contents of the json file:

`{"_index":"automation-292022-angular-sum","_type":"_doc","_id":"U2Im334BbvWmrVvVsC5-","_score":1,"_source":{"testId":"a67182b0bb2a7e28112197be04a4ae19","timeStamp":"2022-02-09T15:41:53.129Z","tests":184,"passes":175,"fails":9,"duration":8.223,"package":"VL-Integration-UI"}}
{"_index":"automation-292022-angular-sum","_type":"_doc","_id":"DmIo334BbvWmrVvVJS8R","_score":1,"_source":{"testId":"3f71d0fd1298276149af585111e7b992","timeStamp":"2022-02-09T15:43:21.980Z","tests":184,"passes":177,"fails":7,"duration":6.905,"package":"VL-Integration-UI"}}`

**Describe the bug**
No errors are reported when dumping the export to ES, but no indices get created.

**To Reproduce**
1. Start docker container with `docker run --rm -ti -v /home/centos/es:/es:ro elasticdump/elasticsearch-dump /bin/bash`
2. Run elasticdump in container `elasticdump --output="10.85.5.241:9200" --input="/es/automation-292022-angular-sum.json"`
3. Note run log `root@75fc11baa480:/# elasticdump --output="10.85.5.241:9200/" --input="/es/automation-292022-angular-sum.json" --debug
Wed, 27 Jul 2022 16:11:22 GMT | starting dump
Wed, 27 Jul 2022 16:11:22 GMT | got 2 objects from source file (offset: 0)
Wed, 27 Jul 2022 16:11:22 GMT | sent 2 objects to destination file, wrote 2
Wed, 27 Jul 2022 16:11:22 GMT | got 0 objects from source file (offset: 2)
Wed, 27 Jul 2022 16:11:22 GMT | Total Writes: 2
Wed, 27 Jul 2022 16:11:22 GMT | dump complete`
5. Cat indices with `curl -klv -XGET  10.85.5.241:9200/_cat/indices/`
6. Note no index is created despite no errors in dump log: 
`[centos@ip-10-85-4-130 ~]$ curl -kl -XGET  10.85.5.241:9200/_cat/indices/
green open .geoip_databases            ydqp1shsQ_6CitOs4-q48A 1 0 40 0 37.5mb 37.5mb`
7. Elasticsearch log contains no entries from this time period

**Current behavior**
No error is produced even though _something_ happened...

**Expected behavior**
The index should be created and available when _cat'ing the indexes

**Comment by ferronrsmith** [comment]
Can't replicate. This seems to be an es issue and not a esdump issue.

```
green  open cars_index                    0umrWIp2QL6LSaCSfSOSjg 1 0 406 0   82kb   82kb
green  open another_index                 _myx1CnEQruElWu3znPYgg 1 0 500 0 60.8kb 60.8kb
yellow open automation-292022-angular-sum GYIB1vLpSEmtEQVaJrNqrw 5 1   2 0 11.5kb 11.5kb
green  open nested_index                  Ey3bFNBlQheJqtXNkrbpDg 1 0   1 0 46.6kb 46.6kb
```
