### ISSUE TITLE
[FEATURE] Dump and Load ES scripts 

### ISSUE THREAD

**Issue by dloiacono** [elasticsearch-dump/elasticsearch-dump#901]
**Is your feature request related to a problem? Please describe.**
There is the need to dump and load also ES scripts.
The scripts can be used into ES indexes.

**Describe the solution you'd like**
I would to add the missing type into the dump and load functionalities.

**Describe alternatives you've considered**
No other alternatives.

**Give some examples of implementations**
elasticdump \
  --input=http://production.es.com:9200/my_index \
  --output=http://staging.es.com:9200/my_index \
  --type=script

**Additional context**
[Add any other context or screenshots about the feature request here.](https://www.elastic.co/guide/en/elasticsearch/reference/current/get-stored-script-api.html)

**Comment by ferronrsmith** [comment]
#908
