### ISSUE TITLE
[FEATURE] csv from s3?

### ISSUE THREAD

**Issue by AlJohri** [elasticsearch-dump/elasticsearch-dump#905]
**Is your feature request related to a problem? Please describe.**

I want to use a CSV hosted on S3 but I'm not sure how to supply this parameter. Reading [this code](https://github.com/elasticsearch-dump/elasticsearch-dump/blob/master/lib/is-url.js#L14-L40) it looks like it only supports `csv://` or `s3://`. In addition the README states "csv:// prefix must be included to allow parsing of csv files".

**Describe the solution you'd like**
I want to be able to use a CSV hosted on S3.

**Describe alternatives you've considered**
Alternative is to download the CSV file first which works for now, but it would be great if it worked straight from S3.

**Give some examples of implementations**
Give some implementation example

**Additional context**

**Comment by ferronrsmith** [comment]
Transport are single operation. We don't support csv from s3, but it's not impossible. 

elasticdump supports a flattened csv format

**Comment by ferronrsmith** [comment]
There is just too much that would need to be done and currently i don't have the bandwidth or access to s3 to do this

**Comment by andremacola** [comment]
I was looking for this feature too. I had to create a shell script to upload with aws cli after the dump.

**Comment by andremacola** [comment]
@ferronrsmith , is there an option to upload the CSV to S3 instead of JSON? I just want to upload it, not interested in importing.

**Comment by ferronrsmith** [comment]
No there isn't an option to change the format to CSV and upload to s3
