### ISSUE TITLE
[FEATURE] Parameter for specifying BULK API operation

### ISSUE THREAD

**Issue by gustavom2998** [elasticsearch-dump/elasticsearch-dump#906]
**Is your feature request related to a problem? Please describe.**

Currently, I've managed to get updates working by specifying a transform that takes and ID field from the source and uses it as the document ID for Elasticsearch, and loading the doc as the source:
```bash
elasticdump \
    --input "test.json" \
    --output="http://host:port/index" \
    --transform="doc._source=Object.assign({},doc)" \
    --transform="doc._id=doc._source['id']" 
```

The data.json files contains the following structure:
```json
{"id":"1", "updated_field":"updated_value"}
```

The problem is that this option makes me overwrite the entire source for the document. I'd like to only update the updated_value provided in the JSON, and the fields that don't exist in the source JSON, I'd like them to remain unchaged in Elasticseach.

**Describe the solution you'd like**
 I was taking a look at the source code for Elasticdump and [found the part of the _data.js that apparently builds the payload](https://github.com/elasticsearch-dump/elasticsearch-dump/blob/6e43f0100a603989526cc2cd7cd34508ddf0faf4/lib/transports/__es__/_data.js#L120). The Bulk API call appears to be fixed as "index" type. It would be great if we could swap out the "index" in the actionMeta variable for a parameter.

This would allow users to provide the "update" Bulk API operation for example, that only updates the provided fields.

**Describe alternatives you've considered**
I tried to examine the code but I couldn't find a way to implement this myself. 

**Give some examples of implementations**
An optional flag `--bulkApiOperation` with defaults to "index" (so the default behavior would stay the same as-is) but can be changed to update to allow bulk updates using Elasticdump. 

**Additional context**

**Comment by gustavom2998** [comment]
I think adding the following change to the linked file, initializing the option with a default value and updating the relevant documentation may work:

```javascript
const actionMeta = { this.parent.options.bulkApiOperation=: {} } 
```

There are probably some other changes that need to be made but I'll probably need help from more experienced contributors with some pointers to how this may impact the project.

**Comment by ferronrsmith** [comment]
Sent PR, test and let me know if works for you.

**Comment by gustavom2998** [comment]
Thanks @ferronrsmith!

I cloned the branch and built the docker image locally. 

With the default value, everything worked normally.

Trying to use the `bulkAction='update'` I ran into some errors.
After consulting the [Bulk API doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html), I noticed that the second row of the request should be a partial document to index. 

So instead of the request body being sent as 
```json
{ "update" : { "_index" : "index_name" , "_id": "id" } }
{ "fieldA" : "valueA" }
```
It should be sent as 
```json
{ "update" : { "_index" : "index_name" , "_id": "id" } }
{"doc": {"fieldA":"valueA"} }
```

I've also tested this with the Index operation and using the "doc" option didn't appear to change the expected behaviour, so maybe we could use "doc" as the default way to provide values? 

I'm gonna try to adjust the code locally, test and confirm.

**Comment by ferronrsmith** [comment]
sure, let me know

**Comment by ferronrsmith** [comment]
btw I made the change.

**Comment by ferronrsmith** [comment]
let me know if the latest changes are good enough

**Comment by gustavom2998** [comment]
Hey @ferronrsmith - Just an update: I had made a change similar to yours but couldn't get it working locally, so I though my code had messed something up. I pulled in your change and rebuilt the image, and I'm still getting the same error:

```
Error Emitted => Cannot read property 'status' of undefined
```

I'm assuming it comes from this [line](https://github.com/elasticsearch-dump/elasticsearch-dump/blob/7a6ba068170cd468ce7cd905ac82b323ed295bd4/lib/transports/__es__/_data.js#L169) since it's the only reference to the property status I found.

 After taking a glance at your code, I assumed it could local error unrelated to Elasticdump, and maybe some depedency related issue. Any chance this could have been introduced by the code changes?

**Comment by ferronrsmith** [comment]
that's a miss on my part, thanks.

**Comment by ferronrsmith** [comment]
Get the latest and try again

**Comment by gustavom2998** [comment]
Tested and working locally with inserts (index) and update.
