### ISSUE TITLE
[BUG] Elasticdump fails with ERR_STREAM_PREMATURE_CLOSE with node.js 18.6/18.7

### ISSUE THREAD

**Issue by ikiril01** [elasticsearch-dump/elasticsearch-dump#909]
**Context**
- ElasticDump version: 6.84.1
- Elasticsearch version: 7.13.3
- Node.js version: 18.7.0
- Full command you are having issue with (with inputs and outputs): `elasticdump --input=<json_file> --output=<es_index> --limit=1000`

**Describe the bug**
When using newer versions of node.js  (we've seen this issue with `18.6.0` and `18.7.0`), elasticdump always fails when trying to write the last set of objects into ES with an `ERR_STREAM_PREMATURE_CLOSE` error. Older versions of node (e.g., `18.2.0`) don't have this issue.

**To Reproduce**
1. Install a newer version of node.js (we've seen this issue with `18.6.0` and `18.7.0`).
2. Run elasticdump to dump JSON into ES.

**Current behavior**
The dump always fails when attempting to ingest the last set of objects from the JSON file. E.g., 

```javascript
Tue, 23 Aug 2022 13:28:26 GMT | starting dump
Tue, 23 Aug 2022 13:28:26 GMT | got 1000 objects from source file (offset: 0)
Tue, 23 Aug 2022 13:28:31 GMT | sent 1000 objects to destination elasticsearch, wrote 1000
Tue, 23 Aug 2022 13:28:31 GMT | got 1000 objects from source file (offset: 1000)
Tue, 23 Aug 2022 13:28:34 GMT | sent 1000 objects to destination elasticsearch, wrote 1000
Tue, 23 Aug 2022 13:28:34 GMT | got 960 objects from source file (offset: 2000)
Tue, 23 Aug 2022 13:28:34 GMT | Error Emitted => {
  msg: 'Pipeline failed',
  err: Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
      at new NodeError (node:internal/errors:387:5)
      at Stream.<anonymous> (node:internal/streams/pipeline:352:14)
      at Stream.emit (node:events:525:35)
      at Stream.emit (node:domain:489:12)
      at stream.destroy (/opt/homebrew/lib/node_modules/elasticdump/node_modules/through/index.js:84:12)
      at _end (/opt/homebrew/lib/node_modules/elasticdump/node_modules/through/index.js:67:14)
      at stream.end (/opt/homebrew/lib/node_modules/elasticdump/node_modules/through/index.js:74:5)
      at PassThrough.onend (node:internal/streams/readable:705:10)
      at Object.onceWrapper (node:events:627:28)
      at PassThrough.emit (node:events:525:35) {
    code: 'ERR_STREAM_PREMATURE_CLOSE'
  }
}
```

**Expected behavior**
The JSON -> ES dump succeeds without issues.

**Comment by manzonif** [comment]
same error with:
multielasticdump --direction=load --input=D:\\es --output=http://localhost:9200multielasticdump --direction=load --input=D:\es --output=http://localhost:9200/

**Comment by ferronrsmith** [comment]
That's an upstream but in nodejs. Nothing I can do about this.

**Comment by manzonif** [comment]
In nodejs v 18.2 work correctly.

Any workaround?

**Comment by ferronrsmith** [comment]
test and let me know if you're still getting the issue https://github.com/elasticsearch-dump/elasticsearch-dump/pull/930

**Comment by manzonif** [comment]
Unfortunately yes.
node-v18.11.0-x64
elasticdump 6.92

```javascript
C:\Users\Fausto>elasticdump --input=D:/es/categories.json --output=http://localhost:9200/categories
Sat, 22 Oct 2022 08:22:23 GMT | starting dump
Sat, 22 Oct 2022 08:22:23 GMT | got 100 objects from source file (offset: 0)
Sat, 22 Oct 2022 08:22:26 GMT | sent 100 objects to destination elasticsearch, wrote 100
Sat, 22 Oct 2022 08:22:26 GMT | got 100 objects from source file (offset: 100)
Sat, 22 Oct 2022 08:22:28 GMT | sent 100 objects to destination elasticsearch, wrote 100
Sat, 22 Oct 2022 08:22:28 GMT | got 56 objects from source file (offset: 200)
Sat, 22 Oct 2022 08:22:28 GMT | Error Emitted => {
  msg: 'Pipeline failed',
  err: Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
      at new NodeError (node:internal/errors:387:5)
      at Stream.<anonymous> (node:internal/streams/pipeline:352:14)
      at Stream.emit (node:events:525:35)
      at Stream.emit (node:domain:489:12)
      at stream.destroy (C:\Users\Fausto\AppData\Roaming\npm\node_modules\elasticdump\node_modules\through\index.js:84:12)
      at _end (C:\Users\Fausto\AppData\Roaming\npm\node_modules\elasticdump\node_modules\through\index.js:67:14)
      at stream.end (C:\Users\Fausto\AppData\Roaming\npm\node_modules\elasticdump\node_modules\through\index.js:74:5)
      at PassThrough.onend (node:internal/streams/readable:705:10)
      at Object.onceWrapper (node:events:627:28)
      at PassThrough.emit (node:events:525:35) {
    code: 'ERR_STREAM_PREMATURE_CLOSE'
  }
}
Sat, 22 Oct 2022 08:22:28 GMT | Error Emitted => {
  msg: 'Pipeline failed',
  err: Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
      at new NodeError (node:internal/errors:387:5)
      at Stream.<anonymous> (node:internal/streams/pipeline:352:14)
      at Stream.emit (node:events:525:35)
      at Stream.emit (node:domain:489:12)
      at stream.destroy (C:\Users\Fausto\AppData\Roaming\npm\node_modules\elasticdump\node_modules\through\index.js:84:12)
      at _end (C:\Users\Fausto\AppData\Roaming\npm\node_modules\elasticdump\node_modules\through\index.js:67:14)
      at stream.end (C:\Users\Fausto\AppData\Roaming\npm\node_modules\elasticdump\node_modules\through\index.js:74:5)
      at PassThrough.onend (node:internal/streams/readable:705:10)
      at Object.onceWrapper (node:events:627:28)
      at PassThrough.emit (node:events:525:35) {
    code: 'ERR_STREAM_PREMATURE_CLOSE'
  }
}
Sat, 22 Oct 2022 08:22:28 GMT | Total Writes: 0
Sat, 22 Oct 2022 08:22:28 GMT | dump ended with error (get phase) => Error: {
  msg: 'Pipeline failed',
  err: Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
      at new NodeError (node:internal/errors:387:5)
      at Stream.<anonymous> (node:internal/streams/pipeline:352:14)
      at Stream.emit (node:events:525:35)
      at Stream.emit (node:domain:489:12)
      at stream.destroy (C:\Users\Fausto\AppData\Roaming\npm\node_modules\elasticdump\node_modules\through\index.js:84:12)
      at _end (C:\Users\Fausto\AppData\Roaming\npm\node_modules\elasticdump\node_modules\through\index.js:67:14)
      at stream.end (C:\Users\Fausto\AppData\Roaming\npm\node_modules\elasticdump\node_modules\through\index.js:74:5)
      at PassThrough.onend (node:internal/streams/readable:705:10)
      at Object.onceWrapper (node:events:627:28)
      at PassThrough.emit (node:events:525:35) {
    code: 'ERR_STREAM_PREMATURE_CLOSE'
  }
}
```

**Comment by manzonif** [comment]
If it can be useful, I noticed that,
 with the 
`elasticdump --input=D:/es/categories.json --output=http://localhost:9200/categories`
 command, the index is still loaded,
 while with the 
`multielasticdump --direction=load --input=D:\\es --output=http://localhost:9200multielasticdump --direction=load --input=D:\es --output=http://localhost:9200/`
 command, no index is loaded.

**Comment by ferronrsmith** [comment]
You're testing the wrong branch. There is no pipeline in the branch supploied

> Unfortunately yes. node-v18.11.0-x64 elasticdump 6.92
> 
> ```js
> C:\Users\Fausto>elasticdump --input=D:/es/categories.json --output=http://localhost:9200/categories
> Sat, 22 Oct 2022 08:22:23 GMT | starting dump
> Sat, 22 Oct 2022 08:22:23 GMT | got 100 objects from source file (offset: 0)
> Sat, 22 Oct 2022 08:22:26 GMT | sent 100 objects to destination elasticsearch, wrote 100
> Sat, 22 Oct 2022 08:22:26 GMT | got 100 objects from source file (offset: 100)
> Sat, 22 Oct 2022 08:22:28 GMT | sent 100 objects to destination elasticsearch, wrote 100
> Sat, 22 Oct 2022 08:22:28 GMT | got 56 objects from source file (offset: 200)
> Sat, 22 Oct 2022 08:22:28 GMT | Error Emitted => {
>   msg: 'Pipeline failed',
>   err: Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
>       at new NodeError (node:internal/errors:387:5)
>       at Stream.<anonymous> (node:internal/streams/pipeline:352:14)
>       at Stream.emit (node:events:525:35)
>       at Stream.emit (node:domain:489:12)
>       at stream.destroy (C:\Users\Fausto\AppData\Roaming\npm\node_modules\elasticdump\node_modules\through\index.js:84:12)
>       at _end (C:\Users\Fausto\AppData\Roaming\npm\node_modules\elasticdump\node_modules\through\index.js:67:14)
>       at stream.end (C:\Users\Fausto\AppData\Roaming\npm\node_modules\elasticdump\node_modules\through\index.js:74:5)
>       at PassThrough.onend (node:internal/streams/readable:705:10)
>       at Object.onceWrapper (node:events:627:28)
>       at PassThrough.emit (node:events:525:35) {
>     code: 'ERR_STREAM_PREMATURE_CLOSE'
>   }
> }
> Sat, 22 Oct 2022 08:22:28 GMT | Error Emitted => {
>   msg: 'Pipeline failed',
>   err: Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
>       at new NodeError (node:internal/errors:387:5)
>       at Stream.<anonymous> (node:internal/streams/pipeline:352:14)
>       at Stream.emit (node:events:525:35)
>       at Stream.emit (node:domain:489:12)
>       at stream.destroy (C:\Users\Fausto\AppData\Roaming\npm\node_modules\elasticdump\node_modules\through\index.js:84:12)
>       at _end (C:\Users\Fausto\AppData\Roaming\npm\node_modules\elasticdump\node_modules\through\index.js:67:14)
>       at stream.end (C:\Users\Fausto\AppData\Roaming\npm\node_modules\elasticdump\node_modules\through\index.js:74:5)
>       at PassThrough.onend (node:internal/streams/readable:705:10)
>       at Object.onceWrapper (node:events:627:28)
>       at PassThrough.emit (node:events:525:35) {
>     code: 'ERR_STREAM_PREMATURE_CLOSE'
>   }
> }
> Sat, 22 Oct 2022 08:22:28 GMT | Total Writes: 0
> Sat, 22 Oct 2022 08:22:28 GMT | dump ended with error (get phase) => Error: {
>   msg: 'Pipeline failed',
>   err: Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
>       at new NodeError (node:internal/errors:387:5)
>       at Stream.<anonymous> (node:internal/streams/pipeline:352:14)
>       at Stream.emit (node:events:525:35)
>       at Stream.emit (node:domain:489:12)
>       at stream.destroy (C:\Users\Fausto\AppData\Roaming\npm\node_modules\elasticdump\node_modules\through\index.js:84:12)
>       at _end (C:\Users\Fausto\AppData\Roaming\npm\node_modules\elasticdump\node_modules\through\index.js:67:14)
>       at stream.end (C:\Users\Fausto\AppData\Roaming\npm\node_modules\elasticdump\node_modules\through\index.js:74:5)
>       at PassThrough.onend (node:internal/streams/readable:705:10)
>       at Object.onceWrapper (node:events:627:28)
>       at PassThrough.emit (node:events:525:35) {
>     code: 'ERR_STREAM_PREMATURE_CLOSE'
>   }
> }
> ```

**Comment by ferronrsmith** [comment]
If you could supply a sample data-set that would help. multielasticdump passes additional params that might be causing failures

> If it can be useful, I noticed that, with the `elasticdump --input=D:/es/categories.json --output=http://localhost:9200/categories` command, the index is still loaded, while with the `multielasticdump --direction=load --input=D:/es --output=http://localhost:9200` command, no index is loaded.

**Comment by manzonif** [comment]
> You're testing the wrong branch. There is no pipeline in the branch supploied

Sorry, my bad.

`npm install "https://github.com/elasticsearch-dump/elasticsearch-dump.git#feature/pipeline-to-pipe" --save -g`

work like a charm.

**Comment by manzonif** [comment]
> If you could supply a sample data-set that would help. multielasticdump passes additional params that might be causing failures
> 
> > If it can be useful, I noticed that, with the `elasticdump --input=D:/es/categories.json --output=http://localhost:9200/categories` command, the index is still loaded, while with the `multielasticdump --direction=load --input=D:/es --output=http://localhost:9200` command, no index is loaded.


Here a sample of one of my dumped index:
[sample.zip](https://github.com/elasticsearch-dump/elasticsearch-dump/files/9845804/sample.zip)

**Comment by ferronrsmith** [comment]
i haven't used windows in years and I would rather like to avoid OS issues. Switching back to pipe works for me as well.
