### ISSUE TITLE
[FEATURE] Continuous polling

### ISSUE THREAD

**Issue by NikitaGl** [elasticsearch-dump/elasticsearch-dump#910]
**Is your feature request related to a problem? Please describe.**
Sometimes there is a case, when you need to switch to another ES cluster, but stopping your ingest and moving existing data is not an option, that must be a live transition. 

**Describe the solution you'd like**
It would be wonderful to have a feature to set up copying index data between source and target for a continuous period. 

**Describe alternatives you've considered**
As an alternative, I see some setup based on logging tool, like fluentd, or logstash.

**Give some examples of implementations**
For example, by adding a flag `--continuous-transfer=true` and `--continuous-refresh-interval=<time in seconds>`

**Comment by ferronrsmith** [comment]
This is out of the scope of this tool.
