### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sesibhushan121** [elasticsearch-dump/elasticsearch-dump#911]
Hi team, we are facing this issue on elastic dump, we have configure in my kubernetes cluster, I have to dump elastic data to s3, so before that we are generating the file ,...facing the issue 

Tue, 23 Aug 2022 09:31:56 GMT | starting dump
Tue, 23 Aug 2022 09:32:16 GMT | Error Emitted => getaddrinfo ENOTFOUND http
Tue, 23 Aug 2022 09:32:16 GMT | Error Emitted => getaddrinfo ENOTFOUND http
Tue, 23 Aug 2022 09:32:16 GMT | Total Writes: 0
Tue, 23 Aug 2022 09:32:16 GMT | dump ended with error (get phase) => Error: getaddrinfo ENOTFOUND http

**Comment by sesibhushan121** [comment]
Hi, my issue is not resolved

**Comment by sesibhushan121** [comment]
Hello @ferronrsmith my issue is not resolved yet

**Comment by ferronrsmith** [comment]
> A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What was the url? What steps will reproduce the issue? What OS experience the problem? All these details will help to fix any potential bugs as soon as possible.

**Comment by sesibhushan121** [comment]
we are facing this issue on elastic dump, present in dev env environment, we have configure in my kubernetes cluster in Amazon EKS ,we have installed EFK in dev cluster and I want to dump elastic data to s3, so we have installed elastic dump in that env, After that when im giving the command to before that we are generating the file ,...facing the issue
-> elasticdump \
>   --input=http://elastic:MaralTNIJefffgrtuy@http/://ggtbtgtacc87d1vrvrg1968grgr-vrgtg26555vgrvrvr.us-east-1.elb.amazonaws.com:9200/data-source \
>   --output=/data/vfef33ddrf.json \
>   --type=data
Tue, 23 Aug 2022 09:31:56 GMT | starting dump
Tue, 23 Aug 2022 09:32:16 GMT | Error Emitted => getaddrinfo ENOTFOUND http
Tue, 23 Aug 2022 09:32:16 GMT | Error Emitted => getaddrinfo ENOTFOUND http
Tue, 23 Aug 2022 09:32:16 GMT | Total Writes: 0
Tue, 23 Aug 2022 09:32:16 GMT | dump ended with error (get phase) => Error: getaddrinfo ENOTFOUND http

**Comment by ferronrsmith** [comment]
ENOTFOUND is dns/network issue. Essentially, it's unable to reach the URL you're specifying. Try access the container and then try pinging the ES instance. If you can't ping it then you have a network problem

**Comment by sesibhushan121** [comment]
@ferronrsmith can u suggest any doc in kubernetes level for elastic dump to s3

**Comment by ferronrsmith** [comment]
There is no documentation, as this isn't an elasticdump issue. This is purely a container network issue. Some googling will help, but beyond that there isn't much I can help with. 

1. connect to a pod
2. try communicating with the ES service
3. try communicating with the S3 service
4. fix communication issue and then repeat steps 1-3
