### ISSUE TITLE
[docs] elasticsearch-dump support es5 to es7？

### ISSUE THREAD

**Issue by SwimSweet** [elasticsearch-dump/elasticsearch-dump#912]
I need to upgrade elasticsearch5 to elasticsearch7. Accrording to Elasticsearch document [https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html](url) , I must use reindex to migrate data from old cluster to new cluster.After verification, the reindex performance does not meet My requirements.
I'm looking for a product that satisfies migration from version 5 to 7 with good performance.

**Comment by SwimSweet** [comment]
@ferronrsmith  hi. elasticsearch-dump support migrating data from elasticsearch 5 to elasticsearch 7 ? thx.

**Comment by ferronrsmith** [comment]
Data yes, mappings/settings no. Information is provided in the documentation
