### ISSUE TITLE
is elasticsearch-dump able to dump indice in ultrawarm/cold tier from opensearch? 

### ISSUE THREAD

**Issue by wttat** [elasticsearch-dump/elasticsearch-dump#913]
Hi all,
I am looking for tools that could backup my opensearch indices in AWS, I am wondering if elasticsearch-dump could directly bakcup the indices which in ultrawarm/cold tier in opensearch? 
if its not working for cold storage, is that means i have to move the cold indices back to ultrawarm/warm back first?

**Comment by ferronrsmith** [comment]
I don't know much about AWS Storage types, but if you can access it via the endpoint it can be backed up.
