### ISSUE TITLE
Issues with indices that has special characters like +

### ISSUE THREAD

**Issue by itnazeer** [elasticsearch-dump/elasticsearch-dump#914]
I am able to dump and load indices with no issues however, the indices that have a special character like + are getting converted to %
Original: z+al_afayr0ardawtanwoab4vag81w__zh
After Load: z%al_afayr0ardawtanwoab4vag81w__zh

**Comment by ferronrsmith** [comment]
Seems like the encoding being returned from ES. We don't do any modifications of values unless directly specified

**Comment by itnazeer** [comment]
Is there any option so that the index name does not change through elasticdump?

**Comment by ferronrsmith** [comment]
https://discuss.elastic.co/t/how-to-delete-index-having-special-characters-in-name/235060 

Seems someone had a similar issue.
