### ISSUE TITLE
[FEATURE] - Incremental Migration with the tool

### ISSUE THREAD

**Issue by shashimahawaththa** [elasticsearch-dump/elasticsearch-dump#915]
Hi ferronrsmith,

It is great to use your tool and I think it will be great if we can use tool for incremental migration(0 down time server side)
If I explain my scenario, I have on-promise elasticsearch cluster and I'm in the process of migrating it to AWS ES instances. Your tool help me lot performing that task. For lower environments with a down time we can performance the migration without any issue. but when it comes to production we need to perform the migration as incremental upgrade, because some of our indexes are quit large in size as some indexes are 70Gb in size, hence we need 1 week to migrate some of the indexes. During that period we can't shut down our services.

I was wondering whether '--offset' option can help in this case where we can plan migration in to 2 steps as,
1 step - Migrate initial data as it take 1 week for some indexes without any downtime.
2 step - once complete with 1st step, down the services in on-promise-end and start the migration process starting the last offset of 1st step for that specific index.

but once I tried to do that got below error,
![image](https://user-images.githubusercontent.com/39517229/191260939-6d45ed72-40d0-47f6-9ed2-a0d7d332df1b.png)

Appreciate your help here in anyways! Thanks!

**Comment by shashimahawaththa** [comment]
Hi ferronrsmith,

Thank you for your quick reply.

You mean that tool itself has capability to sort and filter data by segments?

**Comment by ferronrsmith** [comment]
no the tool doesn't have this functionality. It does support a `searchBody` which can be used to filter/sort data by segments, but the basically dependent on how the data is structured in the index. The scroll api, which this library use doesn't support offsetting due to performance reasons.
