### ISSUE TITLE
No Such file issue when trying to load indexes

### ISSUE THREAD

**Issue by shashimahawaththa** [elasticsearch-dump/elasticsearch-dump#918]
Hello,

I'm trying to backup and restore my es instance from one server to another in compress mode,

dump command used,
nohup  multielasticdump --direction=dump --input=aaa --output=/content/bce/elastic-dump/backup_9_22 --limit=10000 --noRefresh --fsCompress --overwrite=true > ces_indexes_9_22.log 2>&1 &

above command successfully backup 70GB index data to specified folder within 3 hours. Then I was trying to restore those data my other server and below is the command that I used,

nohup multielasticdump --direction=load --input=/content/bce/elastic-dump/backup_9_22 --output=bbbb --overwrite=true > ces_indexes_9_23_load.log 2>&1 &

and getting below error,
![image](https://user-images.githubusercontent.com/39517229/191885922-211706e6-effa-42f8-b68d-9118763754b7.png)

below are the total indexes which were backup,
![image](https://user-images.githubusercontent.com/39517229/191886126-c3aee236-edfe-4f64-973e-351dd9371c7b.png)

**Comment by ferronrsmith** [comment]
That's because the `fsCompress` flag is missing. So it's looking for a suffix of `.json instead of ` .json.gz'
