### ISSUE TITLE
[BUG] - Dump is completing without backing up all data

### ISSUE THREAD

**Issue by shashimahawaththa** [elasticsearch-dump/elasticsearch-dump#919]
Hello,

Below is the index that I'm trying to migrate using backup and restore process which is huge in size 38GB,
***yellow open ces_articles_1.17   5 1 263551842 2854819  38.2gb  38.2gb***

Below is the used command using multielasticdump,

```
nohup  multielasticdump --direction=dump --match='ces_articles_1.17' --input=<SOURCE_URL> --output=/content/bce/elastic-dump/backup_9_30 --limit=3000 --noRefresh --fsCompress --overwrite=true --includeType='data'> ces_indexes_9_30.log 2>&1 &
```

Below is the log output for starting and end entries,

Starting entries,

```bash
Fri, 30 Sep 2022 03:45:32 GMT | We are performing : dump
Fri, 30 Sep 2022 03:45:32 GMT | options: {"debug":true,"parallel":8,"match":"ces_articles_1.17","order":"asc","input":"<SOURCE_URL>","output":"/content/bce/elastic-dump/backup_9_30","scrollId":null,"scrollTime":"10m","scroll-with-post":false,"timeout":null,"limit":3000,"offset":0,"size":-1,"direction":"dump","support-big-int":false,"big-int-fields":"","ignoreAnalyzer":true,"ignoreChildError":true,"ignoreData":false,"ignoreMapping":true,"ignoreSettings":true,"ignoreTemplate":true,"ignoreAlias":true,"ignoreType":true,"includeType":"data","interval":1000,"delete":false,"prefix":"","suffix":"","transform":null,"headers":null,"searchBody":null,"searchWithTemplate":null,"cert":null,"key":null,"pass":null,"ca":null,"tlsAuth":false,"input-cert":null,"input-key":null,"input-pass":null,"input-ca":null,"output-cert":null,"output-key":null,"output-pass":null,"output-ca":null,"httpAuthFile":null,"concurrency":1,"carryoverConcurrencyCount":true,"intervalCap":5,"concurrencyInterval":5000,"overwrite":true,"fsCompress":true,"awsChain":false,"awsAccessKeyId":null,"awsSecretAccessKey":null,"awsIniFileProfile":null,"awsService":null,"awsRegion":null,"awsUrlRegex":null,"s3AccessKeyId":null,"s3SecretAccessKey":null,"s3Region":null,"s3Endpoint":null,"s3SSLEnabled":true,"s3ForcePathStyle":false,"s3Compress":false,"s3ServerSideEncryption":null,"s3SSEKMSKeyId":null,"s3ACL":null,"quiet":false}
Fri, 30 Sep 2022 03:45:32 GMT [debug] | GET /_aliases
Fri, 30 Sep 2022 03:45:32 GMT [debug] | GET /_aliases -> 200 OK
Fri, 30 Sep 2022 03:45:32 GMT | dumping <SOURCE_URL>/ces_articles_1.17 to /content/bce/elastic-dump/backup_9_30/ces_articles_1.17.json.gz
Fri, 30 Sep 2022 03:45:32 GMT [debug] | fork: /usr/lib/node_modules/elasticdump/bin/elasticdump --type=data,--input=<SOURCE_URL>/ces_articles_1.17,--output=/content/bce/elastic-dump/backup_9_30/ces_articles_1.17.json.gz,--scrollId=null,--scrollTime=10m,--limit=3000,--offset=0,--size=-1,--searchBody=null,--searchWithTemplate=null,--prefix=,--suffix=,--support-big-int=false,--big-int-fields=,--headers=null,--cert=null,--key=null,--pass=null,--ca=null,--tlsAuth=false,--input-cert=null,--input-key=null,--input-pass=null,--input-ca=null,--output-cert=null,--output-key=null,--output-pass=null,--output-ca=null,--httpAuthFile=null,--concurrency=1,--carryoverConcurrencyCount=true,--intervalCap=5,--concurrencyInterval=5000,--overwrite=true,--fsCompress=true,--awsChain=false,--awsAccessKeyId=null,--awsSecretAccessKey=null,--awsIniFileProfile=null,--awsService=null,--awsRegion=null,--awsUrlRegex=null,--s3AccessKeyId=null,--s3SecretAccessKey=null,--s3Region=null,--s3Endpoint=null,--s3SSLEnabled=true,--s3ForcePathStyle=false,--s3Compress=false,--s3ServerSideEncryption=null,--s3SSEKMSKeyId=null,--s3ACL=null,--quiet=false,--scroll-with-post=false
```

Ending Entries,
```
Fri, 30 Sep 2022 04:12:31 GMT | sent 3000 objects to destination file, wrote 3000
Fri, 30 Sep 2022 04:12:34 GMT | got 3000 objects from source elasticsearch (offset: 1686000)
Fri, 30 Sep 2022 04:12:35 GMT | sent 3000 objects to destination file, wrote 3000
Fri, 30 Sep 2022 04:12:38 GMT | got 3000 objects from source elasticsearch (offset: 1689000)
Fri, 30 Sep 2022 04:12:39 GMT | sent 3000 objects to destination file, wrote 3000
Fri, 30 Sep 2022 04:12:42 GMT |  dumping all done
Fri, 30 Sep 2022 04:12:42 GMT |  bye
```

Here the issue is, elastic dump is not backup all the data instead small portion of it and end the process without any issue. Could you plz assist me on this?
Or else plz suggest me an alternative solution for this migration, if dump is not supporting that much of size index migration.

Note: I managed to migrate index which is in size 9GB without any issue with dump tool, If you need I can provide that index migration statistics.

And one more question, is this the correct usage for elasticdump with --fsCompress 

```
nohup  elasticdump --input=<SOURCE_URL>/ces_articles_1.17 --output=/content/bce/elastic-dump/backup_9_30/ --limit=10000 --noRefresh --fsCompress --overwrite=true --type='data' > ces_indexes_9_30.log 2>&1 &`
```

**Comment by ferronrsmith** [comment]
Can you try dumping that index alone using **elasticdump** instead of **multielasticdump** . There is a known issue when dumping from sharded indices since the value shown in `_cat/indices` isn't what is returned by the scroll endpoint.

**Comment by shashimahawaththa** [comment]
yeah, I tried that option too, but without backing up full capacity, process is completed.
For an example Letz say for  "index a" we have total documents 120009378 which is size in 20GB
it backup data up to 100000 and complete the backup without any error. 

Note: I  have increased  --max-old-space-size=40GB and server has remaining capacity up to 48GB

**Comment by ferronrsmith** [comment]
Also have you tried increasing your `scrollTime`

**Comment by shashimahawaththa** [comment]
By looking at above attached document, I don't process is exceeding scroll time which is 10m by default,
![image](https://user-images.githubusercontent.com/39517229/193522968-cb4f1911-8607-4579-9471-b7a96b0a127b.png)

**Comment by shashimahawaththa** [comment]
BTW could you send me the command that I need to use, when trying to backup index with --fsCompress using elasticdump. I just want to double check whether my command is correct.

**Comment by ferronrsmith** [comment]
elasticdump --fsCompress --output=http://localhost:9200/test --type=data --input=test.json.gz

**Comment by shashimahawaththa** [comment]
let me use the above command first and let you know the result.

**Comment by shashimahawaththa** [comment]
**On-promise es index which need to be migrated to AWS ES,**
-------------------------
ces_sjf_articles - 5(Shards) - 0(Replicas) - 120009378(Total Documents) - 20.3gb(Index Size)

**Used Command,**
--------------

nohup elasticdump --fsCompress --limit=10000 --output=ces_sjf_articles.json.gz --type=data --overwrite=true --input=<SOURCE_URL>/ces_sjf_articles > ces_sjf_articles.log 2>&1 &

**Dump start log entries.**
--------------------------------------------------

Mon, 03 Oct 2022 09:49:53 GMT | starting dump
Mon, 03 Oct 2022 09:50:00 GMT | got 10000 objects from source elasticsearch (offset: 0)
Mon, 03 Oct 2022 09:50:04 GMT | sent 10000 objects to destination file, wrote 10000
Mon, 03 Oct 2022 09:50:12 GMT | got 10000 objects from source elasticsearch (offset: 10000)
Mon, 03 Oct 2022 09:50:14 GMT | sent 10000 objects to destination file, wrote 10000

**Dump last log entries.**
-------------------------------------------
Mon, 03 Oct 2022 10:09:00 GMT | sent 10000 objects to destination file, wrote 10000
Mon, 03 Oct 2022 10:09:08 GMT | got 10000 objects from source elasticsearch (offset: 1020000)
Mon, 03 Oct 2022 10:09:11 GMT | sent 10000 objects to destination file, wrote 10000
Mon, 03 Oct 2022 10:09:17 GMT | got 8587 objects from source elasticsearch (offset: 1030000)
Mon, 03 Oct 2022 10:09:19 GMT | sent 8587 objects to destination file, wrote 8587
Mon, 03 Oct 2022 10:09:19 GMT | got 0 objects from source elasticsearch (offset: 1038587)
Mon, 03 Oct 2022 10:09:19 GMT | Total Writes: 1038587
Mon, 03 Oct 2022 10:09:19 GMT | dump complete


According to above statistics, I'm trying to migrate large size index from on-promise es to aws es, Dump should complete with 120009378 documents in total, but according to logs, tool has backed up only 1038587 documents and finish the dump without any issue. 
I'm wondering why tool is not backing up total Documents even server has adequate capacity.

**Comment by ferronrsmith** [comment]
Is it possible to get a dump of the index for testing or a subset ?

**Comment by ferronrsmith** [comment]
```json
{
  "_scroll_id": "DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAALFlBONUMxU21YU29PSjJ0eE1xNjVKbVEAAAAAAAAADBZQTjVDMVNtWFNvT0oydHhNcTY1Sm1RAAAAAAAAAA0WUE41QzFTbVhTb09KMnR4TXE2NUptUQAAAAAAAAAOFlBONUMxU21YU29PSjJ0eE1xNjVKbVEAAAAAAAAADxZQTjVDMVNtWFNvT0oydHhNcTY1Sm1R",
  "took": 5,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 407,
    "max_score": 1,
    "hits": []
  }
}
```

One thing to note is that first request will return the total number of hits, which is then used for subsequent request. I am curious to see what this value is. Is this something that you can debug ? I didn't add a debug statement for that in the code.

**Comment by ferronrsmith** [comment]
Hits is the total results that match the query sent to the ES indices. The total, might be a cluster count, it's very hard to say

**Comment by shashimahawaththa** [comment]
> 

![image](https://user-images.githubusercontent.com/39517229/193734181-4f23473b-e817-4ffc-9b9d-0497b71d1264.png)
Still same result

**Comment by ferronrsmith** [comment]
issue seems to be on ES side. **elasticdump** can't go beyond the hit total. I also don't think the 120m represents actually documents, it could be a summation of some sort, but without more information it's hard to say

**Comment by shashimahawaththa** [comment]
Yeah, understood Ferron. Thank you so much for your time on this.

**Comment by ferronrsmith** [comment]
Check this article. I think they elaborate more on this : 

https://www.anycodings.com/1questions/2779838/elastic-search-count-api-showing-incorrect-total-document-count-for-index


Another important thing to note - https://discuss.elastic.co/t/incorrect-doc-count-vs-index-total-returns-in-es/222182
