### ISSUE TITLE
[BUG] - Large index got stuck at the middle while backing up

### ISSUE THREAD

**Issue by shashimahawaththa** [elasticsearch-dump/elasticsearch-dump#921]
Hello,

i'm backing up large index which is size in 38.2gb and total hit count is 2670969
![image](https://user-images.githubusercontent.com/39517229/193987719-32449550-76f0-40db-af2d-57a184a23c6f.png)

I'm using backup and restore process of elastic-dum with --fsCompress to migrate the index from on-promise to AWS es. While backing up the index, process got hold as below as I attached the log snipet,
![image](https://user-images.githubusercontent.com/39517229/193988051-4fc35520-d157-4c1e-80e0-665a84617fc1.png)

Any idea on the issue? Can I use --fileSize option with this? if so what are the commands for import and export

Thanks.

**Comment by shashimahawaththa** [comment]
With --fileSize option I managed to dump all the documents,
![image](https://user-images.githubusercontent.com/39517229/193996741-da3f7337-bcc5-495b-bdc5-6efa2e225b25.png)

My dump files are look like below,
![image](https://user-images.githubusercontent.com/39517229/193996846-d9744182-0f71-4fa6-9e72-bc0ebde4dc7f.png)

Is there any way that we can restore these files at once or do we need to do it one by one?

**Comment by ferronrsmith** [comment]
Filesize is the perfect option to limit the site.

**Comment by shashimahawaththa** [comment]
yeah but now I'm struggling how to load them to my AWS ES. could you plz provide me with command?

**Comment by ferronrsmith** [comment]
```bash
#!/bin/bash

FILES=($(ls *.gz | sort -V))
for filename in ${FILES[@]}; do
    elasticdump --input ${filename} --output=http://localhost:9200/cars
done
```

**Comment by ferronrsmith** [comment]
bash works

**Comment by shashimahawaththa** [comment]
Hello, 
Thanks for your help,
I was trying to execute the bash and caught in to below error,
![image](https://user-images.githubusercontent.com/39517229/194038512-74fe5d83-21d1-47f4-afde-7c5c32b03517.png)
