### ISSUE TITLE
Hello, Trying to execute the bash and caught in to below error

### ISSUE THREAD

**Issue by shashimahawaththa** [elasticsearch-dump/elasticsearch-dump#922]
Hello, 
Thanks for your help,
I was trying to execute the bash and caught in to below error,
![image](https://user-images.githubusercontent.com/39517229/194038512-74fe5d83-21d1-47f4-afde-7c5c32b03517.png)

Used command,
nohup sh load.sh > ../backup_10_4_logs/ces_articles_1.17_load.log 2>&1 &
 
`#!/bin/bash
FILES=($(ls *.gz|sort -V))
for fileName in ${FILES[@]};do
        elasticdump --input ${filename} --output=<DESTINATION_AWS_ES_URL>/ces_articles_1.17
done`
_Originally posted by @shashimahawaththa in https://github.com/elasticsearch-dump/elasticsearch-dump/issues/921#issuecomment-1268241105_

**Comment by ferronrsmith** [comment]
The code I sent was a base, i did expect you to add the additional parameters needed. ^_^. There are missing properties

**Comment by shashimahawaththa** [comment]
Hello,
Yeah, my bad, sorry for the confusion. I managed to write proper bash and restored index successfully,
`#!/bin/bash
for i in $(find $dir -name '*.gz' | sort -V);
do
    echo $i;
elasticdump --input="$i" --output="https://vpc-ces-enrichment-es-perf-nn2yqh2gagzcfuleqleruuf3hi.us-east-1.es.amazonaws.com/ces_articles_1.17" --fsCompress --limit=2000 --type=data --overwrite=true
done; `
