### ISSUE TITLE
[FEATURE][REOPEN] Add option --ignore-es-write-errors=false to abort immediately on a 400/500 response from ES

### ISSUE THREAD

**Issue by mfelician** [elasticsearch-dump/elasticsearch-dump#925]
"Cloning": https://github.com/elasticsearch-dump/elasticsearch-dump/pull/370

ES currently does not provide a way to detect if some particular items failed to write into the destination ES. It would be great if Elasticdump could fail with an exit code 1 if any write fails. The current --ignore-errors flag is not suitable as it detects only the transport layer errors, not application-level errors. Without this feature, there is no way to tell if the copy was successful or not.

**Give some examples of implementations**
Possibly the implementation here is good enough already: https://github.com/elasticsearch-dump/elasticsearch-dump/pull/370

**Comment by ferronrsmith** [comment]
Added here #926. Feel free to review and let me know.

**Comment by mfelician** [comment]
[Thank you, confirmation comment added. ](https://github.com/elasticsearch-dump/elasticsearch-dump/pull/926#issuecomment-1282866273)

**Comment by ferronrsmith** [comment]
closed by https://github.com/elasticsearch-dump/elasticsearch-dump/commit/03fe4425b7ea2a3c6dcb504ced8210704aab201e
