### ISSUE TITLE
[FEATURE] Docker run command supports keyboard interrupt

### ISSUE THREAD

**Issue by atomiechen** [elasticsearch-dump/elasticsearch-dump#933]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am using instructed `docker run` methods in [README](https://github.com/elasticsearch-dump/elasticsearch-dump#docker-install) and cannot interrupt it using `Ctrl + C`. I need to open another terminal to use `docker stop` to terminate the long running container, which is quite inconvenient.

**Describe the solution you'd like**
I would like to use elasticdump via docker as one-line command supporting `Ctrl + C` interruption.

**Describe alternatives you've considered**
Wrap the elasticdump command in another shell script `command.sh`
```sh
#!/bin/sh
elasticdump --input=https://localhost:9200/my_index --output=data.ndjson
```
and use it like
```sh
docker run --rm -it elasticdump/elasticsearch-dump ./command.sh
```
In this case I can interrupt normally, because I make the [entrypoint](https://github.com/elasticsearch-dump/elasticsearch-dump/blob/master/docker-entrypoint.sh) to execute `/bin/sh` to run elasticdump commands. The shell captures `SIGINT` and sends to subprocesses. 

**Give some examples of implementations**
The reason behind is that the docker entrypoint is a PID=1 process inside the container, and Linux treats it differently. If PID=1 process has not registered a custom signal handler, the kernel will not fall back to the default behavior of signal handling (like interrupting the process in case of `Ctrl + C`). Reference [here](https://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html#process-behavior-inside-docker-containers).
So the solution could be improving the entrypoint to register custom signal handlers, or to use a shell to run following commands.

**Comment by ferronrsmith** [comment]
Can you submit a PR ?

**Comment by ferronrsmith** [comment]
Test the Dockerfile updates in the branch and let me know if that's what you want. From my testing it seems that way

**Comment by ferronrsmith** [comment]
https://asciinema.org/a/ilmZrxscDnZgQrjSynv3rm4L0

**Comment by atomiechen** [comment]
> Test the Dockerfile updates in the branch and let me know if that's what you want. From my testing it seems that way

@ferronrsmith That was quick. Thank you!

Yet I have to point out that with the original `docker-entrypoint.sh` removed, the example docker usages in README is invalid (I tried), because those don't pass `elasticdump` as the executable (below copied from README):
```
# Copy an index from production to staging with mappings:
docker run --rm -ti elasticdump/elasticsearch-dump \
  --input=http://production.es.com:9200/my_index \
  --output=http://staging.es.com:9200/my_index \
  --type=mapping
docker run --rm -ti elasticdump/elasticsearch-dump \
  --input=http://production.es.com:9200/my_index \
  --output=http://staging.es.com:9200/my_index \
  --type=data

# Backup index data to a file:
docker run --rm -ti -v /data:/tmp elasticdump/elasticsearch-dump \
  --input=http://production.es.com:9200/my_index \
  --output=/tmp/my_index_mapping.json \
  --type=data
```

We may still need `docker-entrypoint.sh` script to check if the `elasticdump` is typed in the command and auto-complete it. Or change README.

**Comment by ferronrsmith** [comment]
I realize this, too. I released a patch https://github.com/elasticsearch-dump/elasticsearch-dump/commit/36bacfc18a567d3273bc3eab867bac665c960674

**Comment by atomiechen** [comment]
That is great! All seems well.
