### ISSUE TITLE
[BUG] Elasticdump Performance Problems - Could use some tips on how to benchmark

### ISSUE THREAD

**Issue by robromanowski** [elasticsearch-dump/elasticsearch-dump#945]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version - 6.94.1
- Elasticsearch version - 7.17
- Node.js version *(note that nodejs v10+ is required for this tool)* - v16.19.0
- Full command you are having issue with (with inputs and outputs)
```
/path/to/location/.nvm/versions/node/v16.19.0/bin/elasticdump \
    --input=${inputserver}/<my_index_name> \
    --httpAuthFile=/path/to/location/elasticsearch-opensearch-utils/opensearch_migration_scripts/dumpfile \
    --output=${outputserver}/<my_index_name> \
    --limit 2500 \
```

**Describe the bug**
I am getting slower than expected performance with Elasticdump. I am sorry if I picked the wrong label, I'm not fully sure its a bug on Elasticdump entirely - but I've been running Elasticdump over many indices now, and I get varying results, and I can't seem to solve it. (Thanks by the way - this tool is a lifesaver trying to migrate to AWS Opensearch).

I will try to give as much detail as possible, I have been testing my own speeds, with changing the limit in the dump and I can't seem to get consistent speeds. I'm looking to see if this is a problem with running Elasticdump over and over, or how to properly optimize and benchmark.

**Benchmarking**
I have already tried to look through previous issues for help and many of them suggest making sure I properly benchmark first to ensure I can properly tune Elasticdump - which makes sense to me. However, I was unsure of what specifically to benchmark (I tried to google and of course found many results) - but if there would be something I can do to benchmark specific performance tests that matter most for Elasticdump's operations, that would be great. Any guidelines or tips of what to check/what to test for!

**Limit**
I have tried to play around with limit (default is 100). I tried to bump it up to 1000, and slowly did my own performance tuning (basic) to measure speeds. I tried:
- 1000
- 2500
- 5000
- 10K
- 25K

I would try to measure the speeds of each operation:
i.e. Got 2500 objects from source to Elasticsearch - and see how long that takes. 
For example, that would take 2 seconds per.

And then compare it to a different limit.
i.e. Got 5000 objects from source to Elasticsearch

In that case it took 4 seconds per - but effectively the 2500 limit, did the same. (2500 at 2 seconds, hits 5000k by 4 seconds - so same speed at 2500 limit and 5000 limit) - So they were equal. (in this test)

I did notice at some larger ones (10k, 25k limit) it would be slower sometimes compared to the speed of each 5K limit, but other tiems faster.

**So that is where some of my questions are** - is the limit speed solely dependent on the cluster (performance of cluster? how much computer it has)?  **or is dependent at index level?**

For example - would fields/field limit of an index matter? I did some rough testing and it's too small of a sample size - but would something like this matter? (reference on field count: https://stackoverflow.com/questions/40586020/get-the-number-of-fields-on-an-index/40655667#40655667)

It could be coincidence but on multiple indices that were similar size doc.counts, I tried to check the field size on them. The indices that had a small field size (like 40) seemed to be faster, and the indices with a large field size (100, even 800) were slower. Would more fields cause the slowness? All things equivalent otherwise? i.e. 2 indices, both 1 million records, both using 5k limit, but completely polar opposite number of fields in the 2 indices. Is this even something I have to worry about (maybe I'm overthinking?)

Should I be changing limit based on field size?

**Additional context**
If there is any other information I can provide, or tests needed to run, please let me know. I hope this isn't the wrong spot, or a wrong use of the issues, I was just spinning my wheels after reading all the documentation and as much issues I could search for relevant to this.

So far the tool has been great on 99% of my indices, cause they are small, however there are 2-3 that are 20-50 million records, and one ran in 4 hours (testing various limits) and now the next 20 million one has taken over 8 - so that's where this started - I'm trying to figure out why I am seeing such different times (double the hours) for seemingly similar sized indices (but again there must be more to it than just doc.count in an index).

I have a 300 million index coming up, and that is my main concern based on my overnight times of running just on 20 million.

**Comment by ferronrsmith** [comment]
There is a lot of things you can do to improve throughput, but saying that is directly related to the library is a bit hasty. 

- Try modifying the fields returned (maybe you don't need all the fields)
- Try increasing the resources to NODE (NODE_OPTIONS="--max_old_space_size=700000").
- Try tuning elasticsearch. 

All in all there is so much that can be done. It's really for a library to do all these things and provide flexibility and frankly it's beyond the capabilities of the library.

A document size is different. You know your data, the library makes no assumptions. Tune the settings until you get something desired. Beyond that there isn't much I can say, and this is true for any library that dumps data.
