### ISSUE TITLE
ElasticsearchIllegalArgumentException[Failed to decode scrollId]

### ISSUE THREAD

**Issue by vijaya89** [elasticsearch-dump/elasticsearch-dump#946]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version 6.96.0
- Elasticsearch version 1.5 
- Node.js version *(note that nodejs v10+ is required for this tool)*
- ./elasticdump --input https://test-es-aws-jn7j77vczxbykzsj7dckd3iasy.us-east-1.es.amazonaws.com --output https://test-opensearch-6odtzoc2sug7bfwhhjt6zwvgda.us-east-1.es.amazonaws.com --output-index alerts-index --searchBody "{\"query\":{\"match\":{\"typeCode\": \"test\"}}}" --awsAccessKeyId test --awsSecretAccessKey test 

- starting dump
Wed, 25 Jan 2023 22:56:21 GMT | got 100 objects from source elasticsearch (offset: 0)
Wed, 25 Jan 2023 22:56:22 GMT | sent 100 objects to destination elasticsearch, wrote 100
Wed, 25 Jan 2023 22:56:22 GMT | Error Emitted => {"error":"ElasticsearchIllegalArgumentException[Failed to decode scrollId]; nested: IOException[Bad Base64 input character decimal 123 in array position 0]; ","status":400}
Wed, 25 Jan 2023 22:56:22 GMT | Error Emitted => {"error":"ElasticsearchIllegalArgumentException[Failed to decode scrollId]; nested: IOException[Bad Base64 input character decimal 123 in array position 0]; ","status":400}
Wed, 25 Jan 2023 22:56:22 GMT | Total Writes: 0
Wed, 25 Jan 2023 22:56:22 GMT | dump ended with error (get phase) => BAD_REQUEST: {"error":"ElasticsearchIllegalArgumentException[Failed to decode scrollId]; nested: IOException[Bad Base64 input character decimal 123 in array position 0]; ","status":400}

**Describe the bug**
Getting error when trying to migrate data from aws hosted es 1.5 to open search 2.3
proccess is writing only 100 records and exiting

**Comment by ferronrsmith** [comment]
fix on `es-aws-1.5` branch should resolve your issue

**Comment by ferronrsmith** [comment]
related to https://github.com/elasticsearch-dump/elasticsearch-dump/issues/385
