### ISSUE TITLE
Does ElasticSearch dump supports aws opensearch serverless?

### ISSUE THREAD

**Issue by vijaya89** [elasticsearch-dump/elasticsearch-dump#950]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version 6.96.2
- Elasticsearch version aws managed es 1.5
- Node.js version *(note that nodejs v10+ is required for this tool)*
- Full command you are having issue with (with inputs and outputs)
./elasticdump \
--input https://search-dev-llna-alerts-test.us-east-1.es.amazonaws.com \
--output https://tesst.us-east-1.aoss.amazonaws.com \
--output-index test\
--limit 10000 \
--awsAccessKeyId test \
--awsSecretAccessKey test/aaj \
--sessionToken test
- A data-set you can share publicly which reproduces the problem
- 

**Describe the bug**
I am trying to import data from elastic search to open search serverless. Does elastic search dump support open search serverless?

Receiving this error when trying to run :
Thu, 02 Feb 2023 00:28:17 GMT | starting dump
Thu, 02 Feb 2023 00:28:20 GMT | got 10000 objects from source elasticsearch (offset: 0)
Thu, 02 Feb 2023 00:28:21 GMT | Error Emitted => The requested resource could not be found but may be available in the future. Subsequent requests by the client are permissible.
Thu, 02 Feb 2023 00:28:21 GMT | Error Emitted => The requested resource could not be found but may be available in the future. Subsequent requests by the client are permissible.
Thu, 02 Feb 2023 00:28:21 GMT | Total Writes: 0
Thu, 02 Feb 2023 00:28:21 GMT | dump ended with error (get phase) => NOT_FOUND: The requested resource could not be found but may be available in the future. Subsequent requests by the client are permissible.

**Comment by ferronrsmith** [comment]
No it doesn't and won't be supported
