### ISSUE TITLE
[BUG]How to run elasticdump using Bearer token

### ISSUE THREAD

**Issue by jainpratik163** [elasticsearch-dump/elasticsearch-dump#951]
**Context**
how can we run this utility using Bearer as we are not allowed to use a username and password?

In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 6.96.2
- Elasticsearch version : 7.17
- Node.js version *(note that nodejs v10+ is required for this tool)*: v12.16.2
- Full command you are having issue with (with inputs and outputs)
- A data-set you can share publicly which reproduces the problem

**Describe the bug**
we are trying to run using Bearer token and getting this error **`Error Emitted => {"code":500,"message":"Internal Error","error":{}}Authentication finally failed`**

**Comment by ferronrsmith** [comment]
It's important to read the docs

```
# ensure that that json param is properly escaped
--headers='{"Authorization":"Bearer {TOKEN}}}'
```

**Comment by jainpratik163** [comment]
the command is not working 
elasticdump --input=https://<URL>/<index> --headers='{"Authorization":"Bearer {TOKEN}"}' --output=/root/tempppp_down/my_index_new.json

ERROR:
Sun, 05 Feb 2023 05:33:09 GMT | starting dump
(node:24612) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
Sun, 05 Feb 2023 05:33:09 GMT | Error Emitted => {"code":401,"message":"[invalid bearer token, token lookup failed]","error":{}}Authentication finally failed
Sun, 05 Feb 2023 05:33:09 GMT | Error Emitted => {"code":401,"message":"[invalid bearer token, token lookup failed]","error":{}}Authentication finally failed
Sun, 05 Feb 2023 05:33:09 GMT | Total Writes: 0
Sun, 05 Feb 2023 05:33:09 GMT | dump ended with error (get phase) => UNAUTHORIZED: {"code":401,"message":"[invalid bearer token, token lookup failed]","error":{}}Authentication finally failed

**Comment by ferronrsmith** [comment]
I would expect you to replace {TOKEN} with your actual Bearer token

**Comment by ferronrsmith** [comment]
```
NODE_TLS_REJECT_UNAUTHORIZED=0 elasticdump --input=https://URL/index --headers='{"Authorization":"Bearer WHAT_EVER_YOUR_TOKEN_IS"}' --output=/root/tempppp_down/my_index_new.json
```

**Comment by jainpratik163** [comment]
previously I exported TOKEN but it didn't work but the second command worked.
Thanks

**Comment by jainpratik163** [comment]
now i am trying to copy one index from one ES to another and for one URL I passed Authorization":"Bearer and for another ES I am passing username and password but getting unauthorized
seems like it is passing same bearer token for both ES :( 
```
Tue, 07 Feb 2023 11:24:50 GMT | Error Emitted => {"error":{"root_cause":[{"type":"security_exception","reason":"unable to authenticate with provided credentials and anonymous access is not allowed for this request","additional_unsuccessful_credentials":"oauth2 token: invalid token","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}}],"type":"security_exception","reason":"unable to authenticate with provided credentials and anonymous access is not allowed for this request","additional_unsuccessful_credentials":"oauth2 token: invalid token","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}},"status":401}
Tue, 07 Feb 2023 11:24:50 GMT | Total Writes: 0
Tue, 07 Feb 2023 11:24:50 GMT | dump ended with error (get phase) => UNAUTHORIZED: {"error":{"root_cause":[{"type":"security_exception","reason":"unable to authenticate with provided credentials and anonymous access is not allowed for this request","additional_unsuccessful_credentials":"oauth2 token: invalid token","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}}],"type":"security_exception","reason":"unable to authenticate with provided credentials and anonymous access is not allowed for this request","additional_unsuccessful_credentials":"oauth2 token: invalid token","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}},"status":401}
```

**Comment by ferronrsmith** [comment]
```bash
NODE_TLS_REJECT_UNAUTHORIZED=0 elasticdump --input=https://source_es_url/my-index 
--input-headers='{"Authorization":"Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IklnU2NCQ0k1N"}' 
--output=https://username:passwd@target_es_url/my-index --type=data
```

**Comment by jainpratik163** [comment]
Thanks it works but when we run `elasticdump --help` it didn't show this option `--input-headers`.

**Comment by ferronrsmith** [comment]
Yea you're right, must have not copied it over to the `help file`. I'll fix that in the next release
