### ISSUE TITLE
[FEATURE] Please provide --s3SessionToken option

### ISSUE THREAD

**Issue by jakub-ol** [elasticsearch-dump/elasticsearch-dump#953]
**Is your feature request related to a problem? Please describe.**
There seems to be missing option for temporary credentials usage within S3 flow.
Given the example
```
elasticdump \
  --s3AccessKeyId "${access_key_id}" \
  --s3SecretAccessKey "${access_key_secret}" \
  --input "s3://${bucket_name}/${file_name}.json" \
  --output=http://production.es.com:9200/my_index
```
I would like to have an option to provide session token with `--s3SessionToken` in order to use the tool with AWS SSO.

**Comment by ferronrsmith** [comment]
`--s3Configs` allows for this already. I won't add anymore flags, there's already too much.
