### ISSUE TITLE
[BUG] --includeType option missing

### ISSUE THREAD

**Issue by sternkern** [elasticsearch-dump/elasticsearch-dump#956]
Hi!

**Versions**
- ElasticDump version: 6.97.0
- Elasticsearch version: 7.17.3
- Node.js version: v14.20.1

**Command**
elasticdump  --input=http://localhost:9025/entity-person-search-test-48ab2e0f8c5b9a5933a894aa56686099bd9afb3bfd9e7bd2bc8148682a7296d8 --output=/F/tmp/elastic-search/out --limit 1000 --overwrite --esCompress --fsCompress --noRefresh --includeType alias

**Description:**
I have been trying to use one query to gather all the different types needed for our service (data,alias,mapping,settings), but it seems even though the **includeType** parameter is listed in the read me instructions it is not a valid parameter.

"elasticdump --help" does not list the **includeType** parameter either

**Steps to reproduce the behavior:**
1. Try dumping multiple types of data of an index with the --includeType parameter

**Current behavior**
The command does not fail, accepts the --includeType parameter but it does not change the behaviour of the comment.

**Expected behavior**
The dump should contain all the requested types of data requested as per the read me documentation.

Thank You!

**Comment by ferronrsmith** [comment]
`--includeType` is for `multielasticdump`. 

https://github.com/elasticsearch-dump/elasticsearch-dump#multielasticdump
