### ISSUE TITLE
Password contains @ 

### ISSUE THREAD

**Issue by lxy690612941** [elasticsearch-dump/elasticsearch-dump#957]
elasticdump --input=https://test01:test01@123@ip:9200/test--output=test_data.json --limit=10 --type=data

@  %40
:    %3a

elasticdump --input=https://test01:test01%40123@ip:9200/test --output=test_data.json --limit=10 --type=data

Fri, 24 Feb 2023 03:08:20 GMT | starting dump
Fri, 24 Feb 2023 03:08:20 GMT | Error Emitted => unable to verify the first certificate
Fri, 24 Feb 2023 03:08:20 GMT | Error Emitted => unable to verify the first certificate

**Comment by ferronrsmith** [comment]
username/password isn't encoded. Has to be encoded before being passed.
