### ISSUE TITLE
[BUG] The location information prompted when the import fails due to a JSON file format error is incorrect

### ISSUE THREAD

**Issue by bianyun** [elasticsearch-dump/elasticsearch-dump#958]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: [ 6.97.0 ]
- Elasticsearch version: [ 6.8.23 ]
- Node.js version *(note that nodejs v10+ is required for this tool)*: [ 16.18.0 ]
- Full command you are having issue with (with inputs and outputs): [ see attached picture ]
- A data-set you can share publicly which reproduces the problem: [ Artificially modifying the JSON file exported by elasticdump makes its format wrong. Note: the error position must be greater than 65536 to reproduce this problem. ]

**Describe the bug**
As the title says, the location information prompted when the import fails due to a JSON file format error is incorrect, and it seems that the position value of the prompt is the value after modulo 65536 of the real position value.

**To Reproduce**
1. Get any JSON file exported by elasticdump, the character length of the file is required to be greater than 65536.
2. Modifying any position after the position greater than 65536 makes the JSON file format wrong.
3. Then use 'elasticdump' to import this JSON file, and the output will prompt that the JSON format is wrong (may include the location of the error).

**Current behavior**
The location information prompted when the import fails due to a JSON file format error is incorrect, and it seems that the position value of the prompt is the value after modulo 65536 of the real position value.

**Expected behavior**
The location information prompted when the import fails due to a JSON file format error should be the real location value.

**Screenshots**
![00](https://user-images.githubusercontent.com/4619776/224597453-46e4f61f-64dc-4118-b929-444e140609fe.png)

![01_1](https://user-images.githubusercontent.com/4619776/224597467-1d5eceb2-81ad-4c61-a079-3ba4fff83463.png)

![01_2](https://user-images.githubusercontent.com/4619776/224597478-6415beb4-f1ba-4b63-b3ac-196bd7d4f503.png)

<img width="390" alt="01_3" src="https://user-images.githubusercontent.com/4619776/224597685-1e21954c-dceb-4036-89d9-eaccc1fe616d.png">

![02_1](https://user-images.githubusercontent.com/4619776/224597611-dd3e5c93-c619-4dab-9fc3-0581ba694ced.png)

![02_2](https://user-images.githubusercontent.com/4619776/224597643-fc5d2397-6323-4040-8c3b-3f99a38ef100.png)

<img width="390" alt="02_3" src="https://user-images.githubusercontent.com/4619776/224596801-9501e3c8-7205-4efa-8edb-e5638c49d611.png">

**Additional context**
None.

> A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What was the url? What steps will reproduce the issue? What OS experience the problem? All these details will help to fix any potential bugs as soon as possible.

**Comment by ferronrsmith** [comment]
The position is relative to the line being read. The file is read as JSONL, line-by-line. As it relates to the positioning, this is handled by third-party libraries and there isn't much I can do here.

**Comment by bianyun** [comment]
I checked the source code and found that this bug comes from the JSONStream package (v1.3.5) that parses json files. So I locate the problem locally, and then fix the problem, and the correct location information can be printed in the exception information. (see attached image below)

However, this project is now in an unmaintained archived state, so it may be necessary to fork a new project based on the last version of this project, and release it after fixing this bug. Do you think this solution is feasible?

But I still don't know how to publish an npm project. I wonder if you can help me with this?

<img width="587" alt="03_0" src="https://user-images.githubusercontent.com/4619776/224701904-4bfdf971-6733-4759-a444-8c6d39c9734e.png">

<img width="581" alt="03_1" src="https://user-images.githubusercontent.com/4619776/224701965-708c583c-e3a5-4c4d-89d5-de4e923dab0e.png">

<img width="587" alt="03_2" src="https://user-images.githubusercontent.com/4619776/224702593-0a681185-552e-450f-8b55-6e4b8524f614.png">

<img width="587" alt="03_3" src="https://user-images.githubusercontent.com/4619776/224701993-029471c0-387a-4cbe-99c2-eb4120844121.png">

```javascript
exports.parse = function (path, map) {
  var header, footer
  var parser = new Parser()
  
  var offset = 0;
  var stream = through(function (chunk) {
    const chunkBytesLen = (new TextEncoder().encode(chunk)).length
    
    if('string' === typeof chunk) {
      chunk = bufferFrom ? Buffer.from(chunk) : new Buffer(chunk)
    }
    parser.write(chunk)
    
    offset += chunkBytesLen
  },
  function (data) {
    if(data)
      stream.write(data)
    if (header)
        stream.emit('header', header)
    if (footer)
      stream.emit('footer', footer)
    stream.queue(null)
  })

  parser.onError = function (err) {
    const originalErrMsg = err.message
    if(originalErrMsg && originalErrMsg.indexOf("at position") > -1) {
      const regex = /at position ([1-9][0-9]*) /
      const positionNumMatch = originalErrMsg.match(regex)
      if (positionNumMatch && positionNumMatch.length > 1) {
        const relativeBytePos = parseInt(positionNumMatch[1])
        const absolutePosition = offset + relativeBytePos + 1
        const fixedErrMsg = originalErrMsg.replace(regex, 'at position ' + absolutePosition + ' ')
        err.message = 'Invalid JSON (' + fixedErrMsg + ')'
      } else {
        err.message = 'Invalid JSON (' + originalErrMsg + ')';
      }
    }
    stream.emit('error', err)
  }
}
```

**Comment by ferronrsmith** [comment]
Send me a patch file of the changes

**Comment by bianyun** [comment]
Thank you very much.

Ferron H ***@***.***> 于2023年3月13日周一 22:55写道：

**Comment by bianyun** [comment]
https://gist.github.com/bianyun/9fa8f45a5d1971f2979db446690681f7

**Comment by bianyun** [comment]
```new TextEncoder().encode(chunk).length``` This piece of code is only used to find out the size of the buffer in bytes, so that the exact offset that has been processed can be calculated.

If there is another way with better performance, you can replace this statement, as long as you can calculate the actual number of bytes of the UTF-8 string stored in the buffer.

I haven't done a comparison test, but I feel that the main time consumption is still in the step of writing data to ES.

**Comment by ferronrsmith** [comment]
I suspect it would have a performance impact, compounded since this method is used a lot. Did you tryng getting the length of the actual buffer ?

https://nodejs.org/api/buffer.html#buflength

**Comment by bianyun** [comment]
Yes, the purpose of this statement is simply to obtain the exact value of the byte size of the buffer.

If you are worried that this statement will cause performance problems, then I think you can directly replace this statement with ```offset += 65536```, because in most cases, the size of this buffer is 65536 bytes. Only when the character at the boundary happens to be a double-byte character or a three-byte character, can the buffer size be reduced to 65534 or 65535.

So, even if a fixed value of 65536 is used to calculate the offset, the resulting JSON malformed position value is basically accurate.

**Comment by bianyun** [comment]
@ferronrsmith 
Thank you for your hint. I changed the previous statement that may have performance problems to `chunk.byteLength`, which should be better.

The patch file v2:  https://gist.github.com/bianyun/d44035cc6add96d694c60416bef7f5bd

**Comment by ferronrsmith** [comment]
That's sounds good

**Comment by bianyun** [comment]
Thanks for your help.

**Comment by ferronrsmith** [comment]
resolved https://github.com/elasticsearch-dump/elasticsearch-dump/commit/e0a519a2805937063d0dd10a94c6cc2329498edc

**Comment by bianyun** [comment]
👍
