### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by johnt-softclouds** [elasticsearch-dump/elasticsearch-dump#959]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version:  Docker image elasticdump/elasticsearch-dump
- Elasticsearch version: Opensearch 2.4
- Node.js version : v16.16.0
- Full command you are having issue with (with inputs and outputs)

(base)> docker run --name es-dump --rm -ti   elasticdump/elasticsearch-dump     --input=http://localhost:9200/recipe_en     --output=./recipe_en.json
Mon, 13 Mar 2023 21:45:03 GMT | starting dump
Mon, 13 Mar 2023 21:45:23 GMT | Error Emitted => connect ECONNREFUSED 127.0.0.1:9200
Mon, 13 Mar 2023 21:45:23 GMT | Error Emitted => connect ECONNREFUSED 127.0.0.1:9200
Mon, 13 Mar 2023 21:45:23 GMT | Total Writes: 0
Mon, 13 Mar 2023 21:45:23 GMT | dump ended with error (get phase) => Error: connect ECONNREFUSED 127.0.0.1:9200

**Describe the bug**
Not able to connect to a local instance of Opensearch 2.4

**Comment by ferronrsmith** [comment]
https://github.com/elasticsearch-dump/elasticsearch-dump#docker-install
