### ISSUE TITLE
[BUG] Elasticsearch behind reverse proxy with pathprefix stripping

### ISSUE THREAD

**Issue by josephholten** [elasticsearch-dump/elasticsearch-dump#961]
**Context**
- ElasticDump version: 6.99.0
- Elasticsearch version: 7.17.9
- Node.js version: v16.19.0
- Full command you are having issue with (with inputs and outputs):
`
elasticdump --input=https://example.com/searchdb/my-index --output=http://localhost:9200/my-index --type=mapping
`

**Describe the bug**
When the elasticsearch instance is behind a reverse-proxy (e.g. traefik) and reachable only through a specific path wich is stripped before forwarding the request, not just the host, e.g. "example.com/searchdb", elasticdump ignores this path, and just uses the host.

**To Reproduce**
1. Set up elasticsearch behind reverse-proxy, reachable under "example.com/searchdb"
2. call the command, see above

**Current behavior**
Using curl as in
`
curl -XPOST https://example.com/searchdb/asstr-stories/_search -D '{"query": {"match": {"text": "hello"}}}'
`
works.

Elasticdump ignores the path, possibly treats it as an index?
It seems to try to send requests to `example.com` instead of `example.com/searchdb`.

**Expected behavior**
Elasticdump honours the path.
Maybe some way to seperate host with path and index

**Comment by ferronrsmith** [comment]
This isn't a bug. The standard ES routes have been defined, using a reverse proxy to change the URLs doesn't affect the library only your setup.

**Comment by ferronrsmith** [comment]
```bash

elasticdump --input=https://example.com/searchdb --input-index=my-index --output=http://localhost:9200/my-index --type=mapping
```

The above should work

**Comment by josephholten** [comment]
Thank's a lot for the quick reply and fix!! Works like a charm. Totally missed the section on "Non-Standard Install". My bad :)
