### ISSUE TITLE
[BUG] Unable to transfer index sort field

### ISSUE THREAD

**Issue by zhang8473** [elasticsearch-dump/elasticsearch-dump#965]
**Context**
- ElasticDump version lastest docker build
- Elasticsearch version  8.7.0

**Describe the bug**

**To Reproduce**
Dump:
`multielasticdump --input=http://localhost:9200 --match="^xxxx_0" --ignoreType='data' --direction=dump --output=/tmp/es_backup`
OK.

Restore:
`multielasticdump --input=/tmp/es_backup --match="^xxxx_0" --direction=load --ignoreType='data' --output=http://localhost:9201
`

**Current behavior**
"unknown index sort field" error. Indices are not created.
 Since it creates mappings and settings sequentially,  mappings and settings must be created together in order to let "index.sort" work.

**Expected behavior**
No error

**Screenshots**

**Additional context**

> A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What was the url? What steps will reproduce the issue? What OS experience the problem? All these details will help to fix any potential bugs as soon as possible.

**Comment by ferronrsmith** [comment]
using mapping and setting at the same time is a bit redundant. this is a user error

**Comment by ferronrsmith** [comment]
you might just have to manually merge this, this library doesn't handle dependencies

**Comment by zhang8473** [comment]
Could you add an option for settings and mapping s together?

**Comment by ferronrsmith** [comment]
There is some edge cases and I don't want to have to enforce limitations on the user. Best if this is handled by them. Should be fairly easy to write an opinionated merge tool

**Comment by zhang8473** [comment]
Actually, if I say -ignoreType='data', I suppose the es-dump should create the others(mappings settings aliases,...) together, not one by one. That may not be a separate option but just an optimization. What do you think?

**Comment by ferronrsmith** [comment]
Not everyone will want that option to merge different types. Also I don't really see the benefit of this, beyond the index creation. I might add a --index type, still thinking about it

**Comment by ferronrsmith** [comment]
https://github.com/elasticsearch-dump/elasticsearch-dump/tree/chore/index-opt

added a new `--type index`. Try this and let me know if it works for you

**Comment by ferronrsmith** [comment]
available since elasticsearch-dump v[6.100.0](https://github.com/elasticsearch-dump/elasticsearch-dump/commit/127f65964739256df130b85cce0bd410a1ed4ac4)
