### ISSUE TITLE
Bug?  searchBodyTmp is a string, not obj

### ISSUE THREAD

**Issue by hbak** [elasticsearch-dump/elasticsearch-dump#967]
I've been getting an error trying to use both the --limit and --searchBody parameters.

https://github.com/elasticsearch-dump/elasticsearch-dump/blob/533255fb28ad168dace02ffe0c3b86116ace0727/lib/transports/__es__/_data.js#L22

It appears to my superficial view that searchBodyTmp here is supposed to be an object, so that later on in line 56 you can add the "size" parameter to the search body, then on line 62 it's stringified.

I altered line 22 to JSON.parse(this.searchBody) and the code then appeared to work.

**Comment by ferronrsmith** [comment]
Not sure what the issue is, because you haven't show anything. This needs more information.
