### ISSUE TITLE
Dumping index fails because of security policy (CSP)

### ISSUE THREAD

**Issue by mapa17** [elasticsearch-dump/elasticsearch-dump#973]
Hello,
i want to export one index to a json dump, but doing so get a long error message finishing with

`\"kbnWelcomeTitle\">Please upgrade your browser</h2><div class=\"kbnWelcomeText\">This Elastic installation has strict security requirements enabled that your current browser does not meet.</div></div><script>\n            // Since this is an unsafe inline script, this code will not run\n            // in browsers that support content security policy(CSP). This is\n            // intentional as we check for the existence of __kbnCspNotEnforced__ in\n            // bootstrap.\n            window.__kbnCspNotEnforced__ = true;\n          </script><script src=\"/bootstrap.js\"></script></body></html>"
`

I have little not no knowledge of elastic. Is this an issue with how I use elasticsearch-dump? Or how our elastic server is configured?
Can someone point in min a direction?

thx,
Manuel

**Comment by ferronrsmith** [comment]
https://stackoverflow.com/questions/63897826/kibana-has-strict-security-requirements-enabled-that-your-current-browser-does-n

That's for Kibana, not Elasticsearch

**Comment by mapa17** [comment]
For people having similar issues.
Yes this is an Kibana issue, and I ran into it, because I was specifying the kibana web ui address, instead of the elastic server address.
