### ISSUE TITLE
[BUG] AWS SDK version

### ISSUE THREAD

**Issue by truanguyenvan** [elasticsearch-dump/elasticsearch-dump#980]
Hi @all,

I encountered the above problem when dumping data. Even though I don't use AWS

![image](https://github.com/elasticsearch-dump/elasticsearch-dump/assets/57806681/274db764-4de2-4c82-8462-cc669194b7db)

**Comment by ferronrsmith** [comment]
`NODE_TLS_REJECT_UNAUTHORIZED=0` flag should be used with self-signed signatures.
