### ISSUE TITLE
[SUPPORT kerberos authentication]

### ISSUE THREAD

**Issue by jacobluo** [elasticsearch-dump/elasticsearch-dump#981]
[SUPPORT kerberos authentication], thank you.

**Comment by ferronrsmith** [comment]
That's outside the scope of this project.

**Comment by jacobluo** [comment]
if es use kerberos authentication，how can i use elasticsearch-dump to connect es ？

step 1：
kinit  my_keytable_file。【OK】

step 2：
elasticsearch-dump 。。。 【how to do】

thank you very much。

---
for example， curl：

$ curl --negotiate -u : -b ~/cookiejar.txt -c ~/cookiejar.txt http://localhost:14000/webhdfs/v1/?op=liststatus

**"--negotiate" option enables SPNEGO**

**Comment by ferronrsmith** [comment]
That would be a functionality of the underlining library, but as I said that's something outside the scope of this project.

You can look at this PR https://github.com/request/request/pull/1966/files

and see if that can help you achieve what's you're trying.

**Comment by jacobluo** [comment]
thank you for your patience.

from PR, request.js supports "negotiate"。
but which parameter should I pass to elasticsearch-dump to enable the "negotiate" feature ?
