### ISSUE TITLE
[Question] Interest in updating description to Import and export tools for elasticsearch and opensearch?

### ISSUE THREAD

**Issue by brijos** [elasticsearch-dump/elasticsearch-dump#982]
**Is your feature request related to a problem? Please describe.**
OpenSearch reporting users who want to use elasticsearch-dump have doubts if OpenSearch is supported. Based on the version updates, one can clearly see that it is, but when one searches using Google it doesn't register.

**Describe the solution you'd like**
Is there interest in the project to include opensearch support as part of the repo description and tags?

**Describe alternatives you've considered**
Leaving as is and letting users figure it out for themselves.

**Give some examples of implementations**
Import and export tools for elasticsearch and opensearch

**Additional context**
Not applicable.

**Comment by anirudha** [comment]
thanks for posting this, we have many users asking for this and using this

**Comment by anirudha** [comment]
if the maintainers are ok we can also help contribute the change
we will need some guidance and support

**Comment by ferronrsmith** [comment]
The documentation is pretty clear on this. Support for opensearch was added in 6.76.0

**Comment by anirudha** [comment]
updating readme, is that ok?

**Comment by ferronrsmith** [comment]
Merged changes
