### ISSUE TITLE
How to set the size of Elasticsearch s3 blocks chunk size ？

### ISSUE THREAD

**Issue by dazer007** [elasticsearch-dump/elasticsearch-dump#985]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version  6.103.0
- Elasticsearch version  7.13.0
- Node.js version v16.18.1
- Full command you are having issue with (with inputs and outputs)
```
nohup elasticdump \
  --s3AccessKeyId=xxxxxx\
  --s3SecretAccessKey=yyyyy \
  --input=http://elastic:mypassword@192.168.0.36:9200/nuc_person_query \
  --output=s3://elasticdump-s3/biz_nuc.json \
  --limit=100000 \
  --s3ForcePathStyle=false \
  --s3Endpoint=oss-cn-chengdu.aliyuncs.com > esdump_log-nuc_person_query.log 2>&1 & 
```

**Describe the bug**
Part number must be an integer between 1 and 10000
![image](https://github.com/elasticsearch-dump/elasticsearch-dump/assets/6936476/da729676-e403-438f-9742-c13c61c758be)
![image](https://github.com/elasticsearch-dump/elasticsearch-dump/assets/6936476/d1da3165-28cc-40fd-8b8f-eac2cd8e2b5e)

**Seek help**
How to set the size of Elasticsearch s3 blocks ?? Elasticdump export data is quite large, and the number of s3 shards has exceeded 10000, resulting in upload failure。

**Comment by ferronrsmith** [comment]
Read the documentation. There is a `fileSize` param

**Comment by ferronrsmith** [comment]
That option isn't available.

**Comment by ayeshasiddiqs** [comment]
@ferronrsmith any updates on this? like uploading to S3 from Elastic search, would `--expected-size` work in elasticdump? Error faced `Error Emitted => Part number must be an integer between 1 and 10000, inclusive` for an index of sixe 600GB with --limit=5000 and --scrollTime=10m

**Comment by ferronrsmith** [comment]
You need to limit the size of the chunk going to s3 using the `fileSize` param. This was already stated and could be ascertained by reading the documentation.
