### ISSUE TITLE
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by dazer007** [elasticsearch-dump/elasticsearch-dump#986]
/**Context**
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

- ElasticDump  6.103.0
- Elasticsearch 7.14.0
- Node.js version v16.18.1

**script**
```
#!/bin/bash

# forearch 
echo 'bakcup to oss '
for index in nuc_tube_person_conn nuc_tube_person_distinct nuc_tube_person_all; do
  echo "bakeup index: $index"
  
  ..............................................................
   
  echo "index$index bakeup start"
  echo ""
done
```
```shell
nohup elasticdump   --s3AccessKeyId=xxxxx   --s3SecretAccessKey=yyyyy   --input=http://elastic:zzzzzzz@192.168.0.36:9200/nuc_tube_person_all   --output=s3://elasticdump-s3/nuc_tube_person_all.json   --limit=100000   --fileSize=40gb   --s3ForcePathStyle=false   --s3Compress   --s3Endpoint=oss-cn-chengdu.aaaaaaaa.com > esdump_log-nuc_tube_person_all   .log 2>&1 &
  980  tail -f esdump_log-nuc_tube_person_all   .log
```

**Describe the bug**
> `<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x7fc247509268 node::Abort() [/lib64/libnode.so.93]
 2: 0x7fc2473f6b89  [/lib64/libnode.so.93]
 3: 0x7fc248700a00 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/lib64/libnode.so.93]`

**Screenshots**
![image](https://github.com/elasticsearch-dump/elasticsearch-dump/assets/6936476/42867d12-ef20-4ab2-8b3c-1d2a1b41d592)

**help**
How to built-in adjust memory size for Elasticdump; Or I can only perform the export in batches.

Or can we increase support for memory sharding adjustment.

**Comment by ferronrsmith** [comment]
You can use `NODE_OPTIONS="--max-old-space-size=16384"` to increase the heap size. The heap size is controlled by node.js, not Elasticdump. You also might want to think about using smaller fileSize

**Comment by dazer007** [comment]
thanks.
