### ISSUE TITLE
[QUESTION] Dumping data from ElasticSearch index without cluster-level privileges

### ISSUE THREAD

**Issue by liambaloh** [elasticsearch-dump/elasticsearch-dump#989]
Hello! I'm trying to dump data from a shared ElasticSearch server which I only have read/write/manage access to certain indexes. As far as I know I don't have any cluster level privileges. Or at least I'm not able to check them via `_security/user/_privileges`.  

Running the following command in PowerShell...

```
elasticdump 
    --input=https://<url>:9200/<index-i-have-read-write-manage-on> 
    --output "D:\Github\ElasticSearchBackup.json" 
    --headers '{\"Authorization\": \"ApiKey <api-key>\"}'
```

...gives me the following result:

```
Tue, 05 Sep 2023 15:00:39 GMT | starting dump
(node:2520) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
Tue, 05 Sep 2023 15:00:39 GMT | Error Emitted => {"error":{"root_cause":[{"type":"security_exception","reason":"action [cluster:monitor/main] is unauthorized for API key id [<api-key-id>] of user [<myuser>], this action is granted by the cluster privileges [monitor,manage,all]"}],"type":"security_exception","reason":"action [cluster:monitor/main] is unauthorized for API key id [<api-key-id>] of user [<myuser>], this action is granted by the cluster privileges [monitor,manage,all]"},"status":403}
Tue, 05 Sep 2023 15:00:39 GMT | Error Emitted => {"error":{"root_cause":[{"type":"security_exception","reason":"action [cluster:monitor/main] is unauthorized for API key id [<api-key-id>] of user [<myuser>], this action is granted by the cluster privileges [monitor,manage,all]"}],"type":"security_exception","reason":"action [cluster:monitor/main] is unauthorized for API key id [<api-key-id>] of user [<myuser>], this action is granted by the cluster privileges [monitor,manage,all]"},"status":403}
Tue, 05 Sep 2023 15:00:39 GMT | Total Writes: 0
Tue, 05 Sep 2023 15:00:39 GMT | dump ended with error (get phase) => FORBIDDEN: {"error":{"root_cause":[{"type":"security_exception","reason":"action [cluster:monitor/main] is unauthorized for API key id [<api-key-id>] of user [<myuser>], this action is granted by the cluster privileges [monitor,manage,all]"}],"type":"security_exception","reason":"action [cluster:monitor/main] is unauthorized for API key id [<api-key-id>] of user [<myuser>], this action is granted by the cluster privileges [monitor,manage,all]"},"status":403}
```

here's the returned Json:
```json
{
    "error": {
        "root_cause": [
            {
                "type": "security_exception",
                "reason": "action [cluster:monitor/main] is unauthorized for API key id [<api-key-id>] of user [<myuser>], this action is granted by the cluster privileges [monitor,manage,all]"
            }
        ],
        "type": "security_exception",
        "reason": "action [cluster:monitor/main] is unauthorized for API key id [<api-key-id>] of user [<myuser>], this action is granted by the cluster privileges [monitor,manage,all]"
    },
    "status": 403
}
```

What I'm trying to do is to download the content of the specific ElasticSearch index to my local drive into a json file or files

Is there anyway to bypass the need to fetch the cluster-level endpoint? For example can I provide it with the data it needs from there through other flags? Should I be specifying indexes in some other way? I read similar complaints relating to OpenSearch specifically [Example 1](https://stackoverflow.com/questions/73042858/why-does-it-need-clustermonitor-main-permission) & [Example 2](https://stackoverflow.com/questions/73055858/head-and-get-in-spring-data-es-4-4-1). These of course relate to different software solutions, but may be relevant. If the `--force-os-version` flag comes into play, are there any known safe versions? 

Any insight and help would be appreciated! Thank you!

**Comment by ebuildy** [comment]
Yes, to get the elasticsearch version, as you can see at 

- https://github.com/elasticsearch-dump/elasticsearch-dump/blob/master/lib/transports/__es__/_base.js#L28  
- https://github.com/elasticsearch-dump/elasticsearch-dump/blob/master/lib/transports/elasticsearch.js#L82
 
 we call ``/``  endpoint.

We could add an option to "set" the version

**Comment by ferronrsmith** [comment]
You don't have the necessary permission to perform the action. Just request the permission needed.
https://www.elastic.co/guide/en/elasticsearch/reference/current/security-privileges.html

**Comment by liambaloh** [comment]
I'm afraid that doesn't quite answer the question. The ElasticSearch instance is shared between various teams and I only have permissions that relate to certain indexes. This is by design. I'm not able to get any additional permissions. While this use-case likely isn't everyone's as most people likely run their own ElasticSearch instances and thus have manager level access to the whole thing, it's also not particularly rare. The setup I'm working with isn't anything particularly out of the ordinary. 

The question here is: Is there any way I can get this software package to perform an export _despite_ the lack of these cluster-level permissions. From a technical standpoint the only non-negotiable permissions would probably be read permissions on the index I want exported, everything else is likely to only be required by the specific implementation and should be bypassable.

So what I'd like to know is whether any mechanism to do such a bypass exists already, or if I should look into modifying it, introducing hardcoded returns, etc. Obviously if a mechanism exists already it'd save me a bunch of time, hence why I'm asking. 

Thanks for any insight you can give and have a lovely day.

**Comment by liambaloh** [comment]
Ok! Thanks for the clarification. Have a lovely day!
