### ISSUE TITLE
Password contains @，Iunable to connect[BUG]

### ISSUE THREAD

**Issue by heng5120** [elasticsearch-dump/elasticsearch-dump#991]
![微信图片_20230918150858](https://github.com/elasticsearch-dump/elasticsearch-dump/assets/35018688/9c22ab26-4021-4504-81dd-6d6f0cc86580)

**Comment by ferronrsmith** [comment]
upstream bug.

https://github.com/nodejs/node/pull/31450#issuecomment-647719491

It's a bug that's also in the request dependency. Workaround is to encode the password/username in the header.


```
Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==
```

**Comment by heng5120** [comment]
thank you
