### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vladimirtiukhtin** [elasticsearch-dump/elasticsearch-dump#992]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version
`6.103.1`
- Elasticsearch version
`8.9.1`
- Node.js version *(note that nodejs v10+ is required for this tool)*
`v14.21.3`
- Full command you are having issue with (with inputs and outputs)
`elasticdump --input=/tmp/data/dump.json --output=https://elasticsearch.test:9200/test --ca=./ca.pem`
- A data-set you can share publicly which reproduces the problem
N/A

**Describe the bug**
With or without --ca and --output-ca I get `Error: unable to get local issuer certificate`. It feels like those options have no effect at all. Curl works perfectly with the same bundle

**Comment by ferronrsmith** [comment]
self sign certificates need 
```bash
NODE_TLS_REJECT_UNAUTHORIZED=0
```

defined

**Comment by vladimirtiukhtin** [comment]
Thanks for the prompt response @ferronrsmith. But why would anyone want to skip TLS verification?

**Comment by vladimirtiukhtin** [comment]
> self-signed certificates cannot be validated by node

This is not true, node very well supports use of custom CAs

**Comment by ebuildy** [comment]
https://nodejs.org/api/cli.html#node_extra_ca_certsfile should work:

```
NODE_EXTRA_CA_CERTS=/path/to/your/cert.pem
```

**Comment by vladimirtiukhtin** [comment]
I can confirm `NODE_EXTRA_CA_CERTS` works. While it's good enough the purpose of `--ca` and similar flags remain unknown

**Comment by ferronrsmith** [comment]
```
--tlsAuth
                    Enable TLS X509 client authentication
--cert, --input-cert, --output-cert
                    Client certificate file. Use --cert if source and destination are identical.
                    Otherwise, use the one prefixed with --input or --output as needed.
--key, --input-key, --output-key
                    Private key file. Use --key if source and destination are identical.
                    Otherwise, use the one prefixed with --input or --output as needed.
--pass, --input-pass, --output-pass
                    Pass phrase for the private key. Use --pass if source and destination are identical.
                    Otherwise, use the one prefixed with --input or --output as needed.
--ca, --input-ca, --output-ca
                    CA certificate. Use --ca if source and destination are identical.
                    Otherwise, use the one prefixed with --input or --output as needed.
```


A CA certificate is a digital certificate issued by a certificate authority (CA), so SSL clients (such as web browsers) can use it to verify the SSL certificates sign by this CA.

> **what you really need is `--cert`. `--ca` is only needed for SELF-SIGNED cert that needs to be validated with `NODE_EXTRA_CA_CERTS` that hasn't been bypassed with `NODE_TLS_REJECT_UNAUTHORIZED`.**

The documentation is clear. `--cert` is for authorization, `--ca` is for validation.

More info on the internal library - https://github.com/request/request#tlsssl-protocol

**Comment by vladimirtiukhtin** [comment]
I know that CA is for validation. My bug report is about despite `--ca` being provided in the command line elasticdump fails to validate target's certificate

**Comment by ferronrsmith** [comment]
> I can confirm `NODE_EXTRA_CA_CERTS` works. While it's good enough the purpose of `--ca` and similar flags remain unknown

I thought you said it works ?

**Comment by ferronrsmith** [comment]
Have you tried using **curl** to validate it works ?

**Comment by vladimirtiukhtin** [comment]
Yes, that's what I stated in the first message ;)

**Comment by vladimirtiukhtin** [comment]
To summarize: curl works, NODE_EXTRA_CA_CERTS works, `--ca` does not

**Comment by ferronrsmith** [comment]
NODE_EXTRA_CA_CERTS=/path/to/your/cert.pem elasticdump --input=/tmp/data/dump.json --output=https://elasticsearch.test:9200/test --ca=./ca.pem --cert=./cert.pem


Did you remember to pass `tlsAuth` flag ?

**Comment by vladimirtiukhtin** [comment]
I don't need to authenticate client, it is not enabled on the ES side. I need client to authenticate server certificate (ES certificate)

**Comment by vladimirtiukhtin** [comment]
It's nice having it work using NODE_EXTRA_CA_CERTS, but if you declare that `--ca` flag does the job and it fact it does not, it's a bug

**Comment by vladimirtiukhtin** [comment]
What's the purpose of `--ca` flag then?
