### ISSUE TITLE
[FEATURE] show progress

### ISSUE THREAD

**Issue by jimmywarting** [elasticsearch-dump/elasticsearch-dump#994]
It would be useful to know how much data there is to be synced and how much data you have already synced. so you can get a percentage of how much is done

**Comment by ferronrsmith** [comment]
this would break existing functionality and require change how the core works. not something that will be implemented, but feel free to submit a PR

**Comment by jimmywarting** [comment]
Just curious how it could break a cli command

**Comment by ferronrsmith** [comment]
short version. 


```
# Backup and index to a gzip using stdout:
elasticdump \
  --input=http://production.es.com:9200/my_index \
  --output=$ \
  | gzip > /data/my_index.json.gz
```

It wouldn't be possible to do both piping and progress report (unless directed to a file which then as to be tailed etc). It can be mutually exclusive, but it's not worth the effort required. In most cases, persons `_cat` the indices periodically and validate the progress.


If you think it's feasible, then you can feel free to submit a PR

**Comment by jimmywarting** [comment]
> It wouldn't be possible to do both piping and progress report

Ah, make sense. 
yea, it would be problematic, progress would only be something "nice to have" not really that important. 

I have never tried using `$` as an output.
I have only used a destination (into another elastic db) and then it was outputting stuff like "exported 100 docs from x, importing 100 docs to y"
that's why i tough it would instead be possible to show some kind of fancy progresbar
Just something like "imported {x} out of total 423678 doc"

```
300 / 423678 docs exported
300 / 423678 docs imported
400 / 423678 docs exported
400 / 423678 docs imported
```
