### ISSUE TITLE
[FEATURE] dump Elasticsearch index via PIT

### ISSUE THREAD

**Issue by JiaoMaWHU** [elasticsearch-dump/elasticsearch-dump#997]
**Is your feature request related to a problem? Please describe.**
Hi repo maintainers, I'm a newbie in this community. I'm wondering is there any version of this repo that uses Point In Time (PIT) feature for index export? I read through the readme, and it seems it's currently based on scroll API.

According to this elastic search [blog](https://www.elastic.co/blog/get-a-consistent-view-of-your-data-over-time-with-the-elasticsearch-point-in-time-reader) and this [medium post](https://medium.com/trendyol-tech/elasticsearch-scroll-api-vs-search-after-with-pit-1e0ec52e47ef), I see
-  "We recommend that you use the new point-in-time functionality in Elasticsearch if you can. The [scroll API](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/scroll-api.html) is no longer recommended for deep pagination (even though it still works)". Scroll API holds unnecessary reference to segments that are not needed for live data. PIT, on the other hand, does not have this problem, and search can be performed even on deleted data.
- The experiment in the medium post shows that using PIT with search_after decreases the response time by 30% compared to scroll API.

Given this advantage of PIT, is there any plan for supporting PIT? If not, what's reason behind it?

**Comment by ferronrsmith** [comment]
No plans to support PIT. Performance is relative. You can import your own transport and incorporate it as part of a custom transport, or send a PR.

It doesn't solve the major wants of most people.

1. Recovery from crashes during index (rare, but possible). **search_after** would help if keep track of the **sort**, but this is also available via the **scroll_id**. 
2. Real point search, meaning ... you can do something like, search_after [record_id]. kinda like offset/count without the performance overhead
