### ISSUE TITLE
[FEATURE] Incremental Dump of ElasticSearch Index

### ISSUE THREAD

**Issue by StephaneZg** [elasticsearch-dump/elasticsearch-dump#999]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Incremental backup on the index to be implemented, so that all the index data is not loaded or downloaded on every dump to it, This could help reduce the process time if we have fast-growing data and we have to back up the whole index all the time

**Describe alternatives you've considered**

**Give some examples of implementations**
Considering we have a newly active database, on the first dump all the data from all indices are backed, also considering that every week there could be around 50 MB of data added to our database it would be very difficult and will take a lot of time (depending of resource provisioned to the task) to dump our indices at the end of the year, So what if we could have an incremental dump that helps us save only changed data

**Additional context**
Reduce Processing time or data load on every dump for a fast-growing database

**Comment by ferronrsmith** [comment]
If an index is designed properly, incremental backups shouldn't be an issue. I've always added core fields to every record in an index. i.e. __updated_date __created_date. These are used for filtering and backup. 

As it stands, the **Elasticsearch** endpoint doesn't support this feature.
